(module info (lib "infotab.ss" "setup")
  (define name "htdch")
  (define compile-subcollections (list (list "htdch" "draw")
				       (list "htdch" "graphics")
                                       (list "htdch" "idraw"))))
