#lang racket/base
(require tests/utils/docs-complete)
;(check-docs (quote deinprogramm/world))
;(check-docs (quote deinprogramm/turtle))
;(check-docs (quote deinprogramm/test-suite))
;(check-docs (quote deinprogramm/syntax-checkers))
;(check-docs (quote deinprogramm/run-dmda-code))
;(check-docs (quote deinprogramm/line3d))
;(check-docs (quote deinprogramm/image))
;(check-docs (quote deinprogramm/DMdA))
;(check-docs (quote deinprogramm/DMdA-vanilla-reader))
;(check-docs (quote deinprogramm/DMdA-reader))
;(check-docs (quote deinprogramm/DMdA-beginner-reader))
;(check-docs (quote deinprogramm/DMdA-assignments-reader))
;(check-docs (quote deinprogramm/DMdA-advanced-reader))
;(check-docs (quote deinprogramm/define-record-procedures))
;(check-docs (quote deinprogramm/convert-explicit))

(check-docs (quote deinprogramm/DMdA-beginner) #:skip #rx"^#%")
(check-docs (quote deinprogramm/DMdA-vanilla) #:skip #rx"^#%")
(check-docs (quote deinprogramm/DMdA-advanced) #:skip #rx"^#%")
(check-docs (quote deinprogramm/DMdA-assignments) #:skip #rx"^#%")
