#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote wxme/xml))
(check-docs (quote wxme/wxme))
(check-docs (quote wxme/text))
(check-docs (quote wxme/test-case))
(check-docs (quote wxme/scheme))
(check-docs (quote wxme/read))
(check-docs (quote wxme/number))
(check-docs (quote wxme))
(check-docs (quote wxme/image))
(check-docs (quote wxme/editor))
(check-docs (quote wxme/comment))
(check-docs (quote wxme/cache-image))
