#lang info

(define collection 'multi)

(define deps '("base"
               "compatibility-lib"
	       "net-lib"
               "sandbox-lib"
               "compiler-lib"
               "scribble-lib"
               "racket-index"))
(define build-deps '("compatibility-doc"
                     "drracket"
                     "errortrace-doc"
                     "sgl"
                     "typed-racket-doc"
                     "unstable"
                     "at-exp-lib"
                     "data-lib"
                     "pconvert-lib"
                     "rackunit-lib"
                     "unstable-contract-lib"
                     "web-server"
                     "gui"
                     "draw"
                     "sandbox-lib"
                     "pict"
                     "parser-tools"
                     "slideshow"
                     "r5rs"
                     "r6rs"
                     "xrepl"
                     "readline"
                     "profile"
                     "syntax-color"
                     "scribble"
                     "compatibility-lib"
                     "future-visualizer"))
