(module inexact-complex typed/scheme #:optimize
  (require racket/unsafe/ops)
  (let-values (((real imag)
                (let-values (((t1-real t1-imag)
                              (let ((t 1.0+2.0i))
                                (values (unsafe-flreal-part t)
                                        (unsafe-flimag-part t))))
                             ((t2-real t2-imag)
                              (let ((t 2.0+4.0i))
                                (values (unsafe-flreal-part t)
                                        (unsafe-flimag-part t)))))
                  (values
                   (unsafe-fl+ t1-real t2-real)
                   (unsafe-fl+ t1-imag t2-imag)))))
    (unsafe-make-flrectangular real imag))
  (let-values (((real imag)
                (let-values (((t1-real t1-imag)
                              (let ((t 1.0+2.0i))
                                (values (unsafe-flreal-part t)
                                        (unsafe-flimag-part t))))
                             ((t2-real t2-imag)
                              (let ((t 2.0+4.0i))
                                (values (unsafe-flreal-part t)
                                        (unsafe-flimag-part t)))))
                  (values (unsafe-fl- t1-real t2-real)
                          (unsafe-fl- t1-imag t2-imag)))))
    (unsafe-make-flrectangular real imag)))
