#lang typed/scheme
(require racket/unsafe/ops)
((lambda: ((t : Integer))
          (let* ((unboxed-float-1 (exact->inexact (sin (* t 6.28))))
                 (unboxed-real-2 0.0)
                 (unboxed-imag-3 0.0)
                 (unboxed-real-4 (unsafe-fl+ unboxed-float-1 unboxed-real-2))
                 (unboxed-imag-5 unboxed-imag-3))
            (unsafe-make-flrectangular unboxed-real-4 unboxed-imag-5)))
 1)
