#lang typed/scheme
(require racket/unsafe/ops)
(let* ((unboxed-real-1 1.0)
       (unboxed-imag-2 2.0)
       (unboxed-imag-3 (unsafe-fl- 0.0 unboxed-imag-2))
       (unboxed-real-4 2.0)
       (unboxed-imag-5 4.0)
       (unboxed-imag-6 (unsafe-fl- 0.0 unboxed-imag-5))
       (unboxed-real-7 (unsafe-fl+ unboxed-real-1 unboxed-real-4))
       (unboxed-imag-8 (unsafe-fl+ unboxed-imag-3 unboxed-imag-6)))
  (unsafe-make-flrectangular unboxed-real-7 unboxed-imag-8))
