#lang typed/scheme #:optimize
(require racket/unsafe/ops)
(let* ((unboxed-gensym-1 1.0+2.0i)
       (unboxed-gensym-2 (unsafe-flreal-part unboxed-gensym-1))
       (unboxed-gensym-3 (unsafe-flimag-part unboxed-gensym-1))
       (unboxed-gensym-4 3.0)
       (unboxed-gensym-5 (unsafe-fl+ unboxed-gensym-2 unboxed-gensym-4))
       (unboxed-gensym-6 unboxed-gensym-3))
  (unsafe-make-flrectangular unboxed-gensym-5 unboxed-gensym-6))
(let* ((unboxed-gensym-1 1.0)
       (unboxed-gensym-2 2.0+4.0i)
       (unboxed-gensym-3 (unsafe-flreal-part unboxed-gensym-2))
       (unboxed-gensym-4 (unsafe-flimag-part unboxed-gensym-2))
       (unboxed-gensym-5 (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-3))
       (unboxed-gensym-6 unboxed-gensym-4))
  (unsafe-make-flrectangular unboxed-gensym-5 unboxed-gensym-6))
(let* ((unboxed-gensym-1 1.0+2.0i)
       (unboxed-gensym-2 (unsafe-flreal-part unboxed-gensym-1))
       (unboxed-gensym-3 (unsafe-flimag-part unboxed-gensym-1))
       (unboxed-gensym-4 3.0)
       (unboxed-gensym-5 (unsafe-fl- unboxed-gensym-2 unboxed-gensym-4))
       (unboxed-gensym-6 unboxed-gensym-3))
  (unsafe-make-flrectangular unboxed-gensym-5 unboxed-gensym-6))
(let* ((unboxed-gensym-1 1.0)
       (unboxed-gensym-2 2.0+4.0i)
       (unboxed-gensym-3 (unsafe-flreal-part unboxed-gensym-2))
       (unboxed-gensym-4 (unsafe-flimag-part unboxed-gensym-2))
       (unboxed-gensym-5 (unsafe-fl- unboxed-gensym-1 unboxed-gensym-3))
       (unboxed-gensym-6 (unsafe-fl- 0.0 unboxed-gensym-4)))
  (unsafe-make-flrectangular unboxed-gensym-5 unboxed-gensym-6))

(+ 1.0+2.0i (+ 1.0 2.0))
