#lang typed/scheme
(require racket/unsafe/ops)
(let* ((unboxed-gensym-1 (unsafe-fx->fl 2))
       (unboxed-gensym-2 1.0+2.0i)
       (unboxed-gensym-3 (unsafe-flreal-part unboxed-gensym-2))
       (unboxed-gensym-4 (unsafe-flimag-part unboxed-gensym-2))
       (unboxed-gensym-5 3.0+6.0i)
       (unboxed-gensym-6 (unsafe-flreal-part unboxed-gensym-5))
       (unboxed-gensym-7 (unsafe-flimag-part unboxed-gensym-5))
       (unboxed-gensym-8 (unsafe-fl+ (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-3)
                                     unboxed-gensym-6))
       (unboxed-gensym-9 (unsafe-fl+ unboxed-gensym-4 unboxed-gensym-7)))
  (unsafe-make-flrectangular unboxed-gensym-8 unboxed-gensym-9))
