#lang typed/scheme
(require racket/unsafe/ops)
(let* ((unboxed-real-1 1.0)
       (unboxed-imag-2 2.0)
       (unboxed-real-3 2.0)
       (unboxed-imag-4 4.0)
       (unboxed-real-5 (unsafe-fl+ unboxed-real-1 unboxed-real-3))
       (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2 unboxed-imag-4))
       (unboxed-imag-7 (unsafe-fl- 0.0 unboxed-imag-6)))
  (unsafe-make-flrectangular unboxed-real-5 unboxed-imag-7))
