#lang typed/scheme

(require racket/unsafe/ops)

(let* ((unboxed-real-1 1.0)
       (unboxed-imag-2 2.0)
       (unboxed-float-1 (let* ((unboxed-real-1 2.0)
                               (unboxed-imag-2 4.0)
                               (unboxed-real-3 3.0)
                               (unboxed-imag-4 6.0)
                               (unboxed-real-5 (unsafe-fl+ unboxed-real-1
                                                           unboxed-real-3))
                               (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2
                                                           unboxed-imag-4)))
                          unboxed-real-5))
       (unboxed-real-2 (unsafe-fl+ unboxed-real-1 unboxed-float-1))
       (unboxed-imag-3 unboxed-imag-2))
  (unsafe-make-flrectangular unboxed-real-2 unboxed-imag-3))
(let* ((unboxed-real-1 1.0)
       (unboxed-imag-2 2.0)
       (unboxed-float-1 (let* ((unboxed-real-1 2.0)
                               (unboxed-imag-2 4.0)
                               (unboxed-real-3 3.0)
                               (unboxed-imag-4 6.0)
                               (unboxed-real-5 (unsafe-fl+ unboxed-real-1
                                                           unboxed-real-3))
                               (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2
                                                           unboxed-imag-4)))
                          unboxed-real-5))
       (unboxed-real-2 (unsafe-fl+ unboxed-real-1 unboxed-float-1))
       (unboxed-imag-3 unboxed-imag-2))
  (unsafe-make-flrectangular unboxed-real-2 unboxed-imag-3))
(let* ((unboxed-real-1 1.0)
       (unboxed-imag-2 2.0)
       (unboxed-float-1 (let* ((unboxed-real-1 2.0)
                               (unboxed-imag-2 4.0)
                               (unboxed-real-3 3.0)
                               (unboxed-imag-4 6.0)
                               (unboxed-real-5 (unsafe-fl+ unboxed-real-1
                                                           unboxed-real-3))
                               (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2
                                                           unboxed-imag-4)))
                          unboxed-imag-6))
       (unboxed-real-2 (unsafe-fl+ unboxed-real-1 unboxed-float-1))
       (unboxed-imag-3 unboxed-imag-2))
  (unsafe-make-flrectangular unboxed-real-2 unboxed-imag-3))
(let* ((unboxed-real-1 1.0)
       (unboxed-imag-2 2.0)
       (unboxed-float-1 (let* ((unboxed-real-1 2.0)
                               (unboxed-imag-2 4.0)
                               (unboxed-real-3 3.0)
                               (unboxed-imag-4 6.0)
                               (unboxed-real-5 (unsafe-fl+ unboxed-real-1
                                                           unboxed-real-3))
                               (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2
                                                           unboxed-imag-4)))
                          unboxed-imag-6))
       (unboxed-real-2 (unsafe-fl+ unboxed-real-1 unboxed-float-1))
       (unboxed-imag-3 unboxed-imag-2))
  (unsafe-make-flrectangular unboxed-real-2 unboxed-imag-3))
