#lang typed/scheme
(require racket/unsafe/ops)
(let* ((unboxed-float-1 (unsafe-fx->fl (unsafe-fxquotient 2 1)))
       (unboxed-real-2 1.0)
       (unboxed-imag-3 2.0)
       (unboxed-real-4 3.0)
       (unboxed-imag-5 6.0)
       (unboxed-real-6 (unsafe-fl+ (unsafe-fl+ unboxed-float-1 unboxed-real-2)
                                   unboxed-real-4))
       (unboxed-imag-7 (unsafe-fl+ unboxed-imag-3 unboxed-imag-5)))
  (unsafe-make-flrectangular unboxed-real-6 unboxed-imag-7))
