#lang typed/scheme
(require racket/unsafe/ops)
((lambda: ((t : Integer))
          (let* ((unboxed-gensym-1 (exact->inexact (sin (* t 6.28))))
                 (unboxed-gensym-2 0.0)
                 (unboxed-gensym-3 0.0)
                 (unboxed-gensym-4 (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-2))
                 (unboxed-gensym-5 unboxed-gensym-3))
            (unsafe-make-flrectangular unboxed-gensym-4 unboxed-gensym-5)))
 1)
