#lang typed/scheme
(require racket/unsafe/ops)
((lambda: ((t : Integer))
          (let* ((unboxed-gensym-1 (exact->inexact (sin (* t 6.28))))
                 (unboxed-gensym-2 0.0+0.0i)
                 (unboxed-gensym-3 (unsafe-flreal-part unboxed-gensym-2))
                 (unboxed-gensym-4 (unsafe-flimag-part unboxed-gensym-2))
                 (unboxed-gensym-5 (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-3))
                 (unboxed-gensym-6 unboxed-gensym-4))
            (unsafe-make-flrectangular unboxed-gensym-5 unboxed-gensym-6)))
 1)
