#lang racket

(require racket/unsafe/ops)

(let* ((unboxed-gensym-1 1.0)
       (unboxed-gensym-2 2.0)
       (unboxed-gensym-3 2.0)
       (unboxed-gensym-4 4.0)
       (unboxed-gensym-5 (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-3))
       (unboxed-gensym-6 (unsafe-fl+ unboxed-gensym-2 unboxed-gensym-4))
       (t2 (let* ((unboxed-gensym-7 3.0)
                  (unboxed-gensym-8 6.0)
                  (unboxed-gensym-9 4.0)
                  (unboxed-gensym-10 8.0)
                  (unboxed-gensym-11 (unsafe-fl+ unboxed-gensym-7 unboxed-gensym-9))
                  (unboxed-gensym-12 (unsafe-fl+ unboxed-gensym-8 unboxed-gensym-10)))
             (unsafe-make-flrectangular unboxed-gensym-11 unboxed-gensym-12)))
       (t3 1.0+2.0i)
       (t4 1))
  (display (let* ((unboxed-gensym-1 (unsafe-fl+ unboxed-gensym-5 unboxed-gensym-5))
                  (unboxed-gensym-2 (unsafe-fl+ unboxed-gensym-6 unboxed-gensym-6)))
             (unsafe-make-flrectangular unboxed-gensym-1 unboxed-gensym-2)))
  (display t2)
  (display t3)
  (display t4))
(void)
