#lang racket

(require racket/unsafe/ops)

(let* ((unboxed-gensym-1 1.0+2.0i)
       (unboxed-gensym-2 (unsafe-flreal-part unboxed-gensym-1))
       (unboxed-gensym-3 (unsafe-flimag-part unboxed-gensym-1))
       (unboxed-gensym-4 2.0+4.0i)
       (unboxed-gensym-5 (unsafe-flreal-part unboxed-gensym-4))
       (unboxed-gensym-6 (unsafe-flimag-part unboxed-gensym-4))
       (unboxed-gensym-7 (unsafe-fl+ unboxed-gensym-2 unboxed-gensym-5))
       (unboxed-gensym-8 (unsafe-fl+ unboxed-gensym-3 unboxed-gensym-6))
       (t2 (let* ((unboxed-gensym-9 3.0+6.0i)
                  (unboxed-gensym-10 (unsafe-flreal-part unboxed-gensym-9))
                  (unboxed-gensym-11 (unsafe-flimag-part unboxed-gensym-9))
                  (unboxed-gensym-12 4.0+8.0i)
                  (unboxed-gensym-13 (unsafe-flreal-part unboxed-gensym-12))
                  (unboxed-gensym-14 (unsafe-flimag-part unboxed-gensym-12))
                  (unboxed-gensym-15 (unsafe-fl+ unboxed-gensym-10 unboxed-gensym-13))
                  (unboxed-gensym-16 (unsafe-fl+ unboxed-gensym-11 unboxed-gensym-14)))
             (unsafe-make-flrectangular unboxed-gensym-15 unboxed-gensym-16)))
       (t3 1.0+2.0i)
       (t4 1))
  (display (let* ((unboxed-gensym-1 (unsafe-fl+ unboxed-gensym-7 unboxed-gensym-7))
                  (unboxed-gensym-2 (unsafe-fl+ unboxed-gensym-8 unboxed-gensym-8)))
             (unsafe-make-flrectangular unboxed-gensym-1 unboxed-gensym-2)))
  (display t2)
  (display t3)
  (display t4))
(void)
