#lang racket

(require racket/unsafe/ops)

;; unboxing of let bindings does not currently work with multiple values
(let-values (((t1 t2)
              (values (let* ((unboxed-real-1 1.0)
                             (unboxed-imag-2 2.0)
                             (unboxed-real-3 2.0)
                             (unboxed-imag-4 4.0)
                             (unboxed-real-5 (unsafe-fl+ unboxed-real-1 unboxed-real-3))
                             (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2 unboxed-imag-4)))
                        (unsafe-make-flrectangular unboxed-real-5 unboxed-imag-6))
                      (let* ((unboxed-real-1 3.0)
                             (unboxed-imag-2 6.0)
                             (unboxed-real-3 4.0)
                             (unboxed-imag-4 8.0)
                             (unboxed-real-5 (unsafe-fl+ unboxed-real-1 unboxed-real-3))
                             (unboxed-imag-6 (unsafe-fl+ unboxed-imag-2 unboxed-imag-4)))
                        (unsafe-make-flrectangular unboxed-real-5 unboxed-imag-6)))))
  (let* ((unboxed-gensym-1 t1)
         (unboxed-real-2 (unsafe-flreal-part unboxed-gensym-1))
         (unboxed-imag-3 (unsafe-flimag-part unboxed-gensym-1))
         (unboxed-gensym-4 t2)
         (unboxed-real-5 (unsafe-flreal-part unboxed-gensym-4))
         (unboxed-imag-6 (unsafe-flimag-part unboxed-gensym-4))
         (unboxed-real-7 (unsafe-fl+ unboxed-real-2 unboxed-real-5))
         (unboxed-imag-8 (unsafe-fl+ unboxed-imag-3 unboxed-imag-6)))
    (unsafe-make-flrectangular unboxed-real-7 unboxed-imag-8)))
(void)
