#lang racket

(require racket/unsafe/ops)

(let*-values (((unboxed-gensym-1) 1.0)
              ((unboxed-gensym-2) 2.0)
              ((unboxed-gensym-3) 2.0+4.0i)
              ((unboxed-gensym-4) (unsafe-flreal-part unboxed-gensym-3))
              ((unboxed-gensym-5) (unsafe-flimag-part unboxed-gensym-3))
              ((unboxed-gensym-6) (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-4))
              ((unboxed-gensym-7) (unsafe-fl+ unboxed-gensym-2 unboxed-gensym-5)))
  (unsafe-make-flrectangular unboxed-gensym-6 unboxed-gensym-7))
(let*-values (((unboxed-gensym-1) 1.0)
              ((unboxed-gensym-2) 2.0)
              ((unboxed-gensym-3) 2.0+4.0i)
              ((unboxed-gensym-4) (unsafe-flreal-part unboxed-gensym-3))
              ((unboxed-gensym-5) (unsafe-flimag-part unboxed-gensym-3))
              ((unboxed-gensym-6) (unsafe-fl+ unboxed-gensym-1 unboxed-gensym-4))
              ((unboxed-gensym-7) (unsafe-fl+ unboxed-gensym-2 unboxed-gensym-5)))
  (unsafe-make-flrectangular unboxed-gensym-6 unboxed-gensym-7))
(void)
