(define (testfact fact)
  (list (= (fact 1) 1)
        (= (fact 2) 2)
        (= (fact 3) 6)
        (= (fact 4) 24)
        (= (fact 5) 120)))

(define (testfib fib)
  (list (= (fib 0) 0)
        (= (fib 2) 1)
        (= (fib 4) 3)
        (= (fib 6) 8)))

(append (testfact fact)
        (testfact fact2)
        (testfact impfact)
        (testfact (lambda (n) (cadr (fibfact n))))
        (testfib fib)
        (testfib (lambda (n) (car (fibfact n)))))
