#!/bin/sh
#| -*- scheme -*-
exec mzscheme -um "$0" "$@"
|#
#lang scheme/base

#|

This file contains "properties" of various files and directories in the PLT
tree.  Its format is briefly described below, but it is mainly intended to be
used as a script -- run it with `-h' to find out how to use it.  In addition,
you can add this to your git config file:

  [alias]
    prop = "!$(git rev-parse --show-toplevel)/collects/meta/props"

and use it as a git command: `git prop ...args....'.  Note that this will uses
the script from the work tree that you're now in, with any mzscheme executable
that happens to be on your $PATH.  This is fine, because the script will modify
itself based on where it was called from, unelated to the mzscheme version that
runs it.

As described above, the format of this file makes it easy to edit manually, but
it should be considered internal and mostly manipulated by running it as a
script.  Specifically, when the script updates the contents, it will write
things in a certain way regardless of how it was when the file was read in.

The data is contained in a specially marked comment.  Its format is a
sequence of path and properties for it:

  <path> <prop> <val> <prop> <val> ...

where <path> is a "/"-delimited string (relative to the plt tree root), <prop>
is one of a few known property symbols, and <val> is the assigned value.  The
value is should follow the predicate specification for the property, which is
defined as `known-props' before the properties data block; note that it is
assumed that the data in this file is all valid, so take care if you edit it
manually.  Properties of a directory apply to all sub-paths in it (but this
might not be the case for future properties).  A property can overwrite a
previous value that was already set, which means that if you really want to set
properties manually, you can just an appropriate line at the end but note that
the data is expected to have the correct format (it is checked when properties
are set by running this file as a script).

Requiring this file builds the data table and provides an interface for
properties, intended to be used by meta tools:

* (get-prop "some/path" 'known-prop [default] #:strict? [strict? #f])

  Returns the property value of a given path, given as a "/"-delimited string.
  The default is similar to `hash-ref' (can be a thunk, a value, or if not
  specified an exception is raised).  If `strict?' is true, then the property
  value of the path itself is returned, not inheriting values from parent
  paths.

* (set-prop! "some/path" 'known-prop value [warn? #t])

  Sets the value of a (known) proprty for a given path or paths (a string or a
  list of strings).  The path string/s is/are verified (relative paths
  without ".", "..", "//", or a "/" suffix).  The value is verified according
  to the known property predicate, and an exception is raised if it has the
  wrong type.  If `warn?' is true, an exception is raised if the property is
  already set to the value for the (any) path.  Note that this does not rewrite
  the file, use `write-props' for that.

* (del-prop! "some/path" 'known-prop [warn? #t])

  Similar to `set-prop!', except that it removes a property from the given
  path (or paths) .  The property is removed from the path itself, so this will
  have no effect if a parent path has a value.  If `warn?' is true, an
  exception is raised if the property is not directly set for path.

* (write-props)

  Writes all properties back into *this* file.  The properties are normalized:
  paths and properties are sorted, redundant entries are removed.  This
  minimizes the data (in case the file is edited manually), and minimizes
  changes to the file when it is modified.

|#

;; ----------------------------------------------------------------------------

(provide get-prop write-props)

;; ----------------------------------------------------------------------------

;; This could use `meta/tree/tree' in the future, it's pretty similar.
(define-struct tree (name [subs #:mutable] [props #:mutable]))

(define props-tree (make-tree #f '() '()))

;; used to throw an error message that fits uses as a program and when running
;; as a script.
(define running-as-script? #f)
(define (script-name)
  ((compose string->symbol path-element->string file-name-from-path)
   (find-system-path 'run-file)))
(define (error* who fmt . args)
  (if (or running-as-script? (not who))
    (apply raise-user-error (script-name) fmt args)
    (apply error who fmt args)))

(define (warn fmt . args)
  ;; maybe it's better to use log-warning and make it show when used as a
  ;; script?
  (fprintf (current-error-port) "warning: ~a\n" (apply format fmt args)))

(define (path->symbols path-string)
  (if (equal? "" path-string)
    '()
    (map string->symbol (regexp-split #rx"/" path-string))))

(define rx:bad-path
  #rx"^/|/$|\\\\|(?:^|/)(|\\.\\.?)(?:/|$)")
(define rx:bad-pathchar
  ;; instead of checking `path-string?', just heavily restrict the set of
  ;; allowed characters -- so not all paths can be used with this code, but
  ;; such paths are mostly ones that we won't want in the code anyway so do
  ;; this as a sanity check for adding such paths to the repository.  It may
  ;; need updating if more characters are allowed in the future.
  #rx"[^/.a-zA-Z0-9%_+-]")

(define (validate-path-string path-string who)
  (define (bad why)
    (error* who "invalid path argument, expecting a ~a, got: ~e"
            why path-string))
  (unless (string? path-string) (bad "a string"))
  (when (and ((string-length path-string) . > . 0)
             (regexp-match? rx:bad-path path-string))
    (bad "relative `/'-delimited string, no `/' suffix, `//', `.', or `..'"))
  (when (regexp-match? rx:bad-pathchar path-string)
    (error* who "invalid path argument, ~s is not allowed, got: ~e\n~a~a"
            (regexp-match rx:bad-pathchar path-string) path-string
            "(note: if paths with this character are needed, then this"
            " script needs to be exteded to allow them)")))

(define (get-prop path-string prop [default get-prop] #:strict? [strict? #f])
  (validate-path-string path-string 'get-prop)
  (let ([upchain
         ;; take the chain going up from the most specific node, so that
         ;; properties of a directory apply to subpaths
         (let loop ([path (path->symbols path-string)]
                    [upchain (list props-tree)])
           (let ([sub (and (pair? path)
                           (let ([fst (car path)])
                             (ormap (lambda (sub)
                                      (and (eq? (tree-name sub) fst) sub))
                                    (tree-subs (car upchain)))))])
             (cond [sub (loop (cdr path) (cons sub upchain))]
                   [(not strict?) upchain]
                   [(pair? path) '()]
                   [else (list (car upchain))])))])
    (cond [(ormap (lambda (tree) (assq prop (tree-props tree))) upchain)
           => cdr]
          [(eq? get-prop default)
           (error* 'get-prop "no `~s' property for \"~a\"" prop path-string)]
          [(procedure? default) (default)]
          [else default])))

(define (set-prop! path-string/s prop val [warn? #t])
  (define prop+
    (or (assq prop known-props)
        (error* 'set-prop! "unknown property: ~e" prop)))
  (define pred (cadr prop+))
  (unless (pred val)
    (error* 'set-prop! "bad value for `~s', expecting ~a, got: ~e"
            prop (caddr prop+) val))
  (for ([path (if (list? path-string/s) path-string/s (list path-string/s))])
    (validate-path-string path 'set-prop!)
    (if (and warn? (equal? val (get-prop path prop (gensym))))
      (warn "not setting `~s' for ~s to ~a" prop path
            "a value it already has (possibly via a containing directory)")
      ;; otherwise set it blindly (will be normalized away when written)
      (let ([tree (tree-find path #t)])
        (set-tree-props! tree (cons (cons prop val) (tree-props tree)))))))

(define (del-prop! path-string/s prop [warn? #t])
  (unless (assq prop known-props)
    (error* 'set-prop! "unknown property: ~e" prop))
  (for ([path (if (list? path-string/s) path-string/s (list path-string/s))])
    (validate-path-string path 'del-prop!)
    (let* ([tree  (tree-find path #f)]
           [props (if tree (tree-props tree) '())])
      (cond [(assq prop props)
             (set-tree-props! tree (filter (lambda (p)
                                             (not (eq? prop (car p))))
                                           props))]
            [warn? (warn "no `~s' property on ~s" prop path)]))))

(define (tree-find path-string create?)
  (let loop ([path (path->symbols path-string)] [tree props-tree])
    (if (null? path)
      tree
      (let* ([fst (car path)]
             [sub (or (ormap (lambda (sub) (and (eq? (tree-name sub) fst) sub))
                             (tree-subs tree))
                      (and create?
                           (let ([new (make-tree fst '() '())])
                             (set-tree-subs! tree (cons new (tree-subs tree)))
                             new)))])
        (and sub (loop (cdr path) sub))))))

;; ----------------------------------------------------------------------------
;; Reading and writing

(require (for-syntax scheme/base) scheme/file scheme/path scheme/list)

(define-syntax (this-file stx)
  (let ([src (syntax-source stx)])
    (if (path? src)
      (datum->syntax stx src stx)
      (raise-syntax-error 'props "must be required from a file"))))

(define rx:props-start #rx#"#\\|[ \r\n]+#:begin-props *\r?\n[ \r\n]+")
(define props-end-token '#:end-props)

(define (read-props* in)
  (define (malformed why [line? #t])
    (error* 'read-props "malformed props file: ~a~a" why
            (if line?
              (let-values ([(line col pos) (port-next-location in)])
                (format "at line #~a" line))
              "")))
  (port-count-lines! in)
  (unless (regexp-match? rx:props-start in)
    (malformed "beginning markup not found" #f))
  (let loop ([tree #f] [prop #f])
    (define x (read in))
    (cond [(eq? x props-end-token)
           ;; done, check that there's no leftovers
           (when prop (malformed "property with no value at the end"))
           (unless (regexp-match? #rx#"[ \r\n]*\\|#[ \r\n]+$" in)
             (malformed "unexpected text found at the end of the file"))]
          [prop
           ;; register a given property value
           (set-tree-props! tree (cons (cons (car prop) x) (tree-props tree)))
           (loop tree #f)]
          [(string? x)
           ;; new path, find the node or create if none
           (loop (tree-find x #t) #f)]
          [(assq x known-props)
           ;; prop
           => (lambda (prop)
                (loop (or tree (malformed "initial property has no path"))
                      prop))]
          [else (malformed (format "bad datum `~e'" x))])))

(define (read-props) (call-with-input-file* this-file read-props*))

(define (*write-props old new)
  (let ([m (regexp-match rx:props-start old 0 #f new)])
    (unless m
      (error* 'write-props
              "beginning markup not found while writing new file"))
    (write-bytes (car m) new)
    (let loop ([tree props-tree] [path ""])
      (when (pair? (tree-props tree))
        (fprintf new "~s" path)
        (for ([p (in-list (tree-props tree))])
          (fprintf new " ~s ~s" (car p) (cdr p)))
        (newline new))
      (for ([sub (in-list (tree-subs tree))])
        (loop sub (let ([s (symbol->string (tree-name sub))])
                    (if (equal? "" path) s (string-append path "/" s))))))
    (fprintf new "\n~s |#\n" props-end-token)))

(define (write-props)
  (define known-prop-names (map car known-props))
  ;; normalize the tree, to minimize changes to the file and remove redundant
  ;; entries that could be added manually
  (let loop ([tree props-tree] [up-props '()])
    (define normalized-props
      (for*/list ([p (in-list known-prop-names)]
                  [p (in-value (let ([cur (assq p (tree-props tree))])
                                 (and cur (not (member cur up-props)) cur)))]
                  #:when p)
        p))
    (set-tree-props! tree normalized-props)
    (when (pair? (tree-subs tree))
      (let ([up-props (append normalized-props up-props)]
            [subs (sort (tree-subs tree) string<?
                        #:key (lambda (t) (symbol->string (tree-name t)))
                        #:cache-keys? #t)])
        (set-tree-subs! tree (for*/list ([sub (in-list subs)]
                                         [sub (in-value (loop sub up-props))]
                                         #:when sub)
                               sub))))
    (and (or (pair? (tree-subs tree)) (pair? (tree-props tree))) tree))
  (let (;; temp file in the same directory => fail early if cannot write to it
        ;; and make a rename possible
        [temp (make-temporary-file (format "~a~~a" this-file))])
    (dynamic-wind
      void
      (lambda ()
        (call-with-output-file* temp #:exists 'truncate
          (lambda (new)
            (call-with-input-file* this-file
              (lambda (old) (*write-props old new)))))
        (delete-file this-file)
        (rename-file-or-directory temp this-file))
      (lambda () (when (file-exists? temp) (delete-file temp))))))

;; ----------------------------------------------------------------------------
;; Main

(provide main)
(define (main . args)
  (define (usage what)
    (error* #f "~a, use \"help\" for more info" what))
  (define (str->prop str)
    (let ([s (string->symbol str)])
      (car (or (assq s known-props) (error* #f "unknown property `~s'" s)))))
  (define (help . _)
    (define (para . lines) (for ([line lines]) (printf "  ~a\n" line)))
    (printf "Usage: ~a subcommand args ...\n" (script-name))
    (para
     "This is a utility for manipulating properties in the PLT repository."
     "Each of the following subcommands expects a property name from a set of"
     "known properties.  The given paths are normalized to be relative to the"
     "plt root for the tree holding this script *if* it is in such a tree"
     "(determined by inspecting a few known directories), otherwise an error"
     "is raised.  Note that this script holds the data that it changes, so you"
     "need to commit it after changes are made.  Also note that it does not"
     "depend on the plt installation that runs it -- you just need to use the"
     "script from the work directory that you want to deal with; if you add"
     "  prop = \"!$(git rev-parse --show-toplevel)/collects/meta/props\""
     "to your global git config file (usually ~/.gitconfig), then you'll be"
     "able to run it as `git prop'."
     ""
     "Path arguments can also be given via stdin (each on a line) if the"
     "command-line path argument is a single `-'.  In this mode the paths are"
     "not normalized, and it is intended for infrastructure scripts only.")
    (printf "\nAvailable subcommands:\n")
    (for ([v (in-list (verbs))]) (printf "  ~a\n" (cadr v)))
    (printf "\nKnown properties:\n")
    (for ([p (in-list known-props)])
      (printf "  ~s: ~a\n" (car p) (caddr p))))
  (define (verbs)
    `([("help" "h" "-h" "--help") "help: show this help" ,help]
      [("get") "get <prop> <path/s>" ,get]
      [("set") "set <prop> <val> <path/s>" ,set]
      [("del") "del <prop> <path/s>" ,del]))
  (define (find-root)
    (let loop ([p this-file] [n 3]) ; look only a few level up
      (let-values ([(base _1 _2) (split-path p)])
        (and base
             (or (and (andmap (lambda (d) (directory-exists? (build-path p d)))
                              '("collects" "doc" "man" "src"))
                      p)
                 (if (> n 0)
                   (loop base (sub1 n))
                   (error* #f "could not find the plt root from ~a"
                           (path-only this-file))))))))
  (define (paths->list path paths)
    (if (and (equal? "-" path) (null? paths))
      (for/list ([p (in-lines (current-input-port))]) p)
      (let ([root (normalize-path (find-root))])
        (define (norm p)
          (let ([n (find-relative-path root (normalize-path p))])
            (if (equal? n root)
              ""
              (let ([n (path->string n)])
                (if (regexp-match #rx"^\\.\\.(?:/|$)" n)
                  (error* #f "path is not in the plt tree: ~s" p)
                  n)))))
        (if (null? paths) (norm path) (map norm (cons path paths))))))
  (define (get prop path . paths)
    (let ([prop (str->prop prop)]
          [seq  (paths->list path paths)])
      (if (not (list? seq))
        ;; single path: don't show it, and error if none
        (printf "~s\n" (get-prop seq prop))
        ;; multiple paths: show them, ignore errors
        (for ([p (in-list seq)])
          (let ([v (get-prop p prop (void))])
            (unless (void? v) (printf "~a: ~s\n" p v)))))))
  (define (set prop val path . paths)
    (let* ([prop (str->prop prop)]
           [in (open-input-string (string-append "(" val ")"))]
           [val (with-handlers
                    ([exn? (lambda (_)
                             (error* #f "unreadable value \"~a\", ~a" val
                                     "must be a single scheme sexpr"))])
                  (let ([v (read in)])
                    (if (and (pair? v) (null? (cdr v)))
                      (car v)
                      (error "poof"))))])
      (set-prop! (paths->list path paths) prop val)
      (write-props)))
  (define (del prop path . paths)
    (del-prop! (paths->list path paths) (str->prop prop))
    (write-props))
  (set! running-as-script? #t)
  (let* ([verb (if (pair? args) (car args) (usage "missing subcommand"))]
         [args (cdr args)]
         [proc (or (for/or ([v (in-list (verbs))] #:when (member verb (car v)))
                     (caddr v))
                   (usage (format "unknown subcommand ~s" verb)))])
    (if (procedure-arity-includes? proc (length args))
      (apply proc args)
      (usage (format "bad number of arguments for ~s" verb)))))

;; ----------------------------------------------------------------------------

(define known-props
  `([responsible
     ,(lambda (x)
        (and (list? x) (andmap symbol? x)
             (= (length x) (length (remove-duplicates x)))))
     "a list of unique symbols"]
    [drdr
     ,(lambda (x)
        (or (string? x) (integer? x)
            (and (list? x) (= 2 (length x))
                 (string? (car x)) (integer? (cadr x)))))
     "command-line string, delay in seconds, or a list with both"]))

;; read the arguments here, so just requiring this file verifies the data
(read-props)

;; ----------------------------------------------------------------------------

#| #:begin-props

"collects/2htdp" responsible (matthias)
"collects/2htdp/image.ss" responsible (robby) drdr "mred-text -t $path"
"collects/2htdp/private/check-aux.ss" drdr "mred-text -t $path"
"collects/2htdp/private/checked-cell.ss" drdr "mred-text -t $path"
"collects/2htdp/private/image-more.ss" responsible (robby) drdr "mred-text -t $path"
"collects/2htdp/private/img-err.ss" responsible (robby) drdr "mred $path"
"collects/2htdp/private/last.ss" drdr "mred-text -t $path"
"collects/2htdp/private/launch-many-worlds.ss" drdr "mred-text -t $path"
"collects/2htdp/private/timer.ss" drdr "mred-text -t $path"
"collects/2htdp/private/universe-image.ss" drdr "mred $path"
"collects/2htdp/private/universe.ss" drdr "mred-text -t $path"
"collects/2htdp/private/world.ss" drdr "mred-text -t $path"
"collects/2htdp/tests/bad-draw.ss" drdr "mred $path"
"collects/2htdp/tests/full-scene-visible.ss" drdr "mred $path"
"collects/2htdp/tests/image-equality-performance.ss" responsible (robby) drdr "mred-text $path"
"collects/2htdp/tests/mouse-evt.ss" drdr ""
"collects/2htdp/tests/mp.ss" drdr ""
"collects/2htdp/tests/perform-robby.ss" drdr "mred $path"
"collects/2htdp/tests/perform-whack.ss" drdr ""
"collects/2htdp/tests/profile-robby.ss" drdr ""
"collects/2htdp/tests/release.ss" drdr "mred -t $path"
"collects/2htdp/tests/stop.ss" drdr "mred $path"
"collects/2htdp/tests/test-image.ss" responsible (robby) drdr "mred-text -qt $path"
"collects/2htdp/tests/ufo-rename.ss" drdr "mred $path"
"collects/2htdp/tests/world0-stops.ss" drdr "mred-text -t $path"
"collects/2htdp/uchat/chatter.ss" drdr "mzc -k $path"
"collects/2htdp/uchat/server.ss" drdr "mzc -k $path"
"collects/2htdp/universe.ss" drdr "mred-text -t $path"
"collects/2htdp/utest/balls.ss" drdr "mzc $path"
"collects/2htdp/utest/sam.ss" drdr "mzc $path"
"collects/2htdp/utest/shared.ss" drdr "mred-text -t $path"
"collects/afm" responsible (mflatt)
"collects/afm/ttf-to-glyphlist.ss" drdr "mzc $path"
"collects/algol60" responsible (mflatt)
"collects/algol60/bd-tool.ss" drdr "mred-text -t $path"
"collects/algol60/tool.ss" drdr "mred-text -t $path"
"collects/browser" responsible (robby)
"collects/browser/browser-unit.ss" drdr "mred-text -t $path"
"collects/browser/browser.ss" drdr "mred-text -t $path"
"collects/browser/bullet-snip.ss" drdr "mred-text -t $path"
"collects/browser/external.ss" drdr "mred-text -t $path"
"collects/browser/htmltext.ss" drdr "mred-text -t $path"
"collects/browser/main.ss" drdr "mred-text -t $path"
"collects/browser/private/bullet.ss" drdr "mred-text -t $path"
"collects/browser/private/html.ss" drdr "mred-text -t $path"
"collects/browser/private/hyper.ss" drdr "mred-text -t $path"
"collects/browser/private/option-snip.ss" drdr "mred-text -t $path"
"collects/browser/tool.ss" drdr "mred-text -t $path"
"collects/combinator-parser" responsible (kathyg)
"collects/compiler" responsible (mflatt)
"collects/defaults" responsible (robby)
"collects/deinprogramm" responsible (sperber)
"collects/deinprogramm/contract/contract-test-display.ss" drdr "mred-text -t $path"
"collects/deinprogramm/convert-explicit.scm" drdr ""
"collects/deinprogramm/define-record-procedures.scm" drdr ""
"collects/deinprogramm/deinprogramm-langs.ss" drdr "mred-text -t $path"
"collects/deinprogramm/image.ss" drdr "mred-text -t $path"
"collects/deinprogramm/line3d.scm" drdr ""
"collects/deinprogramm/line3d.ss" drdr "mred-text -t $path"
"collects/deinprogramm/quickcheck/quickcheck.scm" drdr ""
"collects/deinprogramm/quickcheck/random.scm" drdr ""
"collects/deinprogramm/run-dmda-code.ss" drdr "mzc $path"
"collects/deinprogramm/turtle.ss" drdr "mred-text -t $path"
"collects/deinprogramm/world.ss" drdr "mred-text -t $path"
"collects/drscheme" responsible (robby)
"collects/drscheme/arrow.ss" drdr "mred-text -t $path"
"collects/drscheme/drscheme.ss" drdr "mzc $path"
"collects/drscheme/main.ss" drdr "mzc $path"
"collects/drscheme/private/app.ss" drdr "mred-text -t $path"
"collects/drscheme/private/auto-language.ss" drdr "mred-text -t $path"
"collects/drscheme/private/bindings-browser.ss" drdr "mred-text -t $path"
"collects/drscheme/private/bitmap-message.ss" drdr "mred-text -t $path"
"collects/drscheme/private/debug.ss" drdr "mred-text -t $path"
"collects/drscheme/private/drscheme-normal.ss" drdr "mzc $path"
"collects/drscheme/private/eb.ss" drdr "mred-text"
"collects/drscheme/private/embedded-snip-utils.ss" drdr "mred-text -t $path"
"collects/drscheme/private/eval.ss" drdr "mred-text -t $path"
"collects/drscheme/private/font.ss" drdr "mred-text -t $path"
"collects/drscheme/private/frame.ss" drdr "mred-text -t $path"
"collects/drscheme/private/help-desk.ss" drdr "mred-text -t $path"
"collects/drscheme/private/honu-logo.ss" drdr "mred-text -t $path"
"collects/drscheme/private/init.ss" drdr "mred-text -t $path"
"collects/drscheme/private/insert-large-letters.ss" drdr "mred-text -t $path"
"collects/drscheme/private/label-frame-mred.ss" drdr "mred-text -t $path"
"collects/drscheme/private/language-configuration.ss" drdr "mred-text -t $path"
"collects/drscheme/private/language-object-contract.ss" drdr "mred-text -t $path"
"collects/drscheme/private/language.ss" drdr "mred-text -t $path"
"collects/drscheme/private/launcher-mred-bootstrap.ss" drdr "mzc $path"
"collects/drscheme/private/launcher-mz-bootstrap.ss" drdr "mzc $path"
"collects/drscheme/private/link.ss" drdr "mred-text -t $path"
"collects/drscheme/private/main.ss" drdr "mred-text -t $path"
"collects/drscheme/private/modes.ss" drdr "mred-text -t $path"
"collects/drscheme/private/module-browser.ss" drdr "mred-text -t $path"
"collects/drscheme/private/module-language-tools.ss" drdr "mred-text"
"collects/drscheme/private/module-language.ss" drdr "mred-text -t $path"
"collects/drscheme/private/multi-file-search.ss" drdr "mred-text -t $path"
"collects/drscheme/private/number-snip.ss" drdr "mred-text -t $path"
"collects/drscheme/private/palaka.ss" drdr "mred-text -t $path"
"collects/drscheme/private/prefs-contract.ss" drdr "mred-text -t $path"
"collects/drscheme/private/profile-drs.ss" drdr "mred-text -t $path"
"collects/drscheme/private/rep.ss" drdr "mred-text -t $path"
"collects/drscheme/private/stick-figures.ss" drdr "mzc $path"
"collects/drscheme/private/syncheck-debug.ss" drdr "mred-text -t $path"
"collects/drscheme/private/text.ss" drdr "mred-text -t $path"
"collects/drscheme/private/tools.ss" drdr "mred-text -t $path"
"collects/drscheme/private/tracing.ss" drdr "mred-text -t $path"
"collects/drscheme/private/unit.ss" drdr "mred-text -t $path"
"collects/drscheme/sprof.ss" drdr "mred-text -t $path"
"collects/drscheme/syncheck.ss" drdr "mred-text -t $path"
"collects/drscheme/tool-lib.ss" drdr "mzc $path"
"collects/dynext" responsible (mflatt)
"collects/dynext/private/macinc.ss" drdr "mzscheme -f $path"
"collects/dynext/private/stdio.ss" drdr ""
"collects/embedded-gui/embedded-gui.ss" drdr "mred-text -t $path"
"collects/embedded-gui/main.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/aligned-pasteboard.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/alignment-helpers.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/button-snip.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/cue-text.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/dllist.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/embedded-message.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/fixed-width-label-snip.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/grey-editor.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/lines.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/locked-pasteboard.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/on-show-editor.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/on-show-pasteboard.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/program-editor.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/really-resized-pasteboard.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/single-line-text.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/snip-lib.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/snip-wrapper.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/stretchable-editor-snip.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/suppress-modify-editor.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/tabbable-text.ss" drdr "mred-text -t $path"
"collects/embedded-gui/private/tests/alignment-test.ss" drdr ""
"collects/embedded-gui/private/tests/info.ss" drdr ""
"collects/embedded-gui/private/tests/not-stetching.ss" drdr ""
"collects/embedded-gui/private/tests/only-one-child.ss" drdr ""
"collects/embedded-gui/private/tests/peer-stretchables.ss" drdr ""
"collects/embedded-gui/private/tests/stretching-in-alignment.ss" drdr ""
"collects/embedded-gui/private/tests/target-not-object.ss" drdr ""
"collects/embedded-gui/private/tests/test-alignment.ss" drdr ""
"collects/embedded-gui/private/tests/test-case-box.ss" drdr ""
"collects/embedded-gui/private/tests/test-macro.ss" drdr ""
"collects/embedded-gui/private/tests/test-show-feature-for-test-case.ss" drdr ""
"collects/embedded-gui/private/tests/test-show-feature.ss" drdr ""
"collects/embedded-gui/private/tests/unaligned-childless-redux.ss" drdr ""
"collects/embedded-gui/private/verthoriz-alignment.ss" drdr "mred-text -t $path"
"collects/errortrace" responsible (mflatt)
"collects/ffi" responsible (eli)
"collects/ffi/esd.ss" drdr "mzc $path"
"collects/ffi/examples/c-printf.ss" drdr "mzc -k $path"
"collects/ffi/examples/esd.ss" drdr "mzc $path"
"collects/ffi/examples/magick.ss" drdr "mzc $path"
"collects/ffi/examples/sndfile.ss" drdr "mzc $path"
"collects/ffi/examples/tcl.ss" drdr "mzc $path"
"collects/ffi/examples/xmmsctrl.ss" drdr "mzc $path"
"collects/ffi/examples/xosd.ss" drdr "mzc $path"
"collects/ffi/magick.ss" drdr "mzc $path"
"collects/ffi/objc.ss" drdr "mzc $path"
"collects/ffi/private/objc-doc-unsafe.ss" drdr "mzc $path"
"collects/ffi/sndfile.ss" drdr "mzc $path"
"collects/ffi/tcl.ss" drdr "mzc $path"
"collects/ffi/xmmsctrl.ss" drdr "mzc $path"
"collects/ffi/xosd.ss" drdr "mzc $path"
"collects/framework" responsible (robby)
"collects/framework/collapsed-snipclass.ss" drdr "mred-text -t $path"
"collects/framework/comment-snip.ss" drdr "mred-text -t $path"
"collects/framework/decorated-editor-snip.ss" drdr "mred-text -t $path"
"collects/framework/framework-unit.ss" drdr "mred-text -t $path"
"collects/framework/framework.ss" drdr "mred-text -t $path"
"collects/framework/gui-utils.ss" drdr "mred-text -t $path"
"collects/framework/keybinding-lang.ss" drdr "mred-text -t $path"
"collects/framework/main.ss" drdr "mred-text -t $path"
"collects/framework/preferences.ss" drdr "mred-text -t $path"
"collects/framework/private/autosave.ss" drdr "mred-text -t $path"
"collects/framework/private/canvas.ss" drdr "mred-text -t $path"
"collects/framework/private/collapsed-snipclass-helpers.ss" drdr "mred-text -t $path"
"collects/framework/private/color-prefs.ss" drdr "mred-text -t $path"
"collects/framework/private/color.ss" drdr "mred-text -t $path"
"collects/framework/private/comment-box.ss" drdr "mred-text -t $path"
"collects/framework/private/decorated-editor-snip.ss" drdr "mred-text -t $path"
"collects/framework/private/editor.ss" drdr "mred-text -t $path"
"collects/framework/private/exit.ss" drdr "mred-text -t $path"
"collects/framework/private/finder.ss" drdr "mred-text -t $path"
"collects/framework/private/frame.ss" drdr "mred-text -t $path"
"collects/framework/private/group.ss" drdr "mred-text -t $path"
"collects/framework/private/handler.ss" drdr "mred-text -t $path"
"collects/framework/private/keymap.ss" drdr "mred-text -t $path"
"collects/framework/private/main.ss" drdr "mred-text -t $path"
"collects/framework/private/menu.ss" drdr "mred-text -t $path"
"collects/framework/private/number-snip.ss" drdr "mred-text -t $path"
"collects/framework/private/preferences.ss" drdr "mred-text -t $path"
"collects/framework/private/scheme.ss" drdr "mred-text -t $path"
"collects/framework/private/search.ss" drdr "mred-text -t $path"
"collects/framework/private/standard-menus.ss" drdr ""
"collects/framework/private/text.ss" drdr "mred-text -t $path"
"collects/framework/splash.ss" drdr "mred-text -t $path"
"collects/framework/test.ss" drdr "mred-text -t $path"
"collects/frtime" responsible (jay gcooper)
"collects/frtime/animation/graphics.ss" drdr "mred-text -t $path"
"collects/frtime/animation.ss" drdr "mzc $path"
"collects/frtime/demos/analog-clock.ss" drdr "mzc $path"
"collects/frtime/demos/ball-on-string.ss" drdr "mzc $path"
"collects/frtime/demos/delay-mouse.ss" drdr "mzc $path"
"collects/frtime/demos/growing-points.ss" drdr "mzc $path"
"collects/frtime/demos/mirror-lens.ss" drdr "mzc $path"
"collects/frtime/demos/mouse.ss" drdr "mzc $path"
"collects/frtime/demos/needles.ss" drdr "mzc $path"
"collects/frtime/demos/orbit-mouse.ss" drdr "mzc $path"
"collects/frtime/demos/piston.ss" drdr "mzc $path"
"collects/frtime/demos/pong.ss" drdr "mzc $path"
"collects/frtime/demos/push-pull-ball.ss" drdr "mzc $path"
"collects/frtime/demos/rotation.ss" drdr "mzc $path"
"collects/frtime/demos/tetris.ss" drdr "mzc $path"
"collects/frtime/demos/tile-game.ss" drdr "mzc $path"
"collects/frtime/demos/ufo.ss" drdr "mzc $path"
"collects/frtime/frlibs/date.ss" drdr "mred-text -t $path"
"collects/frtime/frp-snip.ss" drdr "mred-text -t $path"
"collects/frtime/frtime-big.ss" drdr "mred-text -t $path"
"collects/frtime/frtime.ss" drdr "mred-text -t $path"
"collects/frtime/gui/aux-mixin-macros.ss" drdr "mred-text -t $path"
"collects/frtime/gui/demo/bindec.ss" drdr "mzc $path"
"collects/frtime/gui/demo/instr.ss" drdr "mzc $path"
"collects/frtime/gui/demo/timer.ss" drdr "mzc $path"
"collects/frtime/gui/fred.ss" drdr "mred-text -t $path"
"collects/frtime/gui/mixin-macros.ss" drdr "mred-text -t $path"
"collects/frtime/gui/simple.ss" drdr "mred-text -t $path"
"collects/frtime/gui.ss" drdr "mzc $path"
"collects/frtime/main.ss" drdr "mred-text -t $path"
"collects/frtime/opt/frtime-opt-lang.ss" drdr "mred-text -t $path"
"collects/frtime/reactive.ss" drdr "mred-text -t $path"
"collects/frtime/tool/frtime-tool.ss" drdr "mred-text -t $path"
"collects/games" responsible (mflatt robby)
"collects/games/aces/aces.scm" drdr "mred-text -t $path"
"collects/games/blackjack/blackjack.ss" drdr "mred-text -t $path"
"collects/games/cards/base.ss" drdr "mred-text -t $path"
"collects/games/cards/card-class.ss" drdr "mred-text -t $path"
"collects/games/cards/cards.ss" drdr "mred-text -t $path"
"collects/games/cards/classes.ss" drdr "mred-text -t $path"
"collects/games/cards/constants.ss" drdr "mred-text -t $path"
"collects/games/cards/main.ss" drdr "mred-text -t $path"
"collects/games/cards/make-cards.ss" drdr "mred-text -t $path"
"collects/games/cards/snipclass.ss" drdr "mred-text -t $path"
"collects/games/cards.ss" drdr "mred-text -t $path"
"collects/games/chat-noir/chat-noir-literate.ss" drdr "mzc -k $path"
"collects/games/chat-noir/chat-noir-unit.ss" drdr "mred-text -t $path"
"collects/games/checkers/checkers.ss" drdr "mred-text -t $path"
"collects/games/checkers/honu-bitmaps.ss" drdr "mred-text -t $path"
"collects/games/crazy8s/crazy8s.ss" drdr "mred-text -t $path"
"collects/games/doors/doors.ss" drdr "mred-text -t $path"
"collects/games/doors/utils.ss" drdr "mred-text -t $path"
"collects/games/gcalc/gcalc.ss" drdr "mred-text -t $path"
"collects/games/ginrummy/ginrummy.ss" drdr "mred-text -t $path"
"collects/games/gl-board-game/gl-board.ss" drdr "mred-text -t $path"
"collects/games/gl-board-game/main.ss" drdr "mred-text -t $path"
"collects/games/gl-board-game.ss" drdr "mred-text -t $path"
"collects/games/gobblet/check.ss" drdr "mzc -k $path"
"collects/games/gobblet/gobblet.ss" drdr "mred-text -t $path"
"collects/games/gobblet/gui.ss" drdr "mred-text -t $path"
"collects/games/gobblet/robot.ss" drdr "mzc -k $path"
"collects/games/gobblet/test-explore.ss" drdr "mzc -k $path"
"collects/games/gobblet/test-model.ss" drdr "mzc -k $path"
"collects/games/gofish/gofish.ss" drdr "mred-text -t $path"
"collects/games/jewel/jewel.scm" drdr "mred-text -t $path"
"collects/games/jewel/text.scm" drdr "mred-text -t $path"
"collects/games/lights-out/board.ss" drdr "mred-text -t $path"
"collects/games/lights-out/lights-out.ss" drdr "mred-text -t $path"
"collects/games/main.ss" drdr "mzc $path"
"collects/games/memory/memory.ss" drdr "mred-text -t $path"
"collects/games/mines/gen-tiles.ss" drdr "mred-text -t $path"
"collects/games/mines/mines.ss" drdr "mred-text -t $path"
"collects/games/paint-by-numbers/gui.ss" drdr "mred-text -t $path"
"collects/games/paint-by-numbers/main.ss" drdr ""
"collects/games/paint-by-numbers/paint-by-numbers.ss" drdr "mred-text -t $path"
"collects/games/paint-by-numbers/raw-problems/build-final.ss" drdr "mzscheme -f $path"
"collects/games/paint-by-numbers/raw-problems/build-hattori.ss" drdr "mred -t $path"
"collects/games/paint-by-numbers/raw-problems/build-rows-cols.ss" drdr "mzc -k $path"
"collects/games/paint-by-numbers/raw-problems/build-solution-sets.ss" drdr "mred -t $path"
"collects/games/paint-by-numbers/raw-problems/raw-hattori.ss" drdr "mzscheme -f $path"
"collects/games/paint-by-numbers/raw-problems/raw-kajitani.ss" drdr "mred -t $path"
"collects/games/paint-by-numbers/raw-problems/raw-misc.ss" drdr "mzscheme -f $path"
"collects/games/paint-by-numbers/raw-problems/raw-problems.ss" drdr "mzscheme -f $path"
"collects/games/paint-by-numbers/raw-problems/size-calculation.ss" drdr "mzc $path"
"collects/games/parcheesi/admin-gui.ss" drdr "mred-text -t $path"
"collects/games/parcheesi/die.ss" drdr "mred-text -t $path"
"collects/games/parcheesi/gui.ss" drdr "mred-text -t $path"
"collects/games/parcheesi/make-bitmap.ss" drdr "mzc $path"
"collects/games/parcheesi/parcheesi.ss" drdr "mred-text -t $path"
"collects/games/parcheesi/play-game.ss" drdr "mred-text -t $path"
"collects/games/parcheesi/rules.ss" drdr "mred-text -t $path"
"collects/games/pousse/pousse.ss" drdr "mred-text -t $path"
"collects/games/same/same.ss" drdr "mred-text -t $path"
"collects/games/show-help.ss" drdr "mred-text -t $path"
"collects/games/slidey/slidey.ss" drdr "mred-text -t $path"
"collects/games/spider/spider.ss" drdr "mred-text -t $path"
"collects/graphics/graphics-posn-less-unit.ss" drdr "mred-text -t $path"
"collects/graphics/graphics-unit.ss" drdr "mred-text -t $path"
"collects/graphics/graphics.ss" drdr "mred-text -t $path"
"collects/graphics/main.ss" drdr "mred-text -t $path"
"collects/graphics/turtle-examples.ss" drdr "mred-text -t $path"
"collects/graphics/turtle-test.ss" drdr "mzc -k $path"
"collects/graphics/turtles.ss" drdr "mred-text -t $path"
"collects/graphics/value-turtles-examples.ss" drdr "mred-text -t $path"
"collects/graphics/value-turtles-test.ss" drdr "mzc $path"
"collects/graphics/value-turtles.ss" drdr "mred-text -t $path"
"collects/gui-debugger" responsible (gmarceau)
"collects/gui-debugger/debug-tool.ss" drdr "mred-text -t $path"
"collects/gui-debugger/load-sandbox.ss" drdr "mred-text -t $path"
"collects/guibuilder/base.ss" drdr "mred-text -t $path"
"collects/guibuilder/canvas.ss" drdr "mred-text -t $path"
"collects/guibuilder/feature.ss" drdr "mred-text -t $path"
"collects/guibuilder/guibuilder.ss" drdr "mzc $path"
"collects/guibuilder/multiple-choice.ss" drdr "mred-text -t $path"
"collects/guibuilder/panel.ss" drdr "mred-text -t $path"
"collects/guibuilder/readable.ss" drdr "mred-text -t $path"
"collects/guibuilder/simple-control.ss" drdr "mred-text -t $path"
"collects/guibuilder/slider-guage.ss" drdr "mred-text -t $path"
"collects/guibuilder/text-field.ss" drdr "mred-text -t $path"
"collects/guibuilder/tool.ss" drdr "mred-text -t $path"
"collects/guibuilder/toolbar.ss" drdr "mred-text -t $path"
"collects/guibuilder/top-level.ss" drdr "mred-text -t $path"
"collects/guibuilder/utils.ss" drdr "mred-text -t $path"
"collects/handin-client" responsible (eli)
"collects/handin-client/client-gui.ss" drdr "mred-text -t $path"
"collects/handin-client/handin-multi.ss" drdr "mred-text -t $path"
"collects/handin-client/updater.ss" drdr "mzc $path"
"collects/handin-server" responsible (eli)
"collects/handin-server/checker.ss" drdr "mzc $path"
"collects/handin-server/main.ss" drdr "mzc $path"
"collects/handin-server/overridden-collects/fake-teachpack/htdp/guess.ss" drdr "mred-text -t $path"
"collects/handin-server/overridden-collects/fake-teachpack/htdp/master.ss" drdr "mred-text -t $path"
"collects/handin-server/utils.ss" drdr "mzc $path"
"collects/handin-server/web-status-server.ss" drdr "mzc $path"
"collects/help" responsible (robby)
"collects/help/bug-report.ss" drdr "mred-text -t $path"
"collects/hierlist/hierlist.ss" drdr "mred-text -t $path"
"collects/honu" responsible (mflatt rafkind)
"collects/htdp" responsible (matthias)
"collects/htdp/arrow-gui.ss" drdr "mred-text -t $path"
"collects/htdp/arrow.ss" drdr "mred-text -t $path"
"collects/htdp/big-draw.ss" drdr "mred-text -t $path"
"collects/htdp/convert.ss" drdr "mred-text -t $path"
"collects/htdp/draw.ss" drdr "mred-text -t $path"
"collects/htdp/elevator.ss" drdr "mred-text -t $path"
"collects/htdp/graphing.ss" drdr "mzc $path"
"collects/htdp/guess-gui.ss" drdr "mred-text -t $path"
"collects/htdp/guess.ss" drdr "mred-text -t $path"
"collects/htdp/gui.ss" drdr "mred-text -t $path"
"collects/htdp/hangman-play.ss" drdr "mred-text -t $path"
"collects/htdp/hangman-world-play.ss" drdr "mred-text -t $path"
"collects/htdp/hangman-world.ss" drdr "mred-text -t $path"
"collects/htdp/hangman.ss" drdr "mred-text -t $path"
"collects/htdp/image.ss" drdr "mred-text -t $path"
"collects/htdp/lkup-gui.ss" drdr "mred-text -t $path"
"collects/htdp/master-play.ss" drdr "mred-text -t $path"
"collects/htdp/master.ss" drdr "mred-text -t $path"
"collects/htdp/matrix-invisible.ss" drdr "mred-text -t $path"
"collects/htdp/matrix-unit.ss" drdr "mred-text -t $path"
"collects/htdp/matrix.ss" drdr "mred-text -t $path"
"collects/htdp/show-queen.ss" drdr "mred-text -t $path"
"collects/htdp/tests/arrow-gui.ss" drdr "mred-text -t $path"
"collects/htdp/tests/arrow.ss" drdr "mred-text -t $path"
"collects/htdp/tests/convert.ss" drdr "mzc $path"
"collects/htdp/tests/dir.ss" drdr ""
"collects/htdp/tests/draw.ss" drdr "mred-text -t $path"
"collects/htdp/tests/elevator.ss" drdr "mzc $path"
"collects/htdp/tests/graphing.ss" drdr "mzc $path"
"collects/htdp/tests/guess-gui.ss" drdr ""
"collects/htdp/tests/guess1.ss" drdr "mred-text -t $path"
"collects/htdp/tests/guess2.ss" drdr "mred-text -t $path"
"collects/htdp/tests/guess3.ss" drdr "mred-text -t $path"
"collects/htdp/tests/gui.ss" drdr "mzc $path"
"collects/htdp/tests/hangman-error.ss" drdr "mzc $path"
"collects/htdp/tests/hangman1.ss" drdr "mred -t $path"
"collects/htdp/tests/lkup-gui.ss" drdr "mred-text -t $path"
"collects/htdp/tests/master.ss" drdr "mred-text -t $path"
"collects/htdp/tests/matrix-client.ss" drdr ""
"collects/htdp/tests/matrix-example.ss" drdr ""
"collects/htdp/tests/matrix-test.ss" drdr "mred-text -t $path"
"collects/htdp/tests/world-add-line.ss" drdr "mred-text -t $path"
"collects/htdp/tests/world-mouse.ss" drdr "mzc $path"
"collects/htdp/tests/world.ss" drdr "mred -t $path"
"collects/htdp/world.ss" drdr "mred-text -t $path"
"collects/html" responsible (jay)
"collects/lang/htdp-langs.ss" drdr "mred-text -t $path"
"collects/lang/plt-pretty-big.ss" drdr "mred-text -t $path"
"collects/lang/private/imageeq.ss" drdr "mred-text -t $path"
"collects/lazy" responsible (eli)
"collects/macro-debugger" responsible (ryanc)
"collects/macro-debugger/model/trace-raw.ss" drdr "mred-text -t $path"
"collects/macro-debugger/stepper.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/controller.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/display.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/embed.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/frame.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/hrule-snip.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/image.ss" drdr "mred-text -qt $path"
"collects/macro-debugger/syntax-browser/keymap.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/prefs.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/pretty-printer.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/properties.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/snip-decorated.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/snip.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/text.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser/widget.ss" drdr "mred-text -t $path"
"collects/macro-debugger/syntax-browser.ss" drdr "mred-text -t $path"
"collects/macro-debugger/tool.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/debug.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/extensions.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/frame.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/hiding-panel.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/prefs.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/step-display.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/stepper.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/term-record.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/view.ss" drdr "mred-text -t $path"
"collects/macro-debugger/view/warning.ss" drdr "mred-text -t $path"
"collects/make" responsible (mflatt)
"collects/meta" responsible (eli)
"collects/meta/check-dists.ss" drdr ""
"collects/meta/drdr" responsible (jay) drdr ""
"collects/mred/edit-main.ss" drdr "mzc $path"
"collects/mred/edit.ss" drdr "mred-text -t $path"
"collects/mred/lang/main.ss" drdr "mred-text -t $path"
"collects/mred/main.ss" drdr "mred-text -t $path"
"collects/mred/mred-unit.ss" drdr "mred-text -t $path"
"collects/mred/mred.ss" drdr "mred-text -t $path"
"collects/mred/private/app.ss" drdr "mred-text -t $path"
"collects/mred/private/check.ss" drdr "mred-text -t $path"
"collects/mred/private/const.ss" drdr "mred-text -t $path"
"collects/mred/private/dynamic.ss" drdr "mred-text -t $path"
"collects/mred/private/editor.ss" drdr "mred-text -t $path"
"collects/mred/private/filedialog.ss" drdr "mred-text -t $path"
"collects/mred/private/fontdialog.ss" drdr "mred-text -t $path"
"collects/mred/private/gdi.ss" drdr "mred-text -t $path"
"collects/mred/private/helper.ss" drdr "mred-text -t $path"
"collects/mred/private/kernel.ss" drdr "mred-text -t $path"
"collects/mred/private/lock.ss" drdr "mred-text -t $path"
"collects/mred/private/messagebox.ss" drdr "mred-text -t $path"
"collects/mred/private/misc.ss" drdr "mred-text -t $path"
"collects/mred/private/moredialogs.ss" drdr "mred-text -t $path"
"collects/mred/private/mrcanvas.ss" drdr "mred-text -t $path"
"collects/mred/private/mrcontainer.ss" drdr "mred-text -t $path"
"collects/mred/private/mrgroupbox.ss" drdr "mred-text -t $path"
"collects/mred/private/mritem.ss" drdr "mred-text -t $path"
"collects/mred/private/mrmenu.ss" drdr "mred-text -t $path"
"collects/mred/private/mrpanel.ss" drdr "mred-text -t $path"
"collects/mred/private/mrpopup.ss" drdr "mred-text -t $path"
"collects/mred/private/mrtabgroup.ss" drdr "mred-text -t $path"
"collects/mred/private/mrtextfield.ss" drdr "mred-text -t $path"
"collects/mred/private/mrtop.ss" drdr "mred-text -t $path"
"collects/mred/private/mrwindow.ss" drdr "mred-text -t $path"
"collects/mred/private/path-dialog.ss" drdr "mred-text -t $path"
"collects/mred/private/repl.ss" drdr "mred-text -t $path"
"collects/mred/private/snipfile.ss" drdr "mred-text -t $path"
"collects/mred/private/wx.ss" drdr "mred-text -t $path"
"collects/mred/private/wxcanvas.ss" drdr "mred-text -t $path"
"collects/mred/private/wxcontainer.ss" drdr "mred-text -t $path"
"collects/mred/private/wxgroupbox.ss" drdr "mred-text -t $path"
"collects/mred/private/wxitem.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/editor-admin.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/editor-canvas.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/editor-snip.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/editor.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/keymap.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/mline.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/pasteboard.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/snip-admin.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/snip.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/stream.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/style.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/text.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/undo.ss" drdr "mred-text -t $path"
"collects/mred/private/wxme/wx.ss" drdr "mred-text -t $path"
"collects/mred/private/wxmenu.ss" drdr "mred-text -t $path"
"collects/mred/private/wxpanel.ss" drdr "mred-text -t $path"
"collects/mred/private/wxtabgroup.ss" drdr "mred-text -t $path"
"collects/mred/private/wxtextfield.ss" drdr "mred-text -t $path"
"collects/mred/private/wxtop.ss" drdr "mred-text -t $path"
"collects/mred/private/wxwindow.ss" drdr "mred-text -t $path"
"collects/mrlib" responsible (robby)
"collects/mrlib/aligned-pasteboard.ss" drdr "mred-text -t $path"
"collects/mrlib/bitmap-label.ss" drdr "mred-text -t $path"
"collects/mrlib/cache-image-snip.ss" drdr "mred-text -t $path"
"collects/mrlib/click-forwarding-editor.ss" drdr "mred-text -t $path"
"collects/mrlib/close-icon.ss" drdr "mred-text -t $path"
"collects/mrlib/gif.ss" drdr "mred-text -t $path"
"collects/mrlib/graph.ss" drdr "mred-text -t $path"
"collects/mrlib/hierlist/hierlist-unit.ss" drdr "mred-text -t $path"
"collects/mrlib/hierlist.ss" drdr "mred-text -t $path"
"collects/mrlib/image-core.ss" drdr "mred -t $path"
"collects/mrlib/include-bitmap.ss" drdr "mred-text -t $path"
"collects/mrlib/interactive-value-port.ss" drdr "mred-text -t $path"
"collects/mrlib/matrix-snip.ss" drdr "mred-text -t $path"
"collects/mrlib/name-message.ss" drdr "mred-text -t $path"
"collects/mrlib/path-dialog.ss" drdr "mred-text -t $path"
"collects/mrlib/plot.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/aligned-editor-container.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/aligned-pasteboard.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/geometry-managed-pasteboard.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/interface.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/locked-pasteboard.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/pasteboard-lib.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/snip-lib.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/stretchable-editor-snip.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/tests/actual-bigger.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/edit-sequence-loop.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/example-min.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/example.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/insertion-without-display.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/minimal.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/more-tests-margin-aligned.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/more-tests-margin.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/more-tests-min-stretchable.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/more-tests-min.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/more-tests-text.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/more-tests.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/snip-dumper.ss" drdr "mred-text -t $path"
"collects/mrlib/private/aligned-pasteboard/tests/stretchable-editor-snip-test-min.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/stretchable-editor-snip-test.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/test-alignment.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/test-locked-pasteboard.ss" drdr ""
"collects/mrlib/private/aligned-pasteboard/tests/test-macro.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/test-pasteboard-lib.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/test-snip-lib.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/test.ss" drdr "mred -f $path"
"collects/mrlib/private/aligned-pasteboard/tests/test2.ss" drdr "mred -f $path"
"collects/mrlib/private/image-core-bitmap.ss" drdr "mred-test -qt $path"
"collects/mrlib/switchable-button.ss" drdr "mred-text -t $path"
"collects/mrlib/syntax-browser.ss" drdr "mred-text -t $path"
"collects/mrlib/tab-choice.ss" drdr "mred-text -t $path"
"collects/mrlib/text-string-style-desc.ss" drdr "mred-text -t $path"
"collects/mysterx/main.ss" drdr "mzc $path"
"collects/mysterx/mxdemo.ss" drdr "mzc $path"
"collects/mysterx/mysterx.ss" drdr "mzc $path"
"collects/mysterx/private/mxmain.ss" drdr "mzc $path"
"collects/mysterx/private/prims.ss" drdr "mzc $path"
"collects/mzlib/contract.ss" responsible (robby)
"collects/mzlib/foreign.ss" responsible (eli)
"collects/mzlib/kw.ss" responsible (eli)
"collects/mzlib/match.ss" responsible (samth)
"collects/mzlib/pconvert.ss" responsible (robby)
"collects/mzlib/plt-match.ss" responsible (samth)
"collects/mzlib/private/shared-body.ss" drdr ""
"collects/mzlib/shared.ss" responsible (robby)
"collects/mzscheme/examples/cfile.ss" drdr ""
"collects/mzscheme/examples/curses-demo.ss" drdr ""
"collects/mzscheme/examples/fmod-ez.ss" drdr ""
"collects/mzscheme/examples/msgbox.ss" drdr ""
"collects/mzscheme/examples/tree-finish.ss" drdr ""
"collects/openssl" responsible (eli)
"collects/parser-tools" responsible (sowens)
"collects/parser-tools/private-lex/error-tests.ss" drdr ""
"collects/plai" responsible (jay)
"collects/plai/private/gc-gui.ss" drdr "mred -t $path"
"collects/planet" responsible (jacobm)
"collects/plot" responsible (eli)
"collects/plot/demos/demo-1.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-10.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-2.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-3.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-4.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-5.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-6.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-7.ss" drdr "mred-text -t $path"
"collects/plot/demos/demo-8.ss" drdr "mred-text -t $path"
"collects/plot/demos/fit-demo-1.ss" drdr "mred-text -t $path"
"collects/plot/demos/fit-demo-2.ss" drdr "mred-text -t $path"
"collects/plot/extend.ss" drdr "mred-text -t $path"
"collects/plot/main.ss" drdr "mred-text -t $path"
"collects/plot/plot-extend.ss" drdr "mred-text -t $path"
"collects/plot/plot.ss" drdr "mred-text -t $path"
"collects/plot/renderers.ss" drdr "mred-text -t $path"
"collects/plot/view.ss" drdr "mred-text -t $path"
"collects/preprocessor" responsible (eli)
"collects/profile" responsible (eli)
"collects/r5rs" responsible (mflatt)
"collects/r6rs/run.ss" drdr "mzc $path"
"collects/readline" responsible (mflatt)
"collects/redex" responsible (clklein)
"collects/redex/examples/arithmetic.ss" drdr "mred-text -t $path -- --no-print"
"collects/redex/examples/beginner.ss" drdr "mzscheme -t $path -m"
"collects/redex/examples/church.ss" drdr "mzc $path"
"collects/redex/examples/combinators.ss" drdr "mzc $path"
"collects/redex/examples/compatible-closure.ss" drdr "mzc $path"
"collects/redex/examples/letrec.ss" drdr "mzc $path"
"collects/redex/examples/mzscheme-machine/reduction-test.ss" drdr "mzc $path"
"collects/redex/examples/mzscheme-machine/verification-test.ss" drdr "mzc $path"
"collects/redex/examples/omega.ss" drdr "mzc $path"
"collects/redex/examples/r6rs/r6rs-tests.ss" drdr "mzc $path"
"collects/redex/examples/r6rs/show-examples.ss" drdr "mred-text $path"
"collects/redex/examples/semaphores.ss" drdr "mzc $path"
"collects/redex/examples/subject-reduction.ss" drdr "mzc $path"
"collects/redex/examples/threads.ss" drdr "mzc $path"
"collects/redex/examples/types.ss" drdr "mzc $path"
"collects/redex/gui.ss" drdr "mred-text -t $path"
"collects/redex/main.ss" drdr "mred-text -t $path"
"collects/redex/pict.ss" drdr "mred-text -t $path"
"collects/redex/private/arrow.ss" drdr "mred-text -t $path"
"collects/redex/private/core-layout.ss" drdr "mred-text -t $path"
"collects/redex/private/dot.ss" drdr "mred-text -t $path"
"collects/redex/private/pict.ss" drdr "mred-text -t $path"
"collects/redex/private/sexp-diffs.ss" drdr "mred-text -t $path"
"collects/redex/private/size-snip.ss" drdr "mred-text -t $path"
"collects/redex/private/stepper.ss" drdr "mred-text -t $path"
"collects/redex/private/traces.ss" drdr "mred-text -t $path"
"collects/redex/tests/bitmap-test-util.ss" drdr "mred-text -t $path"
"collects/redex/tests/bitmap-test.ss" drdr "mzc -k $path"
"collects/redex/tests/color-test.ss" drdr "mzc $path"
"collects/redex/tests/core-layout-test.ss" drdr "mzc $path"
"collects/redex/tests/hole-test.ss" drdr "mzc $path"
"collects/redex/tests/keyword-macros-test.ss" drdr "mzc $path"
"collects/redex/tests/matcher-test.ss" drdr "mzc $path"
"collects/redex/tests/pict-test.ss" drdr "mzc $path"
"collects/redex/tests/rg-test.ss" drdr "mzc $path"
"collects/redex/tests/run-tests.ss" drdr ("mred-text $path --examples --no-bitmaps" 180)
"collects/redex/tests/term-test.ss" drdr "mzc $path"
"collects/repos-time-stamp" responsible (eli)
"collects/repos-time-stamp/time-stamp.ss" drdr "mred-text -t $path"
"collects/scheme/contract/private/arrow.ss" responsible (robby)
"collects/scheme/contract/private/base.ss" responsible (robby)
"collects/scheme/contract/private/ds-helpers.ss" responsible (robby)
"collects/scheme/contract/private/ds.ss" responsible (robby)
"collects/scheme/contract/private/guts.ss" responsible (robby)
"collects/scheme/contract/private/helpers.ss" responsible (robby)
"collects/scheme/gui/base.ss" drdr "mred-text -t $path"
"collects/scheme/gui/init.ss" drdr "mred-text -t $path"
"collects/scheme/gui.ss" drdr "mred-text -t $path"
"collects/scheme/match" responsible (samth)
"collects/scheme/match.ss" responsible (samth)
"collects/schemeunit" responsible (noel ryanc)
"collects/schemeunit/gui.ss" responsible (ryanc) drdr "mred-text -t $path"
"collects/schemeunit/private/gui" responsible (ryanc)
"collects/schemeunit/private/gui/config.ss" drdr "mred-text -t $path"
"collects/schemeunit/private/gui/controller.ss" drdr "mred-text -t $path"
"collects/schemeunit/private/gui/gui.ss" drdr "mred-text -t $path"
"collects/schemeunit/private/gui/model2rml.ss" drdr "mred-text -t $path"
"collects/schemeunit/private/gui/rml.ss" drdr "mred-text -t $path"
"collects/schemeunit/private/gui/view.ss" drdr "mred-text -t $path"
"collects/schemeunit/tool.ss" responsible (ryanc) drdr "mred-text -t $path"
"collects/scribble/run.ss" drdr "mzc $path"
"collects/scribble/tools/drscheme-buttons.ss" drdr "mred-text"
"collects/scribble/tools/private/mk-drs-bitmaps.ss" drdr "mred-text"
"collects/scribblings/foreign/unsafe-foreign.ss" drdr "mzc $path"
"collects/scribblings/framework/standard-menus.scrbl" drdr ""
"collects/scribblings/guide/contracts-examples/6.ss" drdr "mzscheme -f $path"
"collects/scribblings/guide/read.scrbl" drdr ""
"collects/setup/main.ss" drdr ""
"collects/setup/plt-installer.ss" drdr "mred-text -t $path"
"collects/setup/setup-go.ss" drdr ""
"collects/setup/unixstyle-install.ss" drdr "mzc $path"
"collects/setup/winvers.ss" drdr "mzc $path"
"collects/sgl" responsible (jay sowens)
"collects/sgl/bitmap.ss" drdr "mred-text -t $path"
"collects/sgl/examples/alpha.ss" drdr "mzc $path"
"collects/sgl/examples/gears.ss" drdr "mzc -k $path"
"collects/sgl/examples/gl-frame.ss" drdr "mred-text -t $path"
"collects/sirmail" responsible (mflatt)
"collects/sirmail/folderr.ss" drdr "mred-text -t $path"
"collects/sirmail/main.ss" drdr "mzc $path"
"collects/sirmail/optionr.ss" drdr "mred-text -t $path"
"collects/sirmail/pref.ss" drdr "mred-text -t $path"
"collects/sirmail/readr.ss" drdr "mred-text -t $path"
"collects/sirmail/recover.ss" drdr "mzscheme -f $path"
"collects/sirmail/sendr.ss" drdr "mred-text -t $path"
"collects/sirmail/sirmail.ss" drdr "mzc $path"
"collects/sirmail/sirmailr.ss" drdr "mred-text -t $path"
"collects/sirmail/spell.ss" drdr "mred-text -t $path"
"collects/slatex/pdf-slatex-launcher.ss" drdr "mzc $path"
"collects/slatex/slatex-launcher.ss" drdr "mzc $path"
"collects/slideshow" responsible (mflatt robby)
"collects/slideshow/balloon.ss" drdr "mred-text -t $path"
"collects/slideshow/base.ss" drdr "mred-text -t $path"
"collects/slideshow/cmdline.ss" drdr "mred-text -t $path"
"collects/slideshow/code.ss" drdr "mred-text -t $path"
"collects/slideshow/core.ss" drdr "mred-text -t $path"
"collects/slideshow/examples/interlocking-components.scm" drdr "mzc $path"
"collects/slideshow/face.ss" drdr "mred-text -t $path"
"collects/slideshow/flash.ss" drdr "mred-text -t $path"
"collects/slideshow/initial-ones.ss" drdr "mred-text -t $path"
"collects/slideshow/main.ss" drdr "mred-text -t $path"
"collects/slideshow/param.ss" drdr "mred-text -t $path"
"collects/slideshow/pict-snipclass.ss" drdr "mred-text -t $path"
"collects/slideshow/pict.ss" drdr "mred-text -t $path"
"collects/slideshow/play.ss" drdr "mred-text -t $path"
"collects/slideshow/private/image-snipr.ss" drdr "mred-text -t $path"
"collects/slideshow/private/pict-box-lib.ss" drdr "mred-text -t $path"
"collects/slideshow/private/utils.ss" drdr "mred-text -t $path"
"collects/slideshow/run.ss" drdr "mred-text -t $path"
"collects/slideshow/slide.ss" drdr "mred-text -t $path"
"collects/slideshow/slides-to-picts.ss" drdr "mred-text -t $path"
"collects/slideshow/slideshow.ss" drdr "mred-text -t $path"
"collects/slideshow/start.ss" drdr "mzc $path"
"collects/slideshow/step.ss" drdr "mred-text -t $path"
"collects/slideshow/tool.ss" drdr "mred-text -t $path"
"collects/slideshow/tutorial-show.ss" drdr "mzc $path"
"collects/slideshow/viewer.ss" drdr "mred-text -t $path"
"collects/srfi/25/arlib.scm" drdr ""
"collects/srfi/25/ix-ctor.scm" drdr ""
"collects/srfi/25/op-ctor.scm" drdr ""
"collects/srfi/32/test.scm" drdr "mzscheme -f $path"
"collects/srfi/67/compare-reference.scm" drdr ""
"collects/srfi/74/blob.scm" drdr ""
"collects/srfi/78/check-reference.scm" drdr ""
"collects/srfi/78/examples-78.scm" drdr ""
"collects/srpersist/main.ss" drdr ""
"collects/srpersist/srpersist.ss" drdr ""
"collects/stepper" responsible (clements)
"collects/stepper/private/display-break-stuff.ss" drdr "mred-text -t $path"
"collects/stepper/private/mred-extensions.ss" drdr "mred-text -t $path"
"collects/stepper/private/vertical-separator-snip.ss" drdr "mred-text -t $path"
"collects/stepper/private/xml-snip-helpers.ss" drdr "mred-text -t $path"
"collects/stepper/stepper+xml-tool.ss" drdr "mred-text -t $path"
"collects/stepper/stepper-tool.ss" drdr "mred-text -t $path"
"collects/stepper/view-controller.ss" drdr "mred -t $path"
"collects/stepper/xml-tool.ss" drdr "mred-text -t $path"
"collects/string-constants" responsible (robby)
"collects/swindle" responsible (eli)
"collects/swindle/tool.ss" drdr "mred-text -t $path"
"collects/syntax" responsible (mflatt)
"collects/syntax-color" responsible (sowens)
"collects/teachpack" responsible (matthias)
"collects/teachpack/2htdp/scribblings/image-gen.ss" drdr "mred-text"
"collects/teachpack/2htdp/universe.ss" drdr "mred-text -t $path"
"collects/teachpack/balls.ss" drdr "mzc $path"
"collects/teachpack/deinprogramm/image.ss" drdr "mred-text -t $path"
"collects/teachpack/deinprogramm/line3d.ss" drdr "mred-text -t $path"
"collects/teachpack/deinprogramm/sound.ss" drdr "mred-text -t $path"
"collects/teachpack/deinprogramm/turtle.ss" drdr "mred-text -t $path"
"collects/teachpack/deinprogramm/universe.ss" drdr "mred-text -qt $path"
"collects/teachpack/deinprogramm/world.ss" drdr "mred-text -t $path"
"collects/teachpack/door.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/arrow-gui.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/arrow.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/convert.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/draw.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/elevator.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/graphing.ss" drdr "mzc $path"
"collects/teachpack/htdp/guess-gui.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/guess.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/gui.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/hangman.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/image.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/lkup-gui.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/master.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/matrix.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/show-queen.ss" drdr "mred-text -t $path"
"collects/teachpack/htdp/world.ss" drdr "mred-text -t $path"
"collects/teachpack/nuworld.ss" drdr "mred-text -t $path"
"collects/teachpack/server.ss" drdr "mred-text -t $path"
"collects/teachpack/turtles.ss" drdr "mred-text -t $path"
"collects/teachpack/value-turtles.ss" drdr "mred-text -t $path"
"collects/teachpack/world.ss" drdr "mred-text -t $path"
"collects/test-box-recovery/tool.ss" drdr "mred-text -t $path"
"collects/test-engine" responsible (kathyg)
"collects/test-engine/scheme-gui.ss" drdr "mred-text -t $path"
"collects/test-engine/test-coverage.scm" drdr "mred-text -t $path"
"collects/test-engine/test-display.scm" drdr "mred-text -t $path"
"collects/test-engine/test-tool.scm" drdr "mred-text -t $path"
"collects/tests/aligned-pasteboard/example.ss" drdr ""
"collects/tests/aligned-pasteboard/old-bugs/big-min.ss" drdr ""
"collects/tests/aligned-pasteboard/old-bugs/missing-min.ss" drdr ""
"collects/tests/aligned-pasteboard/snip-dumper.ss" drdr "mred-text -t $path"
"collects/tests/aligned-pasteboard/test-alignment.ss" drdr ""
"collects/tests/aligned-pasteboard/test-pasteboard-lib.ss" drdr ""
"collects/tests/aligned-pasteboard/test-snip-lib.ss" drdr ""
"collects/tests/aligned-pasteboard/test.ss" drdr "mred -f $path"
"collects/tests/aligned-pasteboard/test2.ss" drdr "mred -f $path"
"collects/tests/compiler" responsible (jay)
"collects/tests/compiler/regression.ss" responsible (mflatt)
"collects/tests/compiler/zo-test.ss" drdr "mzscheme -t $path -- -I -S -t 60 -v -R"
"collects/tests/deinprogramm" responsible (sperber)
"collects/tests/deinprogramm/image.ss" drdr "mred-text -t $path"
"collects/tests/deinprogramm/run-image-test.ss" drdr "mred-text -t $path"
"collects/tests/drscheme" responsible (robby)
"collects/tests/drscheme/drscheme-test-util.ss" drdr "mred -t $path"
"collects/tests/drscheme/io.ss" drdr "mred $path"
"collects/tests/drscheme/language-test.ss" drdr ("mred $path" 600)
"collects/tests/drscheme/module-lang-test-utils.ss" drdr "mred-text -t $path"
"collects/tests/drscheme/module-lang-test.ss" drdr ("mred $path" 120)
"collects/tests/drscheme/randomly-click-language-dialog.ss" drdr "mzc $path"
"collects/tests/drscheme/randomly-click-preferences.ss" drdr "mzc $path"
"collects/tests/drscheme/randomly-click.ss" drdr ""
"collects/tests/drscheme/repl-test.ss" drdr ("mred $path" 600)
"collects/tests/drscheme/sample-solutions-one-window.ss" drdr "mred-text -t $path"
"collects/tests/drscheme/save-teaching-lang-file.ss" drdr "mred $path"
"collects/tests/drscheme/stepper-test.ss" drdr "mred-text -t $path"
"collects/tests/drscheme/syncheck-test.ss" drdr "mred $path"
"collects/tests/drscheme/teachpack.ss" drdr "mred $path"
"collects/tests/drscheme/time-keystrokes.ss" drdr "mred-text -t $path"
"collects/tests/framework" responsible (robby)
"collects/tests/framework/canvas.ss" drdr "mzc -k $path"
"collects/tests/framework/debug.ss" drdr "mzc -k $path"
"collects/tests/framework/exit.ss" drdr "mzc -k $path"
"collects/tests/framework/frame.ss" drdr "mzc -k $path"
"collects/tests/framework/framework-test-engine.ss" drdr "mzc -k $path"
"collects/tests/framework/group-test.ss" drdr "mzc -k $path"
"collects/tests/framework/handler-test.ss" drdr "mzc -k $path"
"collects/tests/framework/info.ss" drdr "mzc -k $path"
"collects/tests/framework/keys.ss" drdr "mzc -k $path"
"collects/tests/framework/load.ss" drdr "mzc -k $path"
"collects/tests/framework/main.ss" drdr "mred $path"
"collects/tests/framework/mem.ss" drdr "mzc -k $path"
"collects/tests/framework/panel.ss" drdr "mzc -k $path"
"collects/tests/framework/pasteboard.ss" drdr "mzc -k $path"
"collects/tests/framework/prefs.ss" drdr "mzc -k $path"
"collects/tests/framework/scheme.ss" drdr "mzc -k $path"
"collects/tests/framework/search.ss" drdr "mzc -k $path"
"collects/tests/framework/test-suite-utils.ss" drdr "mzc -k $path"
"collects/tests/framework/text.ss" drdr "mzc -k $path"
"collects/tests/framework/utils.ss" drdr "mzscheme -f $path"
"collects/tests/frtime/time.ss" drdr "mred-text -t $path"
"collects/tests/future" responsible (jamesswaine mflatt robby)
"collects/tests/future/future.ss" drdr "mzscheme $path"
"collects/tests/future/random-future.ss" drdr 240
"collects/tests/macro-debugger" responsible (ryanc)
"collects/tests/macro-debugger/all-tests.ss" drdr "mred-text -t $path"
"collects/tests/macro-debugger/gui-tests.ss" drdr "mred-text -t $path"
"collects/tests/macro-debugger/tests/collects.ss" drdr "mred-text -t $path"
"collects/tests/mred" responsible (mflatt)
"collects/tests/mred/auto.ss" drdr "mred -f $path"
"collects/tests/mred/blits.ss" drdr "mred -f $path"
"collects/tests/mred/dc.ss" drdr "mred -f $path"
"collects/tests/mred/draw.ss" drdr "mzc $path"
"collects/tests/mred/editor.ss" drdr "mred -f $path"
"collects/tests/mred/gui-main.ss" drdr "mred -f $path"
"collects/tests/mred/gui.ss" drdr "mred -f $path"
"collects/tests/mred/item.ss" drdr "mzc $path"
"collects/tests/mred/loadtest.ss" drdr "mred -f $path"
"collects/tests/mred/mem.ss" drdr ""
"collects/tests/mred/paramz.ss" drdr "mred -f $path"
"collects/tests/mred/png.ss" drdr ""
"collects/tests/mred/random.ss" drdr ""
"collects/tests/mred/showkey.ss" drdr ""
"collects/tests/mred/sixlib.ss" drdr ""
"collects/tests/mred/test-editor-admin.ss" drdr "mred-text -t $path"
"collects/tests/mred/testing.ss" drdr "mred -f $path"
"collects/tests/mred/text-scale.ss" drdr ""
"collects/tests/mred/windowing.ss" drdr "mred -f $path"
"collects/tests/mred/wxme-doc-random.ss" drdr "mzc $path"
"collects/tests/mred/wxme-random.ss" drdr ""
"collects/tests/mred/wxme.ss" drdr "mred-text -t $path"
"collects/tests/mysterx/dhtmltests.ss" drdr ""
"collects/tests/mysterx/mystests.ss" drdr ""
"collects/tests/mzcom/test.ss" drdr ""
"collects/tests/mzscheme" responsible (mflatt)
"collects/tests/mzscheme/advanced.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/all.ss" drdr ""
"collects/tests/mzscheme/async-channel.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/awk.ss" drdr ""
"collects/tests/mzscheme/basic.ss" drdr ""
"collects/tests/mzscheme/beg-adv.ss" drdr ""
"collects/tests/mzscheme/beg-bega.ss" drdr ""
"collects/tests/mzscheme/beg-intm.ss" drdr ""
"collects/tests/mzscheme/beg-intml.ss" drdr ""
"collects/tests/mzscheme/bega-adv.ss" drdr ""
"collects/tests/mzscheme/beginner-abbr.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/beginner.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/benchmarks/common/auto.ss" drdr "mzscheme $path -- mzscheme ctak"
"collects/tests/mzscheme/benchmarks/common/conform.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/ctak.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/destruct.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/div.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/dynamic.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/dynamic2.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/graphs.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/lattice.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/maze.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/maze2.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/mazefun.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/mk-bigloo.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/mk-chicken.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/mk-gambit.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/nestedloop.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/nqueens.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/paraffins.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/peval.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/r5rs-wrap.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/benchmarks/common/scheme.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/scheme2.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/sort1.ss" drdr ""
"collects/tests/mzscheme/benchmarks/common/tak.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/takl.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/takr.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/common/takr2.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/mz/expand-class.scm" drdr "mzscheme -f $path"
"collects/tests/mzscheme/benchmarks/mz/parsing.scm" drdr "mred -f"
"collects/tests/mzscheme/benchmarks/mz/redsem.scm" drdr "mzscheme -f $path -- --skip-struct-test"
"collects/tests/mzscheme/benchmarks/mz/ssax.scm" drdr "mzscheme -f $path"
"collects/tests/mzscheme/benchmarks/rx/auto.ss" drdr ("mzscheme -qt $path -- mzscheme simple" 600)
"collects/tests/mzscheme/benchmarks/rx/pcre.ss" drdr "mzscheme $path \"mz\"\"scheme\""
"collects/tests/mzscheme/benchmarks/shootout/ackermann.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/binarytrees.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/chameneos.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/cheapconcurrency.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/fannkuch.ss" drdr "mzscheme -t $path -- 4"
"collects/tests/mzscheme/benchmarks/shootout/fasta.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/hash.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/hash2.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/mandelbrot-generic.ss" drdr "mzscheme -t $path -- 15"
"collects/tests/mzscheme/benchmarks/shootout/mandelbrot-unsafe.ss" drdr "mzscheme $path 3"
"collects/tests/mzscheme/benchmarks/shootout/mandelbrot.ss" drdr "mzscheme -t $path -- 15"
"collects/tests/mzscheme/benchmarks/shootout/meteor.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/nbody-generic.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/nbody-vec-generic.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/nbody-vec-unsafe.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/nbody-vec.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/nbody.ss" drdr "mzscheme -t $path -- 10"
"collects/tests/mzscheme/benchmarks/shootout/nestedloop.ss" drdr "mzscheme -t $path -- 2"
"collects/tests/mzscheme/benchmarks/shootout/nsieve.ss" drdr "mzscheme -t $path -- 2"
"collects/tests/mzscheme/benchmarks/shootout/nsievebits.ss" drdr "mzscheme -t $path -- 2"
"collects/tests/mzscheme/benchmarks/shootout/partialsums.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/benchmarks/shootout/pidigits-gmp.ss" drdr "mzscheme $path 10"
"collects/tests/mzscheme/benchmarks/shootout/pidigits.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/benchmarks/shootout/random.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/benchmarks/shootout/recursive.ss" drdr "mzscheme -t $path -- 2"
"collects/tests/mzscheme/benchmarks/shootout/run.ss" drdr "mzscheme -t $path -- nsieve.ss 1"
"collects/tests/mzscheme/benchmarks/shootout/spectralnorm-generic.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/benchmarks/shootout/spectralnorm-unsafe.ss" drdr "mzscheme $path 5"
"collects/tests/mzscheme/benchmarks/shootout/spectralnorm.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/benchmarks/shootout/spellcheck.ss" drdr "mzc $path"
"collects/tests/mzscheme/benchmarks/shootout/strcat.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/benchmarks/shootout/thread-ring.ss" drdr "mzscheme -t $path -- 25"
"collects/tests/mzscheme/binc.ss" drdr ""
"collects/tests/mzscheme/boundmap-test.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/cache-image-snip-test.ss" drdr "mred -f $path"
"collects/tests/mzscheme/censor.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/chaperone.ss" drdr ""
"collects/tests/mzscheme/char-set.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/chez-module.ss" drdr ""
"collects/tests/mzscheme/cm.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/cmdline.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/compat.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/compile.ss" drdr ""
"collects/tests/mzscheme/contmark.ss" drdr ""
"collects/tests/mzscheme/contract-mzlib-test.ss" drdr ""
"collects/tests/mzscheme/contract-opt-tests.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/contract-test.ss" responsible (robby) drdr ""
"collects/tests/mzscheme/control.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/date.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/deep.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/dict.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/embed-in-c.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/embed-me4.ss" drdr ""
"collects/tests/mzscheme/embed-me5.ss" drdr "mred-text -t $path"
"collects/tests/mzscheme/embed-me7.ss" drdr "mred-text -t $path"
"collects/tests/mzscheme/embed-me9.ss" drdr ""
"collects/tests/mzscheme/embed.ss" drdr ""
"collects/tests/mzscheme/etc.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/expand.ss" drdr ""
"collects/tests/mzscheme/fact.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/file.ss" drdr ""
"collects/tests/mzscheme/filelib.ss" drdr ("" 360)
"collects/tests/mzscheme/fixnum.ss" drdr ("mzscheme -f $path" 360)
"collects/tests/mzscheme/for.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/foreign-test.c" responsible (eli)
"collects/tests/mzscheme/foreign-test.ss" responsible (eli) drdr "mzscheme -f $path"
"collects/tests/mzscheme/function.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/head.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/htdp-image.ss" responsible (robby) drdr "mred -f $path"
"collects/tests/mzscheme/htdp-test.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/htdp.ss" drdr ""
"collects/tests/mzscheme/id-table-test.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/imap.ss" drdr ""
"collects/tests/mzscheme/intermediate-lambda.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/intermediate.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/intm-adv.ss" drdr ""
"collects/tests/mzscheme/intm-intml.ss" drdr ""
"collects/tests/mzscheme/intmlam-adv.ss" drdr ""
"collects/tests/mzscheme/ktest.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/kw.ss" responsible (eli) drdr "mzscheme -f $path"
"collects/tests/mzscheme/list.ss" drdr ""
"collects/tests/mzscheme/loadable.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/loadtest.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/logger.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/loop.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/ltest.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/macro.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/macrolib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/makeflat.ss" drdr ""
"collects/tests/mzscheme/makeflats.ss" drdr ""
"collects/tests/mzscheme/math.ss" drdr ""
"collects/tests/mzscheme/moddep.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/modprot.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/module-reader.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/module.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/mpair.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/mz-tests.ss" drdr ""
"collects/tests/mzscheme/mzlib-tests.ss" drdr ""
"collects/tests/mzscheme/mzq.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/name.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/namespac.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/nch.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/net.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/number.ss" drdr ""
"collects/tests/mzscheme/numstrs.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/object-old.ss" drdr ""
"collects/tests/mzscheme/object.ss" drdr ""
"collects/tests/mzscheme/oe.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/openssl.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/optimize.ss" drdr ""
"collects/tests/mzscheme/pack.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/package-gen.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/package.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/parallel.ss" drdr ""
"collects/tests/mzscheme/param.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/path.ss" drdr ""
"collects/tests/mzscheme/pathlib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/pconvert.ss" drdr ""
"collects/tests/mzscheme/place-channel.ss" drdr ""
"collects/tests/mzscheme/port.ss" drdr ""
"collects/tests/mzscheme/portlib.ss" drdr ""
"collects/tests/mzscheme/pp-regression.ss" drdr ""
"collects/tests/mzscheme/pretty.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/procs.ss" drdr ""
"collects/tests/mzscheme/prompt-tests.ss" drdr ""
"collects/tests/mzscheme/prompt.ss" drdr ""
"collects/tests/mzscheme/quiet.ss" drdr ("mzscheme -f $path" 360)
"collects/tests/mzscheme/read.ss" drdr ""
"collects/tests/mzscheme/readtable.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/restart.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/runflats.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/rx.ss" drdr ""
"collects/tests/mzscheme/sandbox.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/scheme-tests.ss" drdr ""
"collects/tests/mzscheme/serialize.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/set.ss" drdr ""
"collects/tests/mzscheme/shared-tests.ss" drdr ""
"collects/tests/mzscheme/shared.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/srfi.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/stream.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/string-mzlib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/string.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/struct.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/structlib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/stx.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/subprocess.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/sync.ss" drdr ""
"collects/tests/mzscheme/syntax-tests.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/syntax.ss" drdr ""
"collects/tests/mzscheme/tcp.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/testing.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/thread.ss" drdr ""
"collects/tests/mzscheme/threadlib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/thrport.ss" drdr ""
"collects/tests/mzscheme/trace.ss" drdr ""
"collects/tests/mzscheme/trait.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/ttt/listlib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/ttt/tic-bang.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/ttt/tic-func.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/ttt/ttt.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/ttt/uinc4.ss" drdr ""
"collects/tests/mzscheme/ttt/veclib.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/udp.ss" drdr ""
"collects/tests/mzscheme/uinc.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/uinc2.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/uinc3.ss" drdr ""
"collects/tests/mzscheme/uni-norm.ss" drdr ""
"collects/tests/mzscheme/unicode.ss" drdr ""
"collects/tests/mzscheme/unit.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/unitsig.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/unsafe.ss" drdr ""
"collects/tests/mzscheme/vector.ss" drdr ""
"collects/tests/mzscheme/version.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/will.ss" drdr "mzscheme -f $path"
"collects/tests/mzscheme/zo-marshal.ss" drdr ""
"collects/tests/mzscheme/ztest.ss" drdr ""
"collects/tests/net" responsible (eli)
"collects/tests/plai" responsible (jay)
"collects/tests/plai/gc/bad-mutators/mut-1.ss" drdr ""
"collects/tests/plai/gc/bad-mutators/mutator0.ss" drdr ""
"collects/tests/plai/gc/bad-mutators/mutator1.ss" drdr ""
"collects/tests/plai/gc/bad-mutators/mutator2.ss" drdr ""
"collects/tests/plai/gc/bad-mutators/mutator3.ss" drdr ""
"collects/tests/plai/gc/bad-mutators/mutator5.ss" drdr ""
"collects/tests/plai/gc/bad-mutators/void-app.ss" drdr ""
"collects/tests/plai/test-random-mutator.ss" responsible (jay robby)
"collects/tests/plai/web.ss" drdr "mzc -k $path"
"collects/tests/planet/cmdline-tool.ss" drdr ""
"collects/tests/planet/examples/dummy-module.ss" drdr ""
"collects/tests/plot/run-tests.ss" drdr "mred-text -t $path"
"collects/tests/run-automated-tests.ss" drdr ("mzc -k $path" 600)
"collects/tests/schemeunit" responsible (noel)
"collects/tests/srfi/1/run-tests.ss" drdr "mzscheme -f $path"
"collects/tests/srfi/40/run-tests.ss" drdr "mzscheme -f $path"
"collects/tests/srfi/43/run-tests.ss" drdr "mzscheme -f $path"
"collects/tests/srfi/load-srfis.ss" drdr "mzscheme -f $path"
"collects/tests/srpersist/srptests.ss" drdr ""
"collects/tests/stepper" responsible (clements)
"collects/tests/stepper/already-defined.ss" drdr ""
"collects/tests/stepper/bad-letrec-test.ss" drdr ""
"collects/tests/stepper/constructor-redexes.ss" drdr ""
"collects/tests/stepper/global-prim-reduction.ss" drdr ""
"collects/tests/stepper/image-test.ss" drdr ""
"collects/tests/stepper/intermediate-y.ss" drdr ""
"collects/tests/stepper/jump-to-ui-test.ss" drdr ""
"collects/tests/stepper/lambda-test.ss" drdr ""
"collects/tests/stepper/let-test.ss" drdr ""
"collects/tests/stepper/letrec-test.ss" drdr ""
"collects/tests/stepper/local-define-struct.ss" drdr ""
"collects/tests/stepper/local-test-2.ss" drdr ""
"collects/tests/stepper/local-test.ss" drdr ""
"collects/tests/stepper/long-error-message.ss" drdr ""
"collects/tests/stepper/multiply-defined.ss" drdr ""
"collects/tests/stepper/name-chaining.ss" drdr ""
"collects/tests/stepper/no-else-clause.ss" drdr ""
"collects/tests/stepper/non-procedure.ss" drdr ""
"collects/tests/stepper/print-convert-test.ss" drdr ""
"collects/tests/stepper/printing-reducing-test.ss" drdr ""
"collects/tests/stepper/procedure-display.ss" drdr ""
"collects/tests/stepper/right-redex.ss" drdr ""
"collects/tests/stepper/structures.ss" drdr ""
"collects/tests/stepper/symbol-identifier.ss" drdr ""
"collects/tests/stepper/symbols.ss" drdr ""
"collects/tests/stepper/syntax-error-ordering.ss" drdr ""
"collects/tests/stepper/test-or.ss" drdr ""
"collects/tests/stepper/two-tests.ss" drdr ""
"collects/tests/stepper/unannotated.ss" drdr ""
"collects/tests/stepper/undefined.ss" drdr ""
"collects/tests/stepper/world-test.ss" drdr ""
"collects/tests/stepper/write-display.ss" drdr ""
"collects/tests/stxparse" responsible (ryanc)
"collects/tests/stxparse/stxclass.ss" drdr "mred-text -t $path"
"collects/tests/syntax-color/paren-tree.ss" drdr "mzscheme -f $path"
"collects/tests/syntax-color/token-tree.ss" drdr "mzscheme -f $path"
"collects/tests/typed-scheme" responsible (samth)
"collects/tests/typed-scheme/fail" drdr ""
"collects/tests/typed-scheme/fail/with-type3.ss" responsible (sstrickl)
"collects/tests/typed-scheme/nightly-run.ss" drdr 600
"collects/tests/typed-scheme/run.ss" drdr ("" 600)
"collects/tests/typed-scheme/xfail" drdr ""
"collects/tests/units" responsible (sstrickl)
"collects/tests/units/multi-mod-sigs.ss" drdr "mzscheme -f $path"
"collects/tests/units/test-cert.ss" drdr "mzscheme -f $path"
"collects/tests/units/test-exptime.ss" drdr "mzscheme -f $path"
"collects/tests/units/test-harness.ss" drdr "mzscheme -f $path"
"collects/tests/units/test-runtime.ss" drdr "mzscheme -f $path"
"collects/tests/units/test-unit-contracts.ss" drdr "mzscheme -f $path"
"collects/tests/units/test-unit.ss" drdr "mzscheme -f $path"
"collects/tests/unstable/srcloc.ss" responsible (cce) drdr "mzscheme -f $path"
"collects/tests/utils/gui.ss" drdr "mred-text -t $path"
"collects/tests/web-server" responsible (jay)
"collects/tests/web-server/run-all-tests.ss" drdr 300
"collects/tests/web-server/servlet-env/env.ss" drdr "mzc $path"
"collects/tests/web-server/servlet-env/insta.ss" drdr "mzc -k $path"
"collects/tests/web-server/template/examples/blog-xexpr.ss" drdr "mzc $path"
"collects/tests/web-server/template/examples/blog.ss" drdr "mzc $path"
"collects/tests/xml" responsible (jay)
"collects/tests/xml/test-clark.ss" drdr ("" 300)
"collects/tests/xml/xml-snip-bug.ss" drdr "mred -t $path"
"collects/texpict/balloon.ss" drdr "mred-text -t $path"
"collects/texpict/code.ss" drdr "mred-text -t $path"
"collects/texpict/face-demo.ss" drdr "mzc $path"
"collects/texpict/face.ss" drdr "mred-text -t $path"
"collects/texpict/flash.ss" drdr "mred-text -t $path"
"collects/texpict/mrpict-unit.ss" drdr "mred-text -t $path"
"collects/texpict/mrpict.ss" drdr "mred-text -t $path"
"collects/texpict/pict-value-snip.ss" drdr "mred-text -t $path"
"collects/texpict/private/common-unit.ss" drdr "mred-text -t $path"
"collects/texpict/slideshow-run.ss" drdr "mred-text -t $path"
"collects/texpict/slideshow.ss" drdr "mred-text -t $path"
"collects/texpict/symbol.ss" drdr "mred-text -t $path"
"collects/texpict/texpict-unit.ss" drdr "mred-text -t $path"
"collects/texpict/texpict.ss" drdr "mred-text -t $path"
"collects/texpict/utils.ss" drdr "mred-text -t $path"
"collects/typed" responsible (samth)
"collects/typed/framework/framework.ss" drdr "mred-text -t $path"
"collects/typed/framework/prefs-contract.ss" drdr "mred-text -t $path"
"collects/typed/mred/mred.ss" drdr "mred-text -t $path"
"collects/typed-scheme" responsible (samth)
"collects/unstable/debug.ss" responsible (samth)
"collects/unstable/gui/notify.ss" drdr "mred-text -t $path"
"collects/unstable/gui/prefs.ss" drdr "mred-text -t $path"
"collects/unstable/hash.ss" responsible (samth)
"collects/unstable/match.ss" responsible (samth)
"collects/unstable/mutated-vars.ss" responsible (samth)
"collects/unstable/poly-c.ss" responsible (samth)
"collects/unstable/scribblings/debug.scrbl" responsible (samth)
"collects/unstable/scribblings/hash.scrbl" responsible (samth)
"collects/unstable/scribblings/match.scrbl" responsible (samth)
"collects/unstable/scribblings/mutated-vars.scrbl" responsible (samth)
"collects/unstable/scribblings/poly-c.scrbl" responsible (samth)
"collects/unstable/scribblings/sequence.scrbl" responsible (samth)
"collects/unstable/scribblings/utils.ss" responsible (samth)
"collects/unstable/sequence.ss" responsible (samth)
"collects/version" responsible (eli)
"collects/version/tool.ss" drdr "mred-text -t $path"
"collects/waterworld" responsible (eli)
"collects/waterworld/waterworld.ss" drdr "mzc $path"
"collects/web-server" responsible (jay)
"collects/web-server/default-web-root/configuration-table.ss" drdr ""
"collects/web-server/default-web-root/htdocs/servlets/examples/add-dispatch.ss" drdr "mzc $path"
"collects/web-server/default-web-root/htdocs/servlets/examples/bad-xexpr.ss" drdr "mzc $path"
"collects/web-server/default-web-root/htdocs/servlets/examples/basic.ss" drdr "mzc $path"
"collects/web-server/default-web-root/htdocs/servlets/examples/cookie.ss" drdr "mzc $path"
"collects/web-server/default-web-root/htdocs/servlets/examples/cookie2.ss" drdr "mzc $path"
"collects/web-server/default-web-root/htdocs/servlets/examples/digest.ss" drdr "mzc $path"
"collects/web-server/default-web-root/htdocs/servlets/examples/english-measure-questions.ss" drdr ""
"collects/web-server/default-web-root/htdocs/servlets/examples/response.ss" drdr "mzscheme -f $path"
"collects/web-server/main.ss" drdr ""
"collects/web-server/scribblings/tutorial/examples/dummy-10.ss" drdr ""
"collects/web-server/scribblings/tutorial/examples/dummy-3.ss" drdr ""
"collects/web-server/scribblings/tutorial/examples/iteration-1.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-10.ss" drdr ""
"collects/web-server/scribblings/tutorial/examples/iteration-2.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-3.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-4.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-5.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-6.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-7.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-8.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/iteration-9.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/model-3.ss" drdr ""
"collects/web-server/scribblings/tutorial/examples/no-use-redirect.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/send-suspend-1.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/send-suspend-2.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/test-static.ss" drdr "mzc $path"
"collects/web-server/scribblings/tutorial/examples/use-redirect.ss" drdr "mzc $path"
"collects/xml" responsible (jay)
"collects/xml/scheme-snipclass.ss" drdr "mred-text -t $path"
"collects/xml/text-box-tool.ss" drdr "mred-text -t $path"
"collects/xml/text-snipclass.ss" drdr "mred-text -t $path"
"collects/xml/xml-snipclass.ss" drdr "mred-text -t $path"
"doc/release-notes/COPYING-libscheme.txt" responsible (mflatt)
"doc/release-notes/COPYING.LIB" responsible (mflatt)
"doc/release-notes/drscheme" responsible (robby)
"doc/release-notes/mred" responsible (mflatt)
"doc/release-notes/mzscheme" responsible (mflatt)
"doc/release-notes/stepper" responsible (clements)
"man/man1/drscheme.1" responsible (robby)
"man/man1/mred.1" responsible (mflatt)
"man/man1/mzscheme.1" responsible (mflatt)
"man/man1/plt-help.1" responsible (robby)
"src/Makefile.in" responsible (mflatt)
"src/README" responsible (mflatt)
"src/a-list" responsible (mflatt)
"src/configure" responsible (mflatt)
"src/foreign" responsible (eli)
"src/lt" responsible (mflatt)
"src/mac" responsible (mflatt)
"src/mred" responsible (mflatt)
"src/mysterx" responsible (eli)
"src/mzcom" responsible (eli)
"src/mzscheme" responsible (mflatt)
"src/worksp" responsible (mflatt)
"src/wxcommon" responsible (mflatt)
"src/wxmac" responsible (mflatt)
"src/wxwindow" responsible (mflatt)
"src/wxxt" responsible (mflatt)

#:end-props |#
