(module url-sig (lib "a-signature.ss")
  get-pure-port
  get-impure-port
  post-pure-port
  post-impure-port
  head-pure-port
  head-impure-port
  delete-pure-port
  delete-impure-port
  put-pure-port
  put-impure-port
  display-pure-port
  purify-port
  netscape/string->url
  string->url
  url->string
  call/input-url
  combine-url/relative
  url-exception?
  current-proxy-servers)
