(display "\n\n\n****** test-leftist-heap.scm\n")
(load "test-leftist-heap.scm")
(display "\n\n\n****** test-list-set.scm\n")
(load "test-list-set.scm")
(display "\n\n\n****** test-red-black-tree-set.scm\n")
(load "test-red-black-tree-set.scm")
(display "\n\n\n****** test-list-bag.scm\n")
(load "test-list-bag.scm")
(display "\n\n\n****** test-red-black-tree-bag.scm\n")
(load "test-red-black-tree-bag.scm")
