
; Test MzLib
; See also pptest.rkt and ztest.rkt

(load-relative "loadtest.rktl")
(load-in-sandbox "mpair.rktl")
(load-in-sandbox "etc.rktl")
(load-in-sandbox "structlib.rktl")
(load-in-sandbox "async-channel.rktl")
(load-in-sandbox "restart.rktl")
(load-in-sandbox "string-mzlib.rktl")
(load-in-sandbox "pathlib.rktl")
(load-in-sandbox "filelib.rktl")
(load-in-sandbox "portlib.rktl")
(load-in-sandbox "threadlib.rktl")
(load-in-sandbox "set.rktl")
(load-in-sandbox "date.rktl")
(load-in-sandbox "compat.rktl")
(load-in-sandbox "cmdline.rktl")
(load-in-sandbox "pconvert.rktl")
(load-in-sandbox "pretty.rktl")
(load-in-sandbox "control.rktl")
(load-in-sandbox "serialize.rktl")
(load-in-sandbox "package.rktl")
(load-in-sandbox "contract-mzlib-test.rktl")
(load-in-sandbox "sandbox.rktl")
(load-in-sandbox "shared.rktl")
(load-in-sandbox "kw.rktl")
(load-in-sandbox "macrolib.rktl")

(report-errs)
