;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname tiles-error-tests) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ())))
(require picturing-programs)

(check-error (reflect-horiz 17)
             "reflect-horiz: expected <image> as first argument, given 17")
(check-error (reflect-vert "hello")
             "reflect-vert: expected <image> as first argument, given \"hello\"")
(check-error (reflect-main-diag true)
             "reflect-main-diag: expected <image> as first argument, given true")
(check-error (reflect-other-diag false)
             "reflect-other-diag: expected <image> as first argument, given false")
(check-error (flip-main 'blue)
             "flip-main: expected <image> as first argument, given 'blue")
(check-error (flip-other "snark")
             "flip-other: expected <image> as first argument, given \"snark\"")
(check-error (crop-left pic:hacker 50)
             "crop-left: expected <natural number <= 48> as second argument, given 50")
(check-error (crop-right pic:bloch 100)
             "crop-right: expected <natural number <= 93> as second argument, given 100")
(check-error (crop-top pic:book 56)
             "crop-top: expected <natural number <= 39> as second argument, given 56")
(check-error (crop-bottom pic:hacker 56)
             "crop-bottom: expected <natural number <= 48> as second argument, given 56")
(check-error (crop-left pic:hacker -3)
             "crop-left: expected <natural number <= 48> as second argument, given -3")
(check-error (crop-top pic:book 3.2)
             "crop-top: expected <natural number <= 39> as second argument, given 3.2")
(check-error (crop-bottom pic:book pic:book)
             "crop-bottom: expected <natural number <= 39> as second argument, given #<image>")
(check-error (rotate-cw 17)
             "rotate-cw: expected <image> as first argument, given 17")
(check-error (rotate-ccw true)
             "rotate-ccw: expected <image> as first argument, given true")
(check-error (rotate-180 "goodbye")
             "rotate-180: expected <image> as first argument, given \"goodbye\"")
