(module info (lib "infotab.ss" "setup")
  (require (lib "string-constant.ss" "string-constants"))
  (define name "Lazy Scheme")
  (define doc.txt "doc.txt")
  (define drscheme-language-modules '(("lazy.ss" "lazy")))
  (define drscheme-language-positions
    `((,(string-constant experimental-languages) "Lazy Scheme")))
  (define drscheme-language-numbers '((1000 -500)))
  (define drscheme-language-one-line-summaries '("Lazy Scheme"))
)
