#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote unstable/wrapc))
(check-docs (quote unstable/syntax))
(check-docs (quote unstable/struct))
(check-docs (quote unstable/string))
(check-docs (quote unstable/sequence))
(check-docs (quote unstable/pretty))
(check-docs (quote unstable/match))
(check-docs (quote unstable/markparam) #:skip #rx"^deserialize-info:")
(check-docs (quote unstable/list))
(check-docs (quote unstable/hash))
(check-docs (quote unstable/function))
(check-docs (quote unstable/find))
(check-docs (quote unstable/debug))
(check-docs (quote unstable/contract))
(check-docs (quote unstable/class-iop))
(check-docs (quote unstable/bytes))
