DRAW = /Users/matthias/plt/collects/htdch/

FILES = \
  World \
  Canvas

doc: 
	javadoc -classpath $(DRAW) $(addsuffix .java, $(FILES)) -d docs -breakiterator

compile: 

run: 

test: 

clean: 
	rm -rf *~ *.class docs/


