#lang scheme/base
(provide mapping)
;; this file is generated by image-gen.ss -- do not edit
;; note that the file that creates this file depends on this file
;; it is always safe to simply define (and provide) mapping as the empty list

(define mapping
  (list
   (list '(image-height (rectangle 100 100 "solid" "black")) 'val 100)
   (list '(image-baseline (rectangle 100 100 "solid" "black")) 'val 100)
   (list '(image-height (text "Hello" 24 "black")) 'val 24.0)
   (list '(image-baseline (text "Hello" 24 "black")) 'val 18.0)
   (list
    '(image-height
      (overlay (circle 20 "solid" "orange") (circle 30 "solid" "purple")))
    'val
    60)
   (list '(image-height (circle 30 "solid" "orange")) 'val 60)
   (list '(image-height (ellipse 30 40 "solid" "orange")) 'val 40)
   (list
    '(image-width
      (beside (circle 20 "solid" "orange") (circle 20 "solid" "purple")))
    'val
    80)
   (list '(image-width (circle 30 "solid" "orange")) 'val 60)
   (list '(image-width (ellipse 30 40 "solid" "orange")) 'val 30)
   (list
    '(beside/places
      "bottom"
      (ellipse 20 70 "solid" "lightsteelblue")
      (frame (ellipse 20 50 "solid" "mediumslateblue"))
      (ellipse 20 30 "solid" "slateblue")
      (ellipse 20 10 "solid" "navy"))
    'image
    "5d9d7eb8c7.png")
   (list '(frame (ellipse 20 20 "outline" "black")) 'image "6a5a617f28.png")
   (list '(ellipse 60 60 "solid" "blue") 'image "d92d6a49f1.png")
   (list
    '(scale/xy 3 2 (ellipse 20 30 "solid" "blue"))
    'image
    "2e6a31a9033.png")
   (list '(ellipse 40 60 "solid" "blue") 'image "196bfa7b9c4.png")
   (list '(scale 2 (ellipse 20 30 "solid" "blue")) 'image "2d9ba9032e.png")
   (list
    '(rotate
      45
      (beside/places
       "center"
       (rectangle 40 20 "solid" "darkseagreen")
       (rectangle 20 100 "solid" "darkseagreen")))
    'image
    "292b77d2270.png")
   (list
    '(rotate 5 (rectangle 50 50 "outline" "black"))
    'image
    "13b344ed2ff.png")
   (list
    '(rotate 45 (ellipse 60 20 "solid" "olivedrab"))
    'image
    "28daec71a64.png")
   (list
    '(above/places
      "center"
      (ellipse 70 20 "solid" "yellowgreen")
      (ellipse 50 20 "solid" "olivedrab")
      (ellipse 30 20 "solid" "darkolivegreen")
      (ellipse 10 20 "solid" "darkgreen"))
    'image
    "29c8557c53a.png")
   (list
    '(above/places
      "right"
      (ellipse 70 20 "solid" "gold")
      (ellipse 50 20 "solid" "goldenrod")
      (ellipse 30 20 "solid" "darkgoldenrod")
      (ellipse 10 20 "solid" "sienna"))
    'image
    "2865c0c88d9.png")
   (list
    '(above
      (ellipse 70 20 "solid" "gray")
      (ellipse 50 20 "solid" "darkgray")
      (ellipse 30 20 "solid" "dimgray")
      (ellipse 10 20 "solid" "black"))
    'image
    "aac8b78b6e.png")
   (list
    '(beside/places "baseline" (text "ijy" 18 "black") (text "ijy" 24 "black"))
    'image
    "11477a8292d.png")
   (list
    '(beside/places
      "center"
      (ellipse 20 70 "solid" "mediumorchid")
      (ellipse 20 50 "solid" "darkorchid")
      (ellipse 20 30 "solid" "purple")
      (ellipse 20 10 "solid" "indigo"))
    'image
    "1dd3a9fcdbb.png")
   (list
    '(beside/places
      "bottom"
      (ellipse 20 70 "solid" "lightsteelblue")
      (ellipse 20 50 "solid" "mediumslateblue")
      (ellipse 20 30 "solid" "slateblue")
      (ellipse 20 10 "solid" "navy"))
    'image
    "fe15a0a20c.png")
   (list
    '(beside
      (ellipse 20 70 "solid" "gray")
      (ellipse 20 50 "solid" "darkgray")
      (ellipse 20 30 "solid" "dimgray")
      (ellipse 20 10 "solid" "black"))
    'image
    "28c73238138.png")
   (list
    '(overlay/xy
      (overlay/xy
       (ellipse 40 40 "outline" "black")
       10
       15
       (ellipse 10 10 "solid" "forestgreen"))
      20
      15
      (ellipse 10 10 "solid" "forestgreen"))
    'image
    "10847861f4b.png")
   (list
    '(overlay/xy
      (rectangle 20 20 "solid" "red")
      -20
      -20
      (rectangle 20 20 "solid" "black"))
    'image
    "133309751d2.png")
   (list
    '(overlay/xy
      (rectangle 20 20 "solid" "red")
      20
      20
      (rectangle 20 20 "solid" "black"))
    'image
    "15717b87d30.png")
   (list
    '(overlay/xy
      (rectangle 20 20 "outline" "black")
      20
      0
      (rectangle 20 20 "outline" "black"))
    'image
    "1f0b671ed7b.png")
   (list
    '(overlay/places
      "right"
      "bottom"
      (rectangle 20 20 "solid" "silver")
      (rectangle 30 30 "solid" "seagreen")
      (rectangle 40 40 "solid" "silver")
      (rectangle 50 50 "solid" "seagreen"))
    'image
    "201133dd679.png")
   (list
    '(overlay/places
      "middle"
      "middle"
      (rectangle 30 60 "solid" "orange")
      (ellipse 60 30 "solid" "purple"))
    'image
    "13b365251d3.png")
   (list
    '(overlay
      (ellipse 10 10 "solid" "red")
      (ellipse 20 20 "solid" "black")
      (ellipse 30 30 "solid" "red")
      (ellipse 40 40 "solid" "black")
      (ellipse 50 50 "solid" "red")
      (ellipse 60 60 "solid" "black"))
    'image
    "26c4c403875.png")
   (list
    '(overlay
      (rectangle 30 60 "solid" "orange")
      (ellipse 60 30 "solid" "purple"))
    'image
    "4e85791a5.png")
   (list
    '(text/font "not really a link" 18 "blue" #f 'roman 'normal 'normal #t)
    'image
    "27bbbb6fd64.png")
   (list
    '(text/font "Goodbye" 18 "indigo" #f 'modern 'italic 'normal #f)
    'image
    "24e80ea10b4.png")
   (list
    '(text/font "Hello" 24 "olive" "Gill Sans" 'swiss 'normal 'bold #f)
    'image
    "169f2ceb45c.png")
   (list '(text "Goodbye" 36 "indigo") 'image "169990a635e.png")
   (list '(text "Hello" 24 "olive") 'image "1bbeedc0d6.png")
   (list
    '(add-line
      (ellipse 80 60 "outline" "darkolivegreen")
      (+ 40 (* 40 (cos (* pi 1/4))))
      (+ 30 (* 30 (sin (* pi 1/4))))
      (+ 40 (* 40 (cos (* pi 5/4))))
      (+ 30 (* 30 (sin (* pi 5/4))))
      "darkolivegreen")
    'image
    "17ca1cb72eb.png")
   (list
    '(add-line (ellipse 40 40 "outline" "maroon") 0 40 40 0 "maroon")
    'image
    "89b3a9e462.png")
   (list '(line 30 -20 "red") 'image "12948ac080d.png")
   (list '(line -30 20 "red") 'image "69aaaa680d.png")
   (list '(line 30 30 "black") 'image "8e1ebaaf82.png")
   (list
    '(polygon
      (list
       (make-posn 0 0)
       (make-posn 0 40)
       (make-posn 20 40)
       (make-posn 20 60)
       (make-posn 40 60)
       (make-posn 40 20)
       (make-posn 20 20)
       (make-posn 20 0))
      "solid"
      "plum")
    'image
    "150e1d5e9f.png")
   (list
    '(polygon
      (list
       (make-posn 0 0)
       (make-posn -10 20)
       (make-posn 60 0)
       (make-posn -10 -20))
      "solid"
      "burlywood")
    'image
    "25354f2b84e.png")
   (list
    '(star-polygon 20 10 3 "solid" "cornflowerblue")
    'image
    "2cc717fb347.png")
   (list '(star-polygon 40 7 3 "outline" "darkred") 'image "2330a222ac0.png")
   (list '(star-polygon 40 5 2 "solid" "seagreen") 'image "24410dd26db.png")
   (list '(star 40 "solid" "gray") 'image "b32ce6fcc5.png")
   (list '(regular-polygon 20 8 "solid" "red") 'image "268c974b9ab.png")
   (list '(regular-polygon 40 4 "outline" "blue") 'image "957fe78565.png")
   (list '(regular-polygon 50 3 "outline" "red") 'image "1325a6e7bdb.png")
   (list '(rhombus 80 150 "solid" "mediumpurple") 'image "24365c877d4.png")
   (list '(rhombus 40 45 "solid" "magenta") 'image "5ec4a0cb1f.png")
   (list '(rectangle 20 40 "solid" "blue") 'image "16a631adf1e.png")
   (list '(rectangle 40 20 "outline" "black") 'image "10735f73f78.png")
   (list '(square 50 "outline" "darkmagenta") 'image "89a0d469a7.png")
   (list '(square 40 "solid" "slateblue") 'image "d417a51b4.png")
   (list
    '(isosceles-triangle 60 330 "solid" "lightseagreen")
    'image
    "138792ad221.png")
   (list
    '(isosceles-triangle 60 30 "solid" "aquamarine")
    'image
    "d47072011e.png")
   (list
    '(isosceles-triangle 200 170 "solid" "seagreen")
    'image
    "2dde939d6dc.png")
   (list '(right-triangle 36 48 "solid" "black") 'image "1a0088e3819.png")
   (list '(triangle 40 "solid" "tan") 'image "aeddf66d5d.png")
   (list '(ellipse 20 40 "solid" "blue") 'image "25451dd2997.png")
   (list '(ellipse 40 20 "outline" "black") 'image "8cb34e62d4.png")
   (list '(circle 20 "solid" "blue") 'image "54d58bf7f6.png")
   (list '(circle 30 "outline" "red") 'image "262a4fa650a.png")))
