(module info (lib "infotab.ss" "setup")
  (define name "Skipper")
  #;(define tools '(("debug-tool.ss")))
  (define blurb '("Experimental Debugger"))
  #;(define tool-names '("Skipper"))
  #;(define tool-icons '(("icon-big.png" "skipper")))
)
