
; Test MzLib
; See also pptest.rkt and ztest.rkt

(load-relative "loadtest.rkt")
(load-in-sandbox "mpair.rkt")
(load-in-sandbox "etc.rkt")
(load-in-sandbox "structlib.rkt")
(load-in-sandbox "async-channel.rkt")
(load-in-sandbox "restart.rkt")
(load-in-sandbox "string-mzlib.rkt")
(load-in-sandbox "pathlib.rkt")
(load-in-sandbox "filelib.rkt")
(load-in-sandbox "portlib.rkt")
(load-in-sandbox "threadlib.rkt")
(load-in-sandbox "set.rkt")
(load-in-sandbox "date.rkt")
(load-in-sandbox "compat.rkt")
(load-in-sandbox "cmdline.rkt")
(load-in-sandbox "pconvert.rkt")
(load-in-sandbox "pretty.rkt")
(load-in-sandbox "control.rkt")
(load-in-sandbox "serialize.rkt")
(load-in-sandbox "package.rkt")
(load-in-sandbox "contract-mzlib-test.rkt")
(load-in-sandbox "sandbox.rkt")
(load-in-sandbox "shared.rkt")
(load-in-sandbox "kw.rkt")
(load-in-sandbox "macrolib.rkt")

(report-errs)
