;; SRFI Tests

(load-relative "loadtest.ss")

;; Test that all SRFIs load.  Run this in both DrScheme and
;; MzScheme for maximum coverage.

;; We just require all the SRFIs and hope nothing bombs.
;; Keep an eye out for error messages!

(require (lib "1.ss"              "srfi"))
(require (lib "list.ss"           "srfi" "1"))
(require (lib "and-let.ss"        "srfi" "2"))
(require (lib "4.ss"              "srfi"))
(require (lib "let.ss"            "srfi" "5"))
(require (lib "6.ss"              "srfi"))
(require (lib "program.ss"        "srfi" "7"))
(require (lib "receive.ss"        "srfi" "8"))
(require (lib "record.ss"         "srfi" "9"))
(require (lib "11.ss"             "srfi"))
(require (lib "string.ss"         "srfi" "13"))
(require (lib "char-set.ss"       "srfi" "14"))
(require (lib "16.ss"             "srfi"))
(require (lib "set.ss"            "srfi" "17"))
(require (lib "18.ss"             "srfi"))
(require (lib "time.ss"           "srfi" "19"))
(require (lib "23.ss"             "srfi"))
(require (lib "array.ss"          "srfi" "25"))
(require (lib "cut.ss"            "srfi" "26"))
(require (lib "random-bits.ss"    "srfi" "27"))
(require (lib "28.ss"             "srfi"))
(require (lib "localization.ss"   "srfi" "29"))
(require (lib "30.ss"             "srfi"))
(require (lib "rec.ss"            "srfi" "31"))
(require (lib "sort.scm"          "srfi" "32"))
(require (lib "exception.ss"      "srfi" "34"))
(require (lib "35.ss"             "srfi"))
(require (lib "condition.ss"      "srfi" "35"))
(require (lib "38.ss"             "srfi"))
(require (lib "39.ss"             "srfi"))
(require (lib "stream.ss"         "srfi" "40"))
(require (lib "comprehensions.ss" "srfi" "42"))
(require (lib "vector-lib.ss"     "srfi" "43"))
(require (lib "lazy.ss"           "srfi" "45"))
(require (lib "format.ss"         "srfi" "48"))
(require (lib "cat.ss"            "srfi" "54"))
(require (lib "records.ss"        "srfi" "57"))
(require (lib "vicinity.ss"       "srfi" "59"))
(require (lib "60.ss"             "srfi" "60"))
(require (lib "61.ss"             "srfi"))
(require (lib "63.ss"             "srfi"))
(require (lib "64.ss"             "srfi"))
(require (lib "testing.ss"        "srfi" "64"))
(require (lib "66.ss"             "srfi" "66"))
(require (lib "compare.ss"        "srfi" "67"))
(require (lib "hash.ss"           "srfi" "69"))
(require (lib "letvalues.ss"      "srfi" "71"))
(require (lib "74.ss"             "srfi" "74"))
(require (lib "check.ss"          "srfi" "78"))
(require (lib "86.ss"             "srfi"))
(require (lib "case.ss"           "srfi" "87"))
