#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote sirmail/utilr))
(check-docs (quote sirmail/spell))
(check-docs (quote sirmail/sirmails))
(check-docs (quote sirmail/sirmailr))
(check-docs (quote sirmail/sirmail))
(check-docs (quote sirmail/sendr))
(check-docs (quote sirmail/recover))
(check-docs (quote sirmail/readr))
(check-docs (quote sirmail/pref))
(check-docs (quote sirmail/optionr))
(check-docs (quote sirmail))
(check-docs (quote sirmail/folderr))
