AC_ARG_ENABLE(csdefault,  [  --enable-csdefault      install CS without suffix])
AC_ARG_ENABLE(csonly,     [  --enable-csonly         CS default, and skip BC build])
AC_ARG_ENABLE(cs,         [  --enable-cs             CS enabled])
AC_ARG_ENABLE(bcdefault,  [  --enable-bcdefault      install BC without suffix])
AC_ARG_ENABLE(bconly,     [  --enable-bconly         BC default, and skip CS build])
AC_ARG_ENABLE(bc,         [  --enable-bc             BC enabled])
AC_ARG_ENABLE(cgcdefault, [  --enable-cgcdefault     BC CGC default (discouraged)])
