#!/bin/sh

run() {
  exe="gracket"
  if [ "x$1" = "x-t" ]; then exe="racket"; shift; fi
  "$exe" "$1"
  echo "done:--- $1 ---"
  echo ""
}

cd tests 

run key-error.rkt
run bad-draw.rkt
run error-in-tick.rkt
run error-in-draw.rkt
run -t batch-io.rkt
run -t batch-io2.rkt
run -t batch-io3.rkt
run clause-once.rkt
run full-scene-visible.rkt
run image-too-large.rkt
run image-equality-performance-htdp.rkt
run image-equality-performance.rkt
run mouse-evt.rkt
run on-tick-defined.rkt
run perform-robby.rkt
run profile-robby.rkt
run release.rkt
run stop.rkt
run test-image.rkt
run ufo-rename.rkt
run server-rename.rkt
run world0-stops.rkt
run record.rkt
run record-stop-when.rkt
run stop-when-crash.rkt
run on-tick-universe-with-limit.rkt
run on-tick-with-limit.rkt
run on-release-no-key.rkt
run struct-universe.rkt
run universe-receive.rkt
run universe-restart.rkt
run name.rkt
run pad1.rkt
run pad1-handler.rkt
run pad1-in-bsl.rkt
run error-messages.rkt
