
(define-primitive-table flfxnum-table
  [->fl (known-procedure/folding 2)]
  [fl* (known-procedure/folding -1)]
  [fl+ (known-procedure/folding -1)]
  [fl- (known-procedure/folding -2)]
  [fl->exact-integer (known-procedure/folding 2)]
  [fl->fx (known-procedure/has-unsafe/folding 2 'unsafe-fl->fx)]
  [fl/ (known-procedure/folding -2)]
  [fl< (known-procedure/folding -2)]
  [fl<= (known-procedure/folding -2)]
  [fl= (known-procedure/folding -2)]
  [fl> (known-procedure/folding -2)]
  [fl>= (known-procedure/folding -2)]
  [flabs (known-procedure/folding 2)]
  [flacos (known-procedure/folding 2)]
  [flasin (known-procedure/folding 2)]
  [flatan (known-procedure/folding 2)]
  [flceiling (known-procedure/folding 2)]
  [flcos (known-procedure/folding 2)]
  [flexp (known-procedure/folding 2)]
  [flexpt (known-procedure/folding 4)]
  [flfloor (known-procedure/folding 2)]
  [flimag-part (known-procedure/folding 2)]
  [fllog (known-procedure/folding 2)]
  [flmax (known-procedure/folding -2)]
  [flmin (known-procedure/folding -2)]
  [flreal-part (known-procedure/folding 2)]
  [flround (known-procedure/folding 2)]
  [flsin (known-procedure/folding 2)]
  [flsingle (known-procedure/folding 2)]
  [flsqrt (known-procedure/folding 2)]
  [fltan (known-procedure/folding 2)]
  [fltruncate (known-procedure/folding 2)]
  [flvector (known-procedure/single-valued -1)]
  [flvector-length (known-procedure/folding 2)]
  [flvector-ref (known-procedure/folding 4)]
  [flvector-set! (known-procedure/folding 8)]
  [flvector? (known-procedure/pure/folding 2)]
  [fx* (known-procedure/folding/limited -1 'fixnum)]
  [fx*/wraparound (known-procedure/folding/limited 4 'fixnum)]
  [fx+ (known-procedure/folding/limited -1 'fixnum)]
  [fx+/wraparound (known-procedure/folding/limited 4 'fixnum)]
  [fx- (known-procedure/folding/limited -2 'fixnum)]
  [fx-/wraparound (known-procedure/folding/limited 4 'fixnum)]
  [fx->fl (known-procedure/has-unsafe/folding/limited 2 'unsafe-fx->fl 'fixnum)]
  [fx< (known-procedure/folding/limited -2 'fixnum)]
  [fx<= (known-procedure/folding/limited -2 'fixnum)]
  [fx= (known-procedure/folding/limited -2 'fixnum)]
  [fx> (known-procedure/folding/limited -2 'fixnum)]
  [fx>= (known-procedure/folding/limited -2 'fixnum)]
  [fxabs (known-procedure/folding/limited 2 'fixnum)]
  [fxand (known-procedure/folding/limited -1 'fixnum)]
  [fxior (known-procedure/folding/limited -1 'fixnum)]
  [fxlshift (known-procedure/has-unsafe/folding/limited 4 'unsafe-fxlshift 'fixnum)]
  [fxlshift/wraparound (known-procedure/has-unsafe/folding/limited 4 'unsafe-fxlshift/wraparound 'fixnum)]
  [fxmax (known-procedure/folding/limited -2 'fixnum)]
  [fxmin (known-procedure/folding/limited -2 'fixnum)]
  [fxmodulo (known-procedure/folding/limited 4 'fixnum)]
  [fxnot (known-procedure/folding/limited 2 'fixnum)]
  [fxpopcount (known-procedure/folding/limited 2 'fixnum)]
  [fxpopcount32 (known-procedure/folding/limited 2 'fixnum)]
  [fxpopcount16 (known-procedure/folding/limited 2 'fixnum)]
  [fxquotient (known-procedure/folding/limited 4 'fixnum)]
  [fxremainder (known-procedure/folding/limited 4 'fixnum)]
  [fxrshift (known-procedure/has-unsafe/folding/limited 4 'unsafe-fxrshift 'fixnum)]
  [fxrshift/logical (known-procedure/has-unsafe/folding/limited 4 'unsafe-fxrshift/logical 'fixnum)]
  [fxvector (known-procedure/single-valued -1)]
  [fxvector-length (known-procedure/folding/limited 2 'fixnum)]
  [fxvector-ref (known-procedure/folding/limited 4 'fixnum)]
  [fxvector-set! (known-procedure/folding/limited 8 'fixnum)]
  [fxvector? (known-procedure/pure/folding 2)]
  [fxxor (known-procedure/folding/limited -1 'fixnum)]
  [make-flrectangular (known-procedure/folding 4)]
  [make-flvector (known-procedure/no-prompt 6)]
  [make-fxvector (known-procedure/no-prompt 6)]
  [make-shared-flvector (known-procedure/no-prompt 6)]
  [make-shared-fxvector (known-procedure/no-prompt 6)]
  [most-positive-fixnum (known-procedure/pure 1)]
  [most-negative-fixnum (known-procedure/pure 1)]
  [shared-flvector (known-procedure/no-prompt -1)]
  [shared-fxvector (known-procedure/no-prompt -1)])
