
(define-primitive-table foreign-table
  [_bool (known-constant)]
  [_bytes (known-constant)]
  [_double (known-constant)]
  [_double* (known-constant)]
  [_fixint (known-constant)]
  [_fixnum (known-constant)]
  [_float (known-constant)]
  [_fpointer (known-constant)]
  [_gcpointer (known-constant)]
  [_int16 (known-constant)]
  [_int32 (known-constant)]
  [_int64 (known-constant)]
  [_int8 (known-constant)]
  [_longdouble (known-constant)]
  [_path (known-constant)]
  [_pointer (known-constant)]
  [_scheme (known-constant)]
  [_stdbool (known-constant)]
  [_string/ucs-4 (known-constant)]
  [_string/utf-16 (known-constant)]
  [_symbol (known-constant)]
  [_ufixint (known-constant)]
  [_ufixnum (known-constant)]
  [_uint16 (known-constant)]
  [_uint32 (known-constant)]
  [_uint64 (known-constant)]
  [_uint8 (known-constant)]
  [_void (known-constant)]
  [compiler-sizeof (known-procedure 2)]
  [cpointer-gcable? (known-procedure 2)]
  [cpointer-tag (known-procedure 2)]
  [cpointer? (known-procedure 2)]
  [ctype-alignof (known-procedure 2)]
  [ctype-basetype (known-procedure 2)]
  [ctype-c->scheme (known-procedure 2)]
  [ctype-scheme->c (known-procedure 2)]
  [ctype-sizeof (known-procedure 2)]
  [ctype? (known-procedure 2)]
  [end-stubborn-change (known-procedure 2)]
  [extflvector->cpointer (known-procedure 2)]
  [ffi-call (known-procedure 504)]
  [ffi-call-maker (known-procedure 252)]
  [ffi-callback (known-procedure 120)]
  [ffi-callback? (known-procedure 2)]
  [ffi-callback-maker (known-procedure 60)]
  [ffi-lib (known-procedure 14)]
  [ffi-lib-name (known-procedure 2)]
  [ffi-lib? (known-procedure 2)]
  [ffi-obj (known-procedure 4)]
  [ffi-obj-lib (known-procedure 2)]
  [ffi-obj-name (known-procedure 2)]
  [ffi-obj? (known-procedure 2)]
  [flvector->cpointer (known-procedure 2)]
  [free (known-procedure 2)]
  [free-immobile-cell (known-procedure 2)]
  [lookup-errno (known-procedure 2)]
  [make-array-type (known-procedure 4)]
  [make-cstruct-type (known-procedure 14)]
  [make-ctype (known-procedure 8)]
  [make-late-weak-box (known-procedure 2)]
  [make-late-weak-hasheq (known-procedure 1)]
  [make-sized-byte-string (known-procedure 4)]
  [make-stubborn-will-executor (known-procedure 1)]
  [make-union-type (known-procedure -2)]
  [malloc (known-procedure 62)]
  [malloc-immobile-cell (known-procedure 2)]
  [memcpy (known-procedure 120)]
  [memmove (known-procedure 120)]
  [memset (known-procedure 56)]
  [offset-ptr? (known-procedure 2)]
  [prop:cpointer (known-constant)]
  [ptr-add (known-procedure 12)]
  [ptr-add! (known-procedure 12)]
  [ptr-equal? (known-procedure 4)]
  [ptr-offset (known-procedure 2)]
  [ptr-ref (known-procedure 28)]
  [ptr-set! (known-procedure 56)]
  [saved-errno (known-procedure 3)]
  [set-cpointer-tag! (known-procedure 4)]
  [set-ptr-offset! (known-procedure 12)]
  [vector->cpointer (known-procedure 2)])
