
(define-primitive-table linklet-table
  [compile-linklet (known-procedure 62)]
  [compiled-position->primitive (known-procedure 2)]
  [eval-linklet (known-procedure 2)]
  [instance-data (known-procedure 2)]
  [instance-describe-variable! (known-procedure 8)]
  [instance-name (known-procedure 2)]
  [instance-set-variable-value! (known-procedure 24)]
  [instance-unset-variable! (known-procedure 4)]
  [instance-variable-names (known-procedure 2)]
  [instance-variable-value (known-procedure 12)]
  [instance? (known-procedure 2)]
  [instantiate-linklet (known-procedure 28)]
  [linklet-export-variables (known-procedure 2)]
  [linklet-import-variables (known-procedure 2)]
  [linklet? (known-procedure 2)]
  [make-instance (known-procedure -2)]
  [primitive->compiled-position (known-procedure 2)]
  [primitive-table (known-procedure 6)]
  [linklet-virtual-machine-bytes (known-procedure 1)]
  [read-linklet-bundle-hash (known-procedure 2)]
  [write-linklet-bundle-hash (known-procedure 2)]
  [recompile-linklet (known-procedure 30)]
  [variable-reference->instance (known-procedure 6)]
  [variable-reference-constant? (known-procedure 2)]
  [variable-reference-from-unsafe? (known-procedure 2)]
  [variable-reference? (known-procedure 2)])
