#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote rnrs/unicode-6))
(check-docs (quote rnrs/syntax-case-6))
(check-docs (quote rnrs/sorting-6))
(check-docs (quote rnrs/r5rs-6))
(check-docs (quote rnrs/programs-6))
(check-docs (quote rnrs/mutable-strings-6))
(check-docs (quote rnrs/mutable-pairs-6))
(check-docs (quote rnrs))
(check-docs (quote rnrs))
(check-docs (quote rnrs/lists-6))
(check-docs (quote rnrs/hashtables-6))
(check-docs (quote rnrs/files-6))
(check-docs (quote rnrs/exceptions-6))
(check-docs (quote rnrs/eval-6))
(check-docs (quote rnrs/enums-6))
(check-docs (quote rnrs/control-6))
(check-docs (quote rnrs/conditions-6))
(check-docs (quote rnrs/bytevectors-6))
(check-docs (quote rnrs/base-6))
