#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote mrlib/text-string-style-desc))
(check-docs (quote mrlib/tex-table))
(check-docs (quote mrlib/tab-choice))
(check-docs (quote mrlib/syntax-browser))
(check-docs (quote mrlib/switchable-button))
(check-docs (quote mrlib/plot))
(check-docs (quote mrlib/path-dialog))
(check-docs (quote mrlib/name-message))
(check-docs (quote mrlib/matrix-snip))
(check-docs (quote mrlib/interactive-value-port))
(check-docs (quote mrlib/include-bitmap))
(check-docs (quote mrlib/image-core))
(check-docs (quote mrlib/image-core-wxme))
(check-docs (quote mrlib/hierlist))
(check-docs (quote mrlib/graph))
(check-docs (quote mrlib/gif))
(check-docs (quote mrlib/close-icon))
(check-docs (quote mrlib/click-forwarding-editor))
(check-docs (quote mrlib/cache-image-snip))
(check-docs (quote mrlib/bitmap-label))
(check-docs (quote mrlib/aligned-pasteboard))
