(load-relative "loadtest.rktl")

(load-in-sandbox "kw.rktl")
(load-in-sandbox "awk.rktl")
(load-in-sandbox "etc.rktl")
(load-in-sandbox "compat.rktl")
(load-in-sandbox "unit.rktl")
(load-in-sandbox "unitsig.rktl")
(load-in-sandbox "string-mzlib.rktl")
(load-in-sandbox "threadlib.rktl")
(load-in-sandbox "serialize.rktl")
(load-in-sandbox "pconvert.rktl")
(load-in-sandbox "cmdline.rktl")
(load-in-sandbox "restart.rktl")
(load-in-sandbox "macrolib.rktl")
(load-in-sandbox "structlib.rktl")
(load-in-sandbox "contract-mzlib-test.rktl")
