;;; This file simply tests that all the SRFIs load.  Just
;;; load it into MzScheme to perform this test.  Remember it
;;; might not be up-to-date, so check before you run it!


(require (lib "1.ss" "srfi"))
(require (lib "2.ss" "srfi"))
(require (lib "4.ss" "srfi"))
(require (lib "5.ss" "srfi"))
(require (lib "7.ss" "srfi"))
(require (lib "8.ss" "srfi"))
(require (lib "9.ss" "srfi"))
(require (lib "13.ss" "srfi"))
(require (lib "14.ss" "srfi"))
(require (lib "17.ss" "srfi"))
(require (lib "19.ss" "srfi"))
(require (lib "25.ss" "srfi"))
(require (lib "26.ss" "srfi"))
(require (lib "27.ss" "srfi"))
(require (lib "29.ss" "srfi"))
(require (lib "31.ss" "srfi"))
(require (lib "32.ss" "srfi"))
(require (lib "34.ss" "srfi"))
(require (lib "35.ss" "srfi"))
(require (lib "35.ss" "srfi"))
(require (lib "40.ss" "srfi"))
(require (lib "42.ss" "srfi"))
(require (lib "43.ss" "srfi"))
(require (lib "45.ss" "srfi"))
(require (lib "48.ss" "srfi"))
(require (lib "54.ss" "srfi"))
(require (lib "57.ss" "srfi"))
(require (lib "59.ss" "srfi"))
(require (lib "60.ss" "srfi"))
(require (lib "61.ss" "srfi"))
(require (lib "63.ss" "srfi"))
(require (lib "64.ss" "srfi"))
(require (lib "66.ss" "srfi"))
(require (lib "67.ss" "srfi"))
(require (lib "69.ss" "srfi"))
(require (lib "71.ss" "srfi"))
(require (lib "74.ss" "srfi"))
(require (lib "78.ss" "srfi"))
(require (lib "86.ss" "srfi"))
(require (lib "87.ss" "srfi"))

(require (lib "list.ss" "srfi" "1"))
(require (lib "and-let.ss" "srfi" "2"))
(require (lib "let.ss" "srfi" "5"))
(require (lib "program.ss" "srfi" "7"))
(require (lib "receive.ss" "srfi" "8"))
(require (lib "record.ss" "srfi" "9"))
(require (lib "string.ss" "srfi" "13"))
(require (lib "char-set.ss" "srfi" "14"))
(require (lib "set.ss" "srfi" "17"))
(require (lib "time.ss" "srfi" "19"))
(require (lib "array.ss" "srfi" "25"))
(require (lib "cut.ss" "srfi" "26"))
(require (lib "random-bits.ss" "srfi" "27"))
(require (lib "localization.ss" "srfi" "29"))
(require (lib "rec.ss" "srfi" "31"))
(require (lib "sort.scm" "srfi" "32"))
(require (lib "exception.ss" "srfi" "34"))
(require (lib "condition.ss" "srfi" "35"))
(require (lib "stream.ss" "srfi" "40"))
(require (lib "comprehensions.ss" "srfi" "42"))
(require (lib "vector-lib.ss" "srfi" "43"))
(require (lib "lazy.ss" "srfi" "45"))
(require (lib "format.ss" "srfi" "48"))
(require (lib "records.ss" "srfi" "57"))
(require (lib "vicinity.ss" "srfi" "59"))
(require (lib "60.ss" "srfi" "60"))
(require (lib "cond.ss" "srfi" "61"))
(require (lib "63.ss" "srfi" "63"))
(require (lib "testing.ss" "srfi" "64"))
(require (lib "66.ss" "srfi" "66"))
(require (lib "compare.ss" "srfi" "67"))
(require (lib "hash.ss" "srfi" "69"))
(require (lib "letvalues.ss" "srfi" "71"))
(require (lib "74.ss" "srfi" "74"))
(require (lib "check.ss" "srfi" "78"))
(require (lib "86.ss" "srfi" "86"))
(require (lib "case.ss" "srfi" "87"))