(module info (lib "infotab.ss" "setup")
  (define name "Test Suite")
  (define tools '(("tool.ss")))
  (define tool-names (list "The Test Suite Tool"))
  (define tool-icons (list '("question-mark.png" "test-suite" "private" "icons"))))
