.\" dummy line
.TH RACO 1 "May 2010"
.UC 4
.SH NAME
raco \- the RAcket COmmand-line tool
.SH SYNOPSIS
.B raco
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
.B raco
performs various tasks related to the Racket language, such as finding documentation,
compiling Racket source to bytecode,
packaging executables, and packaging installable archives.

.PP
Run
.PP
   raco help
.PP
for a list of subcommands.

.SH MORE INFORMATION
For further information, run
.PP
   raco docs
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://racket-lang.org/

.SH AUTHOR
.B raco
was implemented by PLT.
.SH SEE ALSO
.BR racket(1),
.BR drracket(1)
