#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote slideshow/viewer))
(check-docs (quote slideshow/tutorial-show))
(check-docs (quote slideshow/tool))
(check-docs (quote slideshow/step))
(check-docs (quote slideshow/start))
(check-docs (quote slideshow/start-param))
(check-docs (quote slideshow/slideshow))
(check-docs (quote slideshow/slides-to-picts))
(check-docs (quote slideshow/slide))
(check-docs (quote slideshow/sig))
(check-docs (quote slideshow/run))
(check-docs (quote slideshow/play))
(check-docs (quote slideshow/pict))
(check-docs (quote slideshow/pict-snipclass))
(check-docs (quote slideshow/param))
(check-docs (quote slideshow))
(check-docs (quote slideshow/initial-ones))
(check-docs (quote slideshow/flash))
(check-docs (quote slideshow/face))
(check-docs (quote slideshow/core))
(check-docs (quote slideshow/code))
(check-docs (quote slideshow/cmdline))
(check-docs (quote slideshow/base))
(check-docs (quote slideshow/balloon))
