#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote guibuilder/utils))
(check-docs (quote guibuilder/top-level))
(check-docs (quote guibuilder/toolbar))
(check-docs (quote guibuilder/tool))
(check-docs (quote guibuilder/text-field))
(check-docs (quote guibuilder/slider-guage))
(check-docs (quote guibuilder/simple-control))
(check-docs (quote guibuilder/readable))
(check-docs (quote guibuilder/panel))
(check-docs (quote guibuilder/multiple-choice))
(check-docs (quote guibuilder/guibuilder))
(check-docs (quote guibuilder/feature))
(check-docs (quote guibuilder/canvas))
(check-docs (quote guibuilder/base))
