.\" dummy line
.TH MRED 1 "May 2010"
.UC 4
.SH NAME
mred \- compatibility executable for GRacket
.SH SYNOPSIS
.B mred
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
MrEd is the old name for the GUI Racket implementation.

.PP
For most cases, running
.B mred
is the same as running
.BR gracket ,
except that the default interaction language is slightly
different for backward compatibility.

.SH MORE INFORMATION
For further information, run
.PP
   raco docs
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://racket-lang.org/

.SH SEE ALSO
.BR gracket(1)
