#lang racket/base
(require ffi2
         rackunit)

(define-ffi2-type ours_t* void_t*)
(define-ffi2-type mine_t* ours_t*)

(define-ffi2-type ours_t** (array ours_t* *))
(define-ffi2-type mine_t** (array mine_t* *))

(define-ffi2-type also_ours_t* ours_t*
  #:tag #f)

(let ()
  (define p (ffi2-malloc #:manual 100))
  (check-true (void_t*? p))
  (check-false (void_t*/gcable? p))
  (check-false (ours_t*? p))
  (check-false (mine_t*? p))
  (check-true (ffi2-is-a? p void_t*))
  (check-true (ffi2-is-a? p (gcable void_t*))) ; does not check gcableness
  (check-true (ffi2-is-a? p void_t*/gcable)) ; does not check gcableness
  (check-false (ffi2-is-a? p ours_t*))
  (check-false (ffi2-is-a? p mine_t*))
  (ffi2-free p))

(let ()
  (define p (ffi2-malloc 100))
  (check-true (void_t*? p))
  (check-true (void_t*/gcable? p))
  (check-false (ours_t*? p))
  (check-false (mine_t*? p)))

(let ()
  (define op (ffi2-malloc #:manual 100 #:as ours_t*))
  (check-true (void_t*? op))
  (check-false (void_t*/gcable? op))
  (check-true (ours_t*? op))
  (check-true (also_ours_t*? op))
  (check-false (mine_t*? op))
  (check-true (ffi2-is-a? op void_t*))
  (check-true (ffi2-is-a? op ours_t*))
  (check-false (ffi2-is-a? op mine_t*))
  (ffi2-free op))

(let ()
  (define op (ffi2-malloc 100 #:bytes #:as ours_t*))
  (check-true (void_t*? op))
  (check-true (void_t*/gcable? op))
  (check-true (ours_t*? op))
  (check-false (mine_t*? op)))

(let ()
  (define mp (ffi2-malloc #:manual 100 #:as mine_t*))
  (check-true (void_t*? mp))
  (check-false (void_t*/gcable? mp))
  (check-true (ours_t*? mp))
  (check-true (mine_t*? mp))
  (check-false (ours_t**? mp))
  (check-false (mine_t**? mp))
  (check-true (ffi2-is-a? mp void_t*))
  (check-true (ffi2-is-a? mp ours_t*))
  (check-true (ffi2-is-a? mp mine_t*))
  (ffi2-free mp))

(let ()
  (define mp (ffi2-malloc 100 #:as mine_t*))
  (check-true (void_t*? mp))
  (check-true (ours_t*? mp))
  (check-true (mine_t*? mp)))

(let ()
  (define pp (ffi2-malloc ours_t*))
  (check-false (ours_t*? pp))
  (check-false (mine_t*? pp))
  (check-true (ours_t**? pp))
  (check-false (mine_t**? pp)))

(let ()
  (define pp (ffi2-malloc mine_t*))
  (check-false (ours_t*? pp))
  (check-false (mine_t*? pp))
  (check-false (ours_t**? pp))
  (check-true (mine_t**? pp)))

(let ()
  (define pp (ffi2-malloc #:gcable-traced ours_t*))
  (define p (ffi2-malloc 10 #:as ours_t*))
  (ffi2-set! pp ours_t* p)
  (define p2 (ffi2-ref pp (gcable ours_t*)))
  (collect-garbage)
  (check-equal? p p2)
  (check-true (void_t*? p2))
  (check-true (void_t*/gcable? p2))
  (check-true (ours_t*? p2))
  (define p3 (ffi2-ref pp (gcable mine_t*)))
  (check-equal? p p3)
  (check-true (void_t*? p3))
  (check-true (void_t*/gcable? p3))
  (check-true (ours_t*? p3)))

(let ()
  (define-ffi2-type int_t* (array int_t *))
  (check-true (ffi2-is-a? (ffi2-malloc int_t) (array int_t *)))
  (check-true (ffi2-is-a? (ffi2-malloc int_t) (gcable (array int_t *))))
  (define p (ffi2-malloc #:manual int_t))
  (check-true (ffi2-is-a? p (gcable (array int_t *))))
  (check-true (int_t*? p))
  (ffi2-free p)
  (check-true (ffi2-is-a? (ffi2-malloc int_t*) (array (gcable (array int_t *)) *)))
  (void))
