
(load-relative "loadtest.rktl")

(load-relative "core-tests.rktl")

(load-in-sandbox "setup.rktl")
(load-in-sandbox "for.rktl")
(load-in-sandbox "list.rktl")
(load-in-sandbox "math.rktl")
(load-in-sandbox "vector.rktl")
(load-in-sandbox "function.rktl")
(load-in-sandbox "dict.rktl")
(load-in-sandbox "fixnum.rktl")
(load-in-sandbox "flonum.rktl")

(load-in-sandbox "mpair.rktl")
(load-in-sandbox "async-channel.rktl")
(load-in-sandbox "pathlib.rktl")
(load-in-sandbox "filelib.rktl")
(load-in-sandbox "portlib.rktl")
(load-in-sandbox "set.rktl")
(load-in-sandbox "date.rktl")
(load-in-sandbox "cmdline.rktl")
(load-in-sandbox "stream.rktl")
(load-in-sandbox "sequence.rktl")
(load-in-sandbox "generator.rktl")
(load-in-sandbox "pretty.rktl")
(load-in-sandbox "control.rktl")
(load-in-sandbox "serialize.rktl")
(load-in-sandbox "package.rktl")
(load-in-sandbox "sandbox.rktl")
(load-in-sandbox "shared.rktl")
(load-in-sandbox "resource.rktl")
(load-in-sandbox "syntaxlibs.rktl")
(load-in-sandbox "subprocess.rktl")
(load-in-sandbox "char-set.rktl")
(load-in-sandbox "bytes.rktl")
(load-in-sandbox "trace.rktl")
(load-in-sandbox "trait.rktl")

(load-in-sandbox "moddep.rktl")
(load-in-sandbox "boundmap-test.rktl")
(load-in-sandbox "id-table-test.rktl")
(load-in-sandbox "cm.rktl")
(load-in-sandbox "module-reader.rktl")

(load-in-sandbox "version.rktl")
(load-in-sandbox "foreign-test.rktl")
(load-in-sandbox "cstruct.rktl")
(load-in-sandbox "uni-norm.rktl")
