;; SRFI Tests

(load-relative "loadtest.rktl")

;; Test that all SRFIs load.  Run this in both DrRacket and
;; Racket for maximum coverage.

;; We just require all the SRFIs and hope nothing bombs.
;; Keep an eye out for error messages!

(require srfi/1)
(require srfi/1/list)
(require srfi/2/and-let)
(require srfi/4)
(require srfi/5/let)
(require srfi/6)
(require srfi/7/program)
(require srfi/8/receive)
(require srfi/9/record)
(require srfi/11)
(require srfi/13/string)
(require srfi/14/char-set)
(require srfi/16)
(require srfi/17/set)
(require srfi/18)
(require srfi/19/time)
(require srfi/23)
(require srfi/25/array)
(require srfi/26/cut)
(require srfi/27/random-bits)
(require srfi/28)
(require srfi/29/localization)
(require srfi/30)
(require srfi/31/rec)
(require srfi/32/sort)
(require srfi/34/exception)
(require srfi/35)
(require srfi/35/condition)
(require srfi/38)
(require srfi/39)
(require srfi/40/stream)
(require (lib "srfi/42/comprehensions.scm"))
(require srfi/43/vector-lib)
(require srfi/45/lazy)
(require srfi/48/format)
(require srfi/54/cat)
(require srfi/57/records)
(require srfi/59/vicinity)
(require srfi/60/60)
(require srfi/61)
(require srfi/63)
(require srfi/64)
(require srfi/64/testing)
(require srfi/66)
(require srfi/67/compare)
(require srfi/69/hash)
(require srfi/71/letvalues)
(require srfi/74/74)
(require srfi/78/check)
(require srfi/86)
(require srfi/87/case)
