# Makefile for Independent JPEG Group's software

# makefile.cfg is edited by configure to produce a custom Makefile.

# Read installation instructions before saying "make" !!

# For compiling with source and object files in different directories.
srcdir = @srcdir@
VPATH = @srcdir@

# Where to install the programs and man pages.
prefix = @prefix@
exec_prefix = @exec_prefix@
bindir = $(exec_prefix)/bin
libdir = $(exec_prefix)/lib
includedir = $(prefix)/include
binprefix =
manprefix =
manext = 1
mandir = $(prefix)/man/man$(manext)

# The name of your C compiler:
CC= @CC@

# You may need to adjust these cc options:
CFLAGS= @CFLAGS@ @CPPFLAGS@ @INCLUDEFLAGS@
# Generally, we recommend defining any configuration symbols in jconfig.h,
# NOT via -D switches here.
# However, any special defines for ansi2knr.c may be included here:
ANSI2KNRFLAGS= @ANSI2KNRFLAGS@

# Link-time cc options:
LDFLAGS= @LDFLAGS@

# To link any special libraries, add the necessary -l commands here.
LDLIBS= @LIBS@

# If using GNU libtool, LIBTOOL references it; if not, LIBTOOL is empty.
LIBTOOL = @LIBTOOL@
# $(O) expands to "lo" if using libtool, plain "o" if not.
# Similarly, $(A) expands to "la" or "a".
O = @O@
A = @A@

# Library version ID; libtool uses this for the shared library version number.
# Note: we suggest this match the macro of the same name in jpeglib.h.
JPEG_LIB_VERSION = @JPEG_LIB_VERSION@

# Put here the object file name for the correct system-dependent memory
# manager file.  For Unix this is usually jmemnobs.o, but you may want
# to use jmemansi.o or jmemname.o if you have limited swap space.
SYSDEPMEM= @MEMORYMGR@

# miscellaneous OS-dependent stuff
SHELL= /bin/sh
# linker
LN= @LN@
# file deletion command
RM= rm -f
# directory creation command
MKDIR= mkdir
# library (.a) file creation command
AR= ar rc
# second step in .a creation (use "touch" if not needed)
AR2= @RANLIB@
# installation program
INSTALL= @INSTALL@
INSTALL_PROGRAM= @INSTALL_PROGRAM@
INSTALL_LIB= @INSTALL_LIB@
INSTALL_DATA= @INSTALL_DATA@

# End of configurable options.


# source files: JPEG library proper
LIBSOURCES= jcapimin.c jcapistd.c jccoefct.c jccolor.c jcdctmgr.c jchuff.c \
        jcinit.c jcmainct.c jcmarker.c jcmaster.c jcomapi.c jcparam.c \
        jcphuff.c jcprepct.c jcsample.c jctrans.c jdapimin.c jdapistd.c \
        jdatadst.c jdatasrc.c jdcoefct.c jdcolor.c jddctmgr.c jdhuff.c \
        jdinput.c jdmainct.c jdmarker.c jdmaster.c jdmerge.c jdphuff.c \
        jdpostct.c jdsample.c jdtrans.c jerror.c jfdctflt.c jfdctfst.c \
        jfdctint.c jidctflt.c jidctfst.c jidctint.c jidctred.c jquant1.c \
        jquant2.c jutils.c jmemmgr.c
# memmgr back ends: compile only one of these into a working library
SYSDEPSOURCES= jmemansi.c jmemname.c jmemnobs.c jmemdos.c jmemmac.c
# source files: cjpeg/djpeg/jpegtran applications, also rdjpgcom/wrjpgcom
APPSOURCES= cjpeg.c djpeg.c jpegtran.c rdjpgcom.c wrjpgcom.c cdjpeg.c \
        rdcolmap.c rdswitch.c transupp.c rdppm.c wrppm.c rdgif.c wrgif.c \
        rdtarga.c wrtarga.c rdbmp.c wrbmp.c rdrle.c wrrle.c
SOURCES= $(LIBSOURCES) $(SYSDEPSOURCES) $(APPSOURCES)
# files included by source files
INCLUDES= jchuff.h jdhuff.h jdct.h jerror.h jinclude.h jmemsys.h jmorecfg.h \
        jpegint.h jpeglib.h jversion.h cdjpeg.h cderror.h transupp.h
# documentation, test, and support files
DOCS= README install.doc usage.doc cjpeg.1 djpeg.1 jpegtran.1 rdjpgcom.1 \
        wrjpgcom.1 wizard.doc example.c libjpeg.doc structure.doc \
        coderules.doc filelist.doc change.log
MKFILES= configure makefile.cfg makefile.ansi makefile.unix makefile.bcc \
        makefile.mc6 makefile.dj makefile.wat makefile.vc makelib.ds \
        makeapps.ds makeproj.mac makcjpeg.st makdjpeg.st makljpeg.st \
        maktjpeg.st makefile.manx makefile.sas makefile.mms makefile.vms \
        makvms.opt
CONFIGFILES= jconfig.cfg jconfig.bcc jconfig.mc6 jconfig.dj jconfig.wat \
        jconfig.vc jconfig.mac jconfig.st jconfig.manx jconfig.sas \
        jconfig.vms
CONFIGUREFILES= config.guess config.sub install-sh ltconfig ltmain.sh
OTHERFILES= jconfig.doc ckconfig.c ansi2knr.c ansi2knr.1 jmemdosa.asm
TESTFILES= testorig.jpg testimg.ppm testimg.bmp testimg.jpg testprog.jpg \
        testimgp.jpg
DISTFILES= $(DOCS) $(MKFILES) $(CONFIGFILES) $(SOURCES) $(INCLUDES) \
        $(CONFIGUREFILES) $(OTHERFILES) $(TESTFILES)
# library object files common to compression and decompression
COMOBJECTS= jcomapi.$(O) jutils.$(O) jerror.$(O) jmemmgr.$(O) $(SYSDEPMEM)
# compression library object files
CLIBOBJECTS= jcapimin.$(O) jcapistd.$(O) jctrans.$(O) jcparam.$(O) \
        jdatadst.$(O) jcinit.$(O) jcmaster.$(O) jcmarker.$(O) jcmainct.$(O) \
        jcprepct.$(O) jccoefct.$(O) jccolor.$(O) jcsample.$(O) jchuff.$(O) \
        jcphuff.$(O) jcdctmgr.$(O) jfdctfst.$(O) jfdctflt.$(O) \
        jfdctint.$(O)
# decompression library object files
DLIBOBJECTS= jdapimin.$(O) jdapistd.$(O) jdtrans.$(O) jdatasrc.$(O) \
        jdmaster.$(O) jdinput.$(O) jdmarker.$(O) jdhuff.$(O) jdphuff.$(O) \
        jdmainct.$(O) jdcoefct.$(O) jdpostct.$(O) jddctmgr.$(O) \
        jidctfst.$(O) jidctflt.$(O) jidctint.$(O) jidctred.$(O) \
        jdsample.$(O) jdcolor.$(O) jquant1.$(O) jquant2.$(O) jdmerge.$(O)
# These objectfiles are included in libjpeg.a
LIBOBJECTS= $(CLIBOBJECTS) $(DLIBOBJECTS) $(COMOBJECTS)
# object files for sample applications (excluding library files)
COBJECTS= cjpeg.$(O) rdppm.$(O) rdgif.$(O) rdtarga.$(O) rdrle.$(O) \
        rdbmp.$(O) rdswitch.$(O) cdjpeg.$(O)
DOBJECTS= djpeg.$(O) wrppm.$(O) wrgif.$(O) wrtarga.$(O) wrrle.$(O) \
        wrbmp.$(O) rdcolmap.$(O) cdjpeg.$(O)
TROBJECTS= jpegtran.$(O) rdswitch.$(O) cdjpeg.$(O) transupp.$(O)


all: @A2K_DEPS@ libjpeg.$(A) cjpeg djpeg jpegtran rdjpgcom wrjpgcom

# Special compilation rules to support ansi2knr and libtool.
.SUFFIXES: .lo .la

# How to compile with libtool.
@COM_LT@.c.lo:
@COM_LT@	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) -c $(srcdir)/$*.c

# How to use ansi2knr, when not using libtool.
@COM_A2K@.c.o:
@COM_A2K@	./ansi2knr $(srcdir)/$*.c knr/$*.c
@COM_A2K@	$(CC) $(CFLAGS) -c knr/$*.c
@COM_A2K@	$(RM) knr/$*.c

# How to use ansi2knr AND libtool.
@COM_A2K@.c.lo:
@COM_A2K@	./ansi2knr $(srcdir)/$*.c knr/$*.c
@COM_A2K@	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) -c knr/$*.c
@COM_A2K@	$(RM) knr/$*.c

ansi2knr: ansi2knr.c
	$(CC) $(CFLAGS) $(ANSI2KNRFLAGS) -o ansi2knr $(srcdir)/ansi2knr.c
	$(MKDIR) knr

# the library:

# without libtool:
libjpeg.$(A): @A2K_DEPS@ $(LIBOBJECTS)
	$(RM) libjpeg.$(A)
	$(AR) libjpeg.$(A)  $(LIBOBJECTS)
	$(AR2) libjpeg.$(A)

# with libtool:
xxx-libjpeg.la: @A2K_DEPS@ $(LIBOBJECTS)
	$(LIBTOOL) --mode=link $(CC) -o libjpeg.la $(LIBOBJECTS) \
		-rpath $(libdir) -version-info $(JPEG_LIB_VERSION)

# sample programs:

cjpeg: $(COBJECTS) libjpeg.$(A)
	$(LN) $(LDFLAGS) -o cjpeg $(COBJECTS) libjpeg.$(A) $(LDLIBS)

djpeg: $(DOBJECTS) libjpeg.$(A)
	$(LN) $(LDFLAGS) -o djpeg $(DOBJECTS) libjpeg.$(A) $(LDLIBS)

jpegtran: $(TROBJECTS) libjpeg.$(A)
	$(LN) $(LDFLAGS) -o jpegtran $(TROBJECTS) libjpeg.$(A) $(LDLIBS)

rdjpgcom: rdjpgcom.$(O)
	$(LN) $(LDFLAGS) -o rdjpgcom rdjpgcom.$(O) $(LDLIBS)

wrjpgcom: wrjpgcom.$(O)
	$(LN) $(LDFLAGS) -o wrjpgcom wrjpgcom.$(O) $(LDLIBS)

# Installation rules:

install: cjpeg djpeg jpegtran rdjpgcom wrjpgcom @FORCE_INSTALL_LIB@
	$(INSTALL_PROGRAM) cjpeg $(bindir)/$(binprefix)cjpeg
	$(INSTALL_PROGRAM) djpeg $(bindir)/$(binprefix)djpeg
	$(INSTALL_PROGRAM) jpegtran $(bindir)/$(binprefix)jpegtran
	$(INSTALL_PROGRAM) rdjpgcom $(bindir)/$(binprefix)rdjpgcom
	$(INSTALL_PROGRAM) wrjpgcom $(bindir)/$(binprefix)wrjpgcom
	$(INSTALL_DATA) $(srcdir)/cjpeg.1 $(mandir)/$(manprefix)cjpeg.$(manext)
	$(INSTALL_DATA) $(srcdir)/djpeg.1 $(mandir)/$(manprefix)djpeg.$(manext)
	$(INSTALL_DATA) $(srcdir)/jpegtran.1 $(mandir)/$(manprefix)jpegtran.$(manext)
	$(INSTALL_DATA) $(srcdir)/rdjpgcom.1 $(mandir)/$(manprefix)rdjpgcom.$(manext)
	$(INSTALL_DATA) $(srcdir)/wrjpgcom.1 $(mandir)/$(manprefix)wrjpgcom.$(manext)

install-lib: libjpeg.$(A) install-headers
	$(INSTALL_LIB) libjpeg.$(A) $(libdir)/$(binprefix)libjpeg.$(A)

install-headers: jconfig.h
	$(INSTALL_DATA) jconfig.h $(includedir)/jconfig.h
	$(INSTALL_DATA) $(srcdir)/jpeglib.h $(includedir)/jpeglib.h
	$(INSTALL_DATA) $(srcdir)/jmorecfg.h $(includedir)/jmorecfg.h
	$(INSTALL_DATA) $(srcdir)/jerror.h $(includedir)/jerror.h

clean:
	$(RM) *.o *.lo libjpeg.a libjpeg.la
	$(RM) cjpeg djpeg jpegtran rdjpgcom wrjpgcom
	$(RM) ansi2knr core testout* config.log config.status
	$(RM) -r knr .libs _libs

distclean: clean
	$(RM) Makefile jconfig.h libtool config.cache

test: cjpeg djpeg jpegtran
	$(RM) testout*
	./djpeg -dct int -ppm -outfile testout.ppm  $(srcdir)/testorig.jpg
	./djpeg -dct int -bmp -colors 256 -outfile testout.bmp  $(srcdir)/testorig.jpg
	./cjpeg -dct int -outfile testout.jpg  $(srcdir)/testimg.ppm
	./djpeg -dct int -ppm -outfile testoutp.ppm $(srcdir)/testprog.jpg
	./cjpeg -dct int -progressive -opt -outfile testoutp.jpg $(srcdir)/testimg.ppm
	./jpegtran -outfile testoutt.jpg $(srcdir)/testprog.jpg
	cmp $(srcdir)/testimg.ppm testout.ppm
	cmp $(srcdir)/testimg.bmp testout.bmp
	cmp $(srcdir)/testimg.jpg testout.jpg
	cmp $(srcdir)/testimg.ppm testoutp.ppm
	cmp $(srcdir)/testimgp.jpg testoutp.jpg
	cmp $(srcdir)/testorig.jpg testoutt.jpg

check: test

# Mistake catcher:

jconfig.h: jconfig.doc
	echo You must prepare a system-dependent jconfig.h file.
	echo Please read the installation directions in install.doc.
	exit 1

# GNU Make likes to know which target names are not really files to be made:
.PHONY: all install install-lib install-headers clean distclean test check


jcapimin.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcapistd.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jccoefct.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jccolor.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcdctmgr.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jchuff.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jchuff.h
jcinit.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcmainct.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcmarker.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcmaster.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcomapi.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcparam.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcphuff.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jchuff.h
jcprepct.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jcsample.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jctrans.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdapimin.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdapistd.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdatadst.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h
jdatasrc.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h
jdcoefct.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdcolor.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jddctmgr.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jdhuff.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdhuff.h
jdinput.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdmainct.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdmarker.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdmaster.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdmerge.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdphuff.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdhuff.h
jdpostct.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdsample.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jdtrans.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jerror.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jversion.h $(srcdir)/jerror.h
jfdctflt.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jfdctfst.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jfdctint.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jidctflt.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jidctfst.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jidctint.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jidctred.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jdct.h
jquant1.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jquant2.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jutils.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h
jmemmgr.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jmemsys.h
jmemansi.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jmemsys.h
jmemname.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jmemsys.h
jmemnobs.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jmemsys.h
jmemdos.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jmemsys.h
jmemmac.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/jmemsys.h
cjpeg.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h $(srcdir)/jversion.h
djpeg.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h $(srcdir)/jversion.h
jpegtran.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h $(srcdir)/transupp.h $(srcdir)/jversion.h
rdjpgcom.$(O): $(srcdir)/jinclude.h jconfig.h
wrjpgcom.$(O): $(srcdir)/jinclude.h jconfig.h
cdjpeg.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
rdcolmap.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
rdswitch.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
transupp.$(O): $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jpegint.h $(srcdir)/jerror.h $(srcdir)/transupp.h
rdppm.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
wrppm.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
rdgif.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
wrgif.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
rdtarga.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
wrtarga.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
rdbmp.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
wrbmp.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
rdrle.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h
wrrle.$(O): $(srcdir)/cdjpeg.h $(srcdir)/jinclude.h jconfig.h $(srcdir)/jpeglib.h $(srcdir)/jmorecfg.h $(srcdir)/jerror.h $(srcdir)/cderror.h


jcapimin.$(O): $(srcdir)/jcapimin.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcapimin.c
jcapistd.$(O): $(srcdir)/jcapistd.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcapistd.c
jccoefct.$(O): $(srcdir)/jccoefct.c
	$(CC) $(CFLAGS) -c $(srcdir)/jccoefct.c
jccolor.$(O): $(srcdir)/jccolor.c
	$(CC) $(CFLAGS) -c $(srcdir)/jccolor.c
jcdctmgr.$(O): $(srcdir)/jcdctmgr.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcdctmgr.c
jchuff.$(O): $(srcdir)/jchuff.c
	$(CC) $(CFLAGS) -c $(srcdir)/jchuff.c
jcinit.$(O): $(srcdir)/jcinit.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcinit.c
jcmainct.$(O): $(srcdir)/jcmainct.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcmainct.c
jcmarker.$(O): $(srcdir)/jcmarker.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcmarker.c
jcmaster.$(O): $(srcdir)/jcmaster.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcmaster.c
jcomapi.$(O): $(srcdir)/jcomapi.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcomapi.c
jcparam.$(O): $(srcdir)/jcparam.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcparam.c
jcphuff.$(O): $(srcdir)/jcphuff.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcphuff.c
jcprepct.$(O): $(srcdir)/jcprepct.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcprepct.c
jcsample.$(O): $(srcdir)/jcsample.c
	$(CC) $(CFLAGS) -c $(srcdir)/jcsample.c
jctrans.$(O): $(srcdir)/jctrans.c
	$(CC) $(CFLAGS) -c $(srcdir)/jctrans.c
jdapimin.$(O): $(srcdir)/jdapimin.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdapimin.c
jdapistd.$(O): $(srcdir)/jdapistd.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdapistd.c
jdatadst.$(O): $(srcdir)/jdatadst.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdatadst.c
jdatasrc.$(O): $(srcdir)/jdatasrc.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdatasrc.c
jdcoefct.$(O): $(srcdir)/jdcoefct.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdcoefct.c
jdcolor.$(O): $(srcdir)/jdcolor.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdcolor.c
jddctmgr.$(O): $(srcdir)/jddctmgr.c
	$(CC) $(CFLAGS) -c $(srcdir)/jddctmgr.c
jdhuff.$(O): $(srcdir)/jdhuff.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdhuff.c
jdinput.$(O): $(srcdir)/jdinput.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdinput.c
jdmainct.$(O): $(srcdir)/jdmainct.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdmainct.c
jdmarker.$(O): $(srcdir)/jdmarker.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdmarker.c
jdmaster.$(O): $(srcdir)/jdmaster.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdmaster.c
jdmerge.$(O): $(srcdir)/jdmerge.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdmerge.c
jdphuff.$(O): $(srcdir)/jdphuff.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdphuff.c
jdpostct.$(O): $(srcdir)/jdpostct.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdpostct.c
jdsample.$(O): $(srcdir)/jdsample.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdsample.c
jdtrans.$(O): $(srcdir)/jdtrans.c
	$(CC) $(CFLAGS) -c $(srcdir)/jdtrans.c
jerror.$(O): $(srcdir)/jerror.c
	$(CC) $(CFLAGS) -c $(srcdir)/jerror.c
jfdctflt.$(O): $(srcdir)/jfdctflt.c
	$(CC) $(CFLAGS) -c $(srcdir)/jfdctflt.c
jfdctfst.$(O): $(srcdir)/jfdctfst.c
	$(CC) $(CFLAGS) -c $(srcdir)/jfdctfst.c
jfdctint.$(O): $(srcdir)/jfdctint.c
	$(CC) $(CFLAGS) -c $(srcdir)/jfdctint.c
jidctflt.$(O): $(srcdir)/jidctflt.c
	$(CC) $(CFLAGS) -c $(srcdir)/jidctflt.c
jidctfst.$(O): $(srcdir)/jidctfst.c
	$(CC) $(CFLAGS) -c $(srcdir)/jidctfst.c
jidctint.$(O): $(srcdir)/jidctint.c
	$(CC) $(CFLAGS) -c $(srcdir)/jidctint.c
jidctred.$(O): $(srcdir)/jidctred.c
	$(CC) $(CFLAGS) -c $(srcdir)/jidctred.c
jquant1.$(O): $(srcdir)/jquant1.c
	$(CC) $(CFLAGS) -c $(srcdir)/jquant1.c
jquant2.$(O): $(srcdir)/jquant2.c
	$(CC) $(CFLAGS) -c $(srcdir)/jquant2.c
jutils.$(O): $(srcdir)/jutils.c
	$(CC) $(CFLAGS) -c $(srcdir)/jutils.c
jmemmgr.$(O): $(srcdir)/jmemmgr.c
	$(CC) $(CFLAGS) -c $(srcdir)/jmemmgr.c
jmemansi.$(O): $(srcdir)/jmemansi.c
	$(CC) $(CFLAGS) -c $(srcdir)/jmemansi.c
jmemname.$(O): $(srcdir)/jmemname.c
	$(CC) $(CFLAGS) -c $(srcdir)/jmemname.c
jmemnobs.$(O): $(srcdir)/jmemnobs.c
	$(CC) $(CFLAGS) -c $(srcdir)/jmemnobs.c
jmemdos.$(O): $(srcdir)/jmemdos.c
	$(CC) $(CFLAGS) -c $(srcdir)/jmemdos.c
jmemmac.$(O): $(srcdir)/jmemmac.c
	$(CC) $(CFLAGS) -c $(srcdir)/jmemmac.c
cjpeg.$(O): $(srcdir)/cjpeg.c
	$(CC) $(CFLAGS) -c $(srcdir)/cjpeg.c
djpeg.$(O): $(srcdir)/djpeg.c
	$(CC) $(CFLAGS) -c $(srcdir)/djpeg.c
jpegtran.$(O): $(srcdir)/jpegtran.c
	$(CC) $(CFLAGS) -c $(srcdir)/jpegtran.c
rdjpgcom.$(O): $(srcdir)/rdjpgcom.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdjpgcom.c
wrjpgcom.$(O): $(srcdir)/wrjpgcom.c
	$(CC) $(CFLAGS) -c $(srcdir)/wrjpgcom.c
cdjpeg.$(O): $(srcdir)/cdjpeg.c
	$(CC) $(CFLAGS) -c $(srcdir)/cdjpeg.c
rdcolmap.$(O): $(srcdir)/rdcolmap.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdcolmap.c
rdswitch.$(O): $(srcdir)/rdswitch.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdswitch.c
transupp.$(O): $(srcdir)/transupp.c
	$(CC) $(CFLAGS) -c $(srcdir)/transupp.c
rdppm.$(O): $(srcdir)/rdppm.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdppm.c
wrppm.$(O): $(srcdir)/wrppm.c
	$(CC) $(CFLAGS) -c $(srcdir)/wrppm.c
rdgif.$(O): $(srcdir)/rdgif.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdgif.c
wrgif.$(O): $(srcdir)/wrgif.c
	$(CC) $(CFLAGS) -c $(srcdir)/wrgif.c
rdtarga.$(O): $(srcdir)/rdtarga.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdtarga.c
wrtarga.$(O): $(srcdir)/wrtarga.c
	$(CC) $(CFLAGS) -c $(srcdir)/wrtarga.c
rdbmp.$(O): $(srcdir)/rdbmp.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdbmp.c
wrbmp.$(O): $(srcdir)/wrbmp.c
	$(CC) $(CFLAGS) -c $(srcdir)/wrbmp.c
rdrle.$(O): $(srcdir)/rdrle.c
	$(CC) $(CFLAGS) -c $(srcdir)/rdrle.c
wrrle.$(O): $(srcdir)/wrrle.c
	$(CC) $(CFLAGS) -c $(srcdir)/wrrle.c

