(module info (lib "infotab.ss" "setup")
  (define name "Debugger")
  (define tools '(("debugger-tool.ss")))
  (define tool-names '("The Debugger"))
  (define tool-icons '(("emblem-ohno.png" "mztake")))
)
