(module info (lib "infotab.ss" "setup")
  (define name "Debugger")
  (define tools '(("mztake-lang.ss") ("debug-tool.ss")))
  (define blurb '("MzTake is a scripted debugger for PLT Scheme." "A debugging tool for DrScheme"))
  (define tool-names '("MzTake Debugger" "Skipper"))
  (define tool-icons '(("emblem-ohno.png" "mztake" "icons") ("icon-big.png" "mztake" "icons")))
)
