#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote frtime/struct))
(check-docs (quote frtime/reactive))
(check-docs (quote frtime))
(check-docs (quote frtime/gui))
(check-docs (quote frtime/frtime))
(check-docs (quote frtime/frtime-big))
(check-docs (quote frtime/frp-snip))
(check-docs (quote frtime/animation))
