/* Generated by wbuild
 * (generator version 3.2)
 */
#ifndef ___XWFRAMEP_H
#define ___XWFRAMEP_H
#include <./xwCommonP.h>
#include <./xwFrame.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfFrameClassPart;

typedef struct _XfwfFrameClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
} XfwfFrameClassRec;

typedef struct {
/* resources */
Cursor  cursor;
FrameType  frameType;
Dimension  frameWidth;
Dimension  outerOffset;
Dimension  innerOffset;
ShadowScheme  shadowScheme;
Pixel  topShadowColor;
Pixel  bottomShadowColor;
Bitmap  topShadowStipple;
Bitmap  bottomShadowStipple;
/* private state */
GC  lightgc;
GC  darkgc;
GC  fggc;
Pixmap  gray;
Pixmap  darkGray;
Pixmap  lightGray;
FrameType  old_frame_type;
} XfwfFramePart;

typedef struct _XfwfFrameRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
} XfwfFrameRec;

externalref XfwfFrameClassRec xfwfFrameClassRec;

_XFUNCPROTOEND
#endif /* ___XWFRAMEP_H */
