#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote texpict/utils))
(check-docs (quote texpict/texpict))
(check-docs (quote texpict/texpict-unit))
(check-docs (quote texpict/texpict-sig))
(check-docs (quote texpict/symbol))
(check-docs (quote texpict/slideshow))
(check-docs (quote texpict/slideshow-run))
(check-docs (quote texpict/pict-value-snip))
(check-docs (quote texpict/mrpict))
(check-docs (quote texpict/mrpict-unit))
(check-docs (quote texpict/mrpict-sig))
(check-docs (quote texpict/flash))
(check-docs (quote texpict/face))
(check-docs (quote texpict/face-demo))
(check-docs (quote texpict/code))
(check-docs (quote texpict/balloon))
