#ifndef WXS_SETUP_ONLY
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxImageSnip *objscheme_unbundle_wxImageSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamIn(class wxMediaStreamIn *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamIn(class wxMediaStreamIn *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxBufferData(class wxBufferData *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxBufferData *objscheme_unbundle_wxBufferData(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxColour(class wxColour *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxCursor *objscheme_unbundle_wxCursor(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern Scheme_Object *objscheme_bundle_wxMediaBuffer(class wxMediaBuffer *);
extern class wxMediaBuffer *objscheme_unbundle_wxMediaBuffer(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxStyleDelta(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxStyleDelta *objscheme_unbundle_wxStyleDelta(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxStyleDelta(Scheme_Object *, const char *, int);
extern class wxStyleDelta *objscheme_unbundle_wxStyleDelta(Scheme_Object *, const char *, int);
extern class wxStyle *objscheme_unbundle_wxStyle(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxImageSnip(class wxImageSnip *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxMediaStreamIn *objscheme_unbundle_wxMediaStreamIn(Scheme_Object *, const char *, int);
extern class wxMediaStreamIn *objscheme_unbundle_wxMediaStreamIn(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxMediaStreamIn *objscheme_unbundle_wxMediaStreamIn(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxBufferData *objscheme_unbundle_wxBufferData(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxBufferData(class wxBufferData *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxColour *objscheme_unbundle_wxColour(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxCursor(class wxCursor *);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern class wxMediaBuffer *objscheme_unbundle_wxMediaBuffer(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxMediaBuffer(class wxMediaBuffer *);
#endif
void objscheme_setup_wxMediaPasteboard(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxMediaPasteboard(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxMediaPasteboard(class wxMediaPasteboard *realobj);
class wxMediaPasteboard *objscheme_unbundle_wxMediaPasteboard(Scheme_Object *obj, const char *where, int nullOK);
#endif
