#ifndef WXS_SETUP_ONLY
extern Scheme_Object *objscheme_bundle_wxSnipAdmin(class wxSnipAdmin *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxCursor *objscheme_unbundle_wxCursor(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnipAdmin *objscheme_unbundle_wxSnipAdmin(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxCursor(class wxCursor *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxStyle *objscheme_unbundle_wxStyle(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnipAdmin(class wxSnipAdmin *);
extern Scheme_Object *objscheme_bundle_wxStyle(class wxStyle *);
extern Scheme_Object *objscheme_bundle_wxSnipClass(class wxSnipClass *);
extern class wxSnipClass *objscheme_unbundle_wxSnipClass(Scheme_Object *, const char *, int);
#endif
void objscheme_setup_wxSnip(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxSnip(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *realobj);
class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxSnipAdmin(class wxSnipAdmin *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxCursor *objscheme_unbundle_wxCursor(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern class wxMediaStreamIn *objscheme_unbundle_wxMediaStreamIn(Scheme_Object *, const char *, int);
extern class wxSnipAdmin *objscheme_unbundle_wxSnipAdmin(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxCursor(class wxCursor *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
#endif
void objscheme_setup_wxTextSnip(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxTextSnip(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxTextSnip(class wxTextSnip *realobj);
class wxTextSnip *objscheme_unbundle_wxTextSnip(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxSnipAdmin(class wxSnipAdmin *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxCursor *objscheme_unbundle_wxCursor(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern class wxSnipAdmin *objscheme_unbundle_wxSnipAdmin(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxCursor(class wxCursor *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
#endif
void objscheme_setup_wxTabSnip(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxTabSnip(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxTabSnip(class wxTabSnip *realobj);
class wxTabSnip *objscheme_unbundle_wxTabSnip(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxSnipAdmin(class wxSnipAdmin *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxCursor *objscheme_unbundle_wxCursor(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxBitmap(class wxBitmap *);
extern Scheme_Object *objscheme_bundle_wxBitmap(class wxBitmap *);
extern class wxBitmap *objscheme_unbundle_wxBitmap(Scheme_Object *, const char *, int);
extern class wxBitmap *objscheme_unbundle_wxBitmap(Scheme_Object *, const char *, int);
extern class wxSnipAdmin *objscheme_unbundle_wxSnipAdmin(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxCursor(class wxCursor *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern int objscheme_istype_wxBitmap(Scheme_Object *, const char *, int);
extern class wxBitmap *objscheme_unbundle_wxBitmap(Scheme_Object *, const char *, int);
extern class wxBitmap *objscheme_unbundle_wxBitmap(Scheme_Object *, const char *, int);
#endif
void objscheme_setup_wxImageSnip(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxImageSnip(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxImageSnip(class wxImageSnip *realobj);
class wxImageSnip *objscheme_unbundle_wxImageSnip(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxSnipAdmin(class wxSnipAdmin *);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxCursor *objscheme_unbundle_wxCursor(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern Scheme_Object *objscheme_bundle_wxDC(class wxDC *);
extern class wxSnipAdmin *objscheme_unbundle_wxSnipAdmin(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxCursor(class wxCursor *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern class wxSnip *objscheme_unbundle_wxSnip(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern Scheme_Object *objscheme_bundle_wxSnip(class wxSnip *);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxDC *objscheme_unbundle_wxDC(Scheme_Object *, const char *, int);
extern class wxMediaBuffer *objscheme_unbundle_wxMediaBuffer(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxMediaBuffer(class wxMediaBuffer *);
extern class wxMediaBuffer *objscheme_unbundle_wxMediaBuffer(Scheme_Object *, const char *, int);
#endif
void objscheme_setup_wxMediaSnip(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxMediaSnip(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxMediaSnip(class wxMediaSnip *realobj);
class wxMediaSnip *objscheme_unbundle_wxMediaSnip(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxMediaStreamIn(class wxMediaStreamIn *);
extern class wxBufferData *objscheme_unbundle_wxBufferData(Scheme_Object *, const char *, int);
extern class wxMediaStreamIn *objscheme_unbundle_wxMediaStreamIn(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxBufferData(class wxBufferData *);
#endif
void objscheme_setup_wxBufferDataClass(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxBufferDataClass(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxBufferDataClass(class wxBufferDataClass *realobj);
class wxBufferDataClass *objscheme_unbundle_wxBufferDataClass(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxBufferDataClass(class wxBufferDataClass *);
extern class wxBufferDataClass *objscheme_unbundle_wxBufferDataClass(Scheme_Object *, const char *, int);
extern class wxBufferDataClass *objscheme_unbundle_wxBufferDataClass(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxBufferDataClass(class wxBufferDataClass *);
#endif
void objscheme_setup_wxBufferDataClassList(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxBufferDataClassList(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxBufferDataClassList(class wxBufferDataClassList *realobj);
class wxBufferDataClassList *objscheme_unbundle_wxBufferDataClassList(Scheme_Object *obj, const char *where, int nullOK);
extern Scheme_Object *objscheme_bundle_wxMediaStreamOut(class wxMediaStreamOut *);
extern class wxBufferData *objscheme_unbundle_wxBufferData(Scheme_Object *, const char *, int);
extern class wxMediaStreamOut *objscheme_unbundle_wxMediaStreamOut(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxBufferDataClass(class wxBufferDataClass *);
extern class wxBufferDataClass *objscheme_unbundle_wxBufferDataClass(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxBufferData(class wxBufferData *);
#endif
void objscheme_setup_wxBufferData(Scheme_Env *env);
#ifndef WXS_SETUP_ONLY
int objscheme_istype_wxBufferData(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxBufferData(class wxBufferData *realobj);
class wxBufferData *objscheme_unbundle_wxBufferData(Scheme_Object *obj, const char *where, int nullOK);
#endif
