.\" dummy line
.TH MZC 1 "May 2010"
.UC 4
.SH NAME
mzc \- compatibility Racket compiler tool
.SH SYNOPSIS
.B mzc
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
.B mzc
provides an old interface to some Racket tools that are now
normally provided via
.BR raco .

.PP
Run
.PP
   mzc --help
.PP
for a list of command-line options.

.SH MORE INFORMATION
For further information, run
.PP
   raco docs
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://racket-lang.org/

.SH SEE ALSO
.BR raco(1),
.BR racket(1)
