#lang scheme/base
(require "init.rkt"
         "button.rkt"
         "canvas.rkt"
         "check-box.rkt"
         "choice.rkt"
         "clipboard.rkt"
         "cursor.rkt"
         "dialog.rkt"
         "frame.rkt"
         "gauge.rkt"
         "gl-context.rkt"
         "group-box.rkt"
         "group-panel.rkt"
         "item.rkt"
         "list-box.rkt"
         "menu.rkt"
         "menu-bar.rkt"
         "menu-item.rkt"
         "message.rkt"
         "panel.rkt"
         "printer-dc.rkt"
         "radio-box.rkt"
         "slider.rkt"
         "tab-group.rkt"
         "tab-panel.rkt"
         "window.rkt"
         "procs.rkt")
(provide platform-values)

(define (platform-values)
  (values
   button%
   canvas%
   check-box%
   choice%
   clipboard-driver%
   cursor-driver%
   dialog%
   frame%
   gauge%
   gl-context%
   group-box%
   group-panel%
   item%
   list-box%
   menu%
   menu-bar%
   menu-item%
   message%
   panel%
   printer-dc%
   radio-box%
   slider%
   tab-group%
   tab-panel%
   window%
   can-show-print-setup?
   show-print-setup
   id-to-menu-item
   file-selector
   is-color-display?
   get-display-depth
   has-x-selection?
   hide-cursor
   bell
   display-size
   display-origin
   get-resource
   write-resource
   flush-display
   fill-private-color
   cancel-quit
   get-control-font-size
   key-symbol-to-integer
   draw-tab-base
   draw-tab
   set-combo-box-font
   get-double-click-time
   run-printout
   file-creator-and-type
   send-event
   set-executer
   set-dialogs
   location->window
   set-menu-tester
   in-atomic-region
   shortcut-visible-in-label?
   unregister-collecting-blit
   register-collecting-blit
   find-graphical-system-path
   check-for-break
   play-sound
   get-panel-background
   get-font-from-user
   get-color-from-user
   application-pref-handler
   application-about-handler
   application-quit-handler
   application-file-handler
   special-option-key
   special-control-key
   get-highlight-background-color
   get-highlight-text-color))
