#reader(lib "docreader.ss" "scribble")
@require["common.ss"]
@require["diagrams.ss"]

@title[#:style '(toc quiet)]{Drawing Class Reference}

@local-table-of-contents[]

@require["bitmap-class.scrbl"]
@require["bitmap-dc-class.scrbl"]
@require["brush-class.scrbl"]
@require["brush-list-class.scrbl"]
@require["color-class.scrbl"]
@require["color-database-intf.scrbl"]
@require["dc-intf.scrbl"]
@require["dc-path-class.scrbl"]
@require["font-class.scrbl"]
@require["font-list-class.scrbl"]
@require["font-name-directory-intf.scrbl"]
@require["gl-config-class.scrbl"]
@require["gl-context-intf.scrbl"]
@require["pen-class.scrbl"]
@require["pen-list-class.scrbl"]
@require["point-class.scrbl"]
@require["post-script-dc-class.scrbl"]
@require["printer-dc-class.scrbl"]
@require["ps-setup-class.scrbl"]
@require["region-class.scrbl"]

@include-class[bitmap%]
@include-class[bitmap-dc%]
@include-class[brush%]
@include-class[brush-list%]
@include-class[color%]
@include-class[color-database<%>]
@include-class[dc<%>]
@include-class[dc-path%]
@include-class[font%]
@include-class[font-list%]
@include-class[font-name-directory<%>]
@include-class[gl-config%]
@include-class[gl-context<%>]
@include-class[pen%]
@include-class[pen-list%]
@include-class[point%]
@include-class[post-script-dc%]
@include-class[printer-dc%]
@include-class[ps-setup%]
@include-class[region%]
