#reader(lib "docreader.ss" "scribble")
@require["common.ss"]
@require["diagrams.ss"]

@title[#:style '(toc quiet)]{Windowing Class Reference}

Windows and controls:

@diagram->table[windowing-diagram]

Menus:

@diagram->table[menu-diagram]

Events and other:

@diagram->table[event-diagram]

Alphabetical:

@local-table-of-contents[]

@require["area-intf.scrbl"]
@require["area-container-intf.scrbl"]
@require["area-container-window-intf.scrbl"]
@require["button-class.scrbl"]
@require["canvas-intf.scrbl"]
@require["canvas-class.scrbl"]
@require["check-box-class.scrbl"]
@require["checkable-menu-item-class.scrbl"]
@require["choice-class.scrbl"]
@require["clipboard-client-class.scrbl"]
@require["clipboard-intf.scrbl"]
@require["combo-field-class.scrbl"]
@require["control-intf.scrbl"]
@require["control-event-class.scrbl"]
@require["cursor-class.scrbl"]
@require["dialog-class.scrbl"]
@require["event-class.scrbl"]
@require["frame-class.scrbl"]
@require["gauge-class.scrbl"]
@require["group-box-panel-class.scrbl"]
@require["grow-box-spacer-pane-class.scrbl"]
@require["horizontal-pane-class.scrbl"]
@require["horizontal-panel-class.scrbl"]
@require["key-event-class.scrbl"]
@require["labelled-menu-item-intf.scrbl"]
@require["list-box-class.scrbl"]
@require["list-control-intf.scrbl"]
@require["menu-class.scrbl"]
@require["menu-bar-class.scrbl"]
@require["menu-item-intf.scrbl"]
@require["menu-item-class.scrbl"]
@require["menu-item-container-intf.scrbl"]
@require["message-class.scrbl"]
@require["mouse-event-class.scrbl"]
@require["pane-class.scrbl"]
@require["panel-class.scrbl"]
@require["popup-menu-class.scrbl"]
@require["radio-box-class.scrbl"]
@require["selectable-menu-item-intf.scrbl"]
@require["separator-menu-item-class.scrbl"]
@require["scroll-event-class.scrbl"]
@require["slider-class.scrbl"]
@require["subarea-intf.scrbl"]
@require["subwindow-intf.scrbl"]
@require["tab-panel-class.scrbl"]
@require["text-field-class.scrbl"]
@require["timer-class.scrbl"]
@require["top-level-window-intf.scrbl"]
@require["vertical-pane-class.scrbl"]
@require["vertical-panel-class.scrbl"]
@require["window-intf.scrbl"]

@include-class[area<%>]
@include-class[area-container<%>]
@include-class[area-container-window<%>]
@include-class[button%]
@include-class[canvas<%>]
@include-class[canvas%]
@include-class[check-box%]
@include-class[checkable-menu-item%]
@include-class[choice%]
@include-class[clipboard<%>]
@include-class[clipboard-client%]
@include-class[combo-field%]
@include-class[control<%>]
@include-class[control-event%]
@include-class[cursor%]
@include-class[dialog%]
@include-class[event%]
@include-class[frame%]
@include-class[gauge%]
@include-class[group-box-panel%]
@include-class[grow-box-spacer-pane%]
@include-class[horizontal-pane%]
@include-class[horizontal-panel%]
@include-class[key-event%]
@include-class[labelled-menu-item<%>]
@include-class[list-box%]
@include-class[list-control<%>]
@include-class[menu%]
@include-class[menu-bar%]
@include-class[menu-item<%>]
@include-class[menu-item%]
@include-class[menu-item-container<%>]
@include-class[message%]
@include-class[mouse-event%]
@include-class[pane%]
@include-class[panel%]
@include-class[popup-menu%]
@include-class[radio-box%]
@include-class[scroll-event%]
@include-class[selectable-menu-item<%>]
@include-class[separator-menu-item%]
@include-class[slider%]
@include-class[subarea<%>]
@include-class[subwindow<%>]
@include-class[tab-panel%]
@include-class[text-field%]
@include-class[timer%]
@include-class[top-level-window<%>]
@include-class[vertical-pane%]
@include-class[vertical-panel%]
@include-class[window<%>]
