#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote string-constants/ukrainian-string-constants))
(check-docs (quote string-constants/traditional-chinese-string-constants))
(check-docs (quote string-constants/string-constant))
(check-docs (quote string-constants/spanish-string-constants))
(check-docs (quote string-constants/simplified-chinese-string-constants))
(check-docs (quote string-constants/russian-string-constants))
(check-docs (quote string-constants/portuguese-string-constants))
(check-docs (quote string-constants))
(check-docs (quote string-constants/korean-string-constants))
(check-docs (quote string-constants/japanese-string-constants))
(check-docs (quote string-constants/german-string-constants))
(check-docs (quote string-constants/french-string-constants))
(check-docs (quote string-constants/english-string-constants))
(check-docs (quote string-constants/dutch-string-constants))
(check-docs (quote string-constants/danish-string-constants))
