#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote dynext))
(check-docs (quote dynext/link))
(check-docs (quote dynext/link-unit))
(check-docs (quote dynext/link-sig))
(check-docs (quote dynext/filename-version))
(check-docs (quote dynext/file))
(check-docs (quote dynext/file-unit))
(check-docs (quote dynext/file-sig))
(check-docs (quote dynext/dynext))
(check-docs (quote dynext/dynext-unit))
(check-docs (quote dynext/dynext-sig))
(check-docs (quote dynext/compile))
(check-docs (quote dynext/compile-unit))
(check-docs (quote dynext/compile-sig))
