#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote compiler/zo-structs))
(check-docs (quote compiler/zo-parse))
(check-docs (quote compiler/zo-marshal))
(check-docs (quote compiler/xform))
(check-docs (quote compiler/to-core))
(check-docs (quote compiler/src2src))
(check-docs (quote compiler/sig))
(check-docs (quote compiler/option))
(check-docs (quote compiler/option-unit))
(check-docs (quote compiler))
(check-docs (quote compiler/find-exe))
(check-docs (quote compiler/embed))
(check-docs (quote compiler/embed-unit))
(check-docs (quote compiler/embed-sig))
(check-docs (quote compiler/distribute))
(check-docs (quote compiler/decompile))
(check-docs (quote compiler/compiler))
(check-docs (quote compiler/compiler-unit))
(check-docs (quote compiler/comp-unit))
(check-docs (quote compiler/cm))
(check-docs (quote compiler/cm-accomplice))
(check-docs (quote compiler/cffi))
(check-docs (quote compiler/bundle-dist))
