.\" dummy line
.TH DRSCHEME 1 "December 2005"
.UC 4
.SH NAME
drscheme \- The PLT Scheme programming environment
.SH SYNOPSIS
.B drscheme
[
.I Xoption ...
]
[
.I file ...
]
.SH DESCRIPTION
.I DrScheme
is the PLT Scheme
programming environment.
.PP
.I DrScheme
opens the files given as command-line arguments.
.pp
For further information on
.IR DrScheme ,
please consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.drscheme.org/
.SH X OPTIONS
When running in X11, DrScheme accepts the following standard
.IR Xoption s:
.B -display
.IR disp ,
.B -geometry
.IR geom ,
.B -bg
.IR color ,
.B -background
.IR color ,
.B -fg
.IR color ,
.B -foreground
.IR color ,
.B -fn
.IR font ,
.B -font
.IR font ,
.BR -iconic ,
.B -name
.IR name ,
.BR -rv ,
.BR -reverse ,
.BR +rv ,
.B -selectionTimeout
.IR time ,
.BR -synchronous ,
.B -title
.IR name ,
.B -xnllanguage
.IR lang ,
.B -xrm
.IR file .
.PP

.SH FILES
.I DrScheme
looks for its libraries using the environment variables
PLTHOME and PLTCOLLECTS.  If this variable is not defined,
the installation directory is assumed (usually
"/usr/local/lib/plt/"). See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
help-desk (encouraged),
or via the web
.ce 1
http://bugs.plt-scheme.org/ (discouraged)
or by e-mail to
.ce 1
bugs@plt-scheme.org (discouraged)
.SH AUTHOR
.I DrScheme
was implemented by PLT.
.SH SEE ALSO
.BR help-desk(1),
.BR mred(1),
.BR mzscheme(1)
