.\" dummy line
.TH DRSCHEME 1 "May 2010"
.UC 4
.SH NAME
drscheme \- the Racket programming environment
.SH SYNOPSIS
.B drscheme
[
.I Xoption ...
]
[
.I file ...
]
.SH DESCRIPTION
DrScheme is the old name for the Racket programming environment.

.PP
Running
.B drscheme
is the same as running
.BR drracket .

.SH SEE ALSO
.BR drracket(1)
