.\" dummy line
.TH HELP-DESK 1 "May 2006"
.UC 4
.SH NAME
help-desk \- The PLT Scheme documentation center
.SH SYNOPSIS
.B help-desk
.I term ...
.SH DESCRIPTION
.I Help Desk 
searches for term in the PLT Scheme documentation and opens an html document in a web browser with the results of the search.
.PP
For further information on
.I Help Desk,
please consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.drscheme.org/
.SH FILES
.I Help Desk
looks for its libraries using the environment variable
PLTCOLLECTS.  If this variable is not defined,
the installation directory is found automatically.
See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
drscheme (encouraged),
or via the web
.ce 1
http://bugs.plt-scheme.org/ (discouraged)
or by e-mail to
.ce 1
bugs@plt-scheme.org (discouraged)
.SH AUTHOR
PLT.
.SH SEE ALSO
.BR mzscheme(1),
.BR drscheme(1)
