.\" dummy line
.TH HELP-DESK 1 "January 2005"
.UC 4
.SH NAME
help-desk \- The PLT Scheme documentation center
.SH SYNOPSIS
.B help-desk
.SH DESCRIPTION
.I Help Desk 
contains all of the documentation for
the PLT suite of tools.
.PP
For further information on
.I Help Desk,
please consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.drscheme.org/
.SH FILES
.I Help Desk
looks for its libraries using the environment variables
PLTHOME and PLTCOLLECTS.  If this variable is not defined,
the installation directory is assumed (usually
"/usr/local/lib/plt/"). See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
help-desk (encouraged),
or via the web
.ce 1
http://bugs.plt-scheme.org/ (discouraged)
or by e-mail to
.ce 1
bugs@plt-scheme.org (discouraged)
.SH AUTHOR
.I Help Desk 
was implemented by Paul Steckler, Robby Findler, and Matthew Flatt.
The documentation was written by PLT.
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1),
.BR drscheme(1)
