.\" dummy line
.TH HELP-DESK 1 "May 2006"
.UC 4
.SH NAME
help-desk \- The PLT Scheme documentation center
.SH SYNOPSIS
.B help-desk
[
.I Xoption ...
]
.SH DESCRIPTION
.I Help Desk 
contains all of the documentation for
the PLT suite of tools.
.PP
For further information on
.I Help Desk,
please consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.drscheme.org/
.SH X OPTIONS
When running in X11, Help Desk accepts the following standard
.IR Xoption s:
.B -display
.IR disp ,
.B -geometry
.IR geom ,
.B -bg
.IR color ,
.B -background
.IR color ,
.B -fg
.IR color ,
.B -foreground
.IR color ,
.B -fn
.IR font ,
.B -font
.IR font ,
.BR -iconic ,
.B -name
.IR name ,
.BR -rv ,
.BR -reverse ,
.BR +rv ,
.B -selectionTimeout
.IR time ,
.BR -synchronous ,
.B -title
.IR name ,
.B -xnllanguage
.IR lang ,
.B -xrm
.IR file .
.PP
.SH FILES
.I Help Desk
looks for its libraries using the environment variable
PLTCOLLECTS.  If this variable is not defined,
the installation directory is found automatically.
See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
help-desk (encouraged),
or via the web
.ce 1
http://bugs.plt-scheme.org/ (discouraged)
or by e-mail to
.ce 1
bugs@plt-scheme.org (discouraged)
.SH AUTHOR
.I Help Desk 
was implemented by Robby Findler, Matthew Flatt, and Paul Steckler.
The documentation was written by PLT.
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1),
.BR drscheme(1)
