\" dummy line
.TH MRED 1 "January 2008"
.UC 4
.SH NAME
mred \- The PLT Graphical Scheme implementation
.SH SYNOPSIS
.B mred
[
.I option ...
] [
.I argument ...
]

.SH DESCRIPTION
MrEd
is the PLT graphical Scheme
implementation.
It embeds and extends 
MzScheme
with a graphical user interface (GUI) toolbox.

.PP
Run
.PP
   mred --help
.PP
for a list of command-line options and other start-up information.

.PP
Supplying no arguments to
.B mred
is the same as supplying the
.B -i
option for interactive evaluation.

.PP
Supplying a single non-switch argument to
.B mred
is the same as putting
.B -u
before the argument to run it as a module-based script.

.SH MORE INFORMATION
For further information, run
.PP
   plt-help
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.plt-scheme.org/software/mred/

.SH AUTHOR
MrEd was implemented by Matthew Flatt (mflatt@plt-scheme.org),
Robert Bruce Findler (robby@plt-scheme.org), and
John Clements (clements@plt-scheme.org), based on
MzScheme.

.SH SEE ALSO
.BR plt-help(1),
.BR drscheme(1),
.BR mzscheme(1)
