.\" dummy line
.TH MZC 1 "January 2008"
.UC 4
.SH NAME
mzc \- The PLT Scheme compiler tool
.SH SYNOPSIS
.B mzscheme
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
.B mzc
performs various tasks such as compiling Scheme source to bytecode,
packaging executables, and packaging installable archives.

.PP
Run
.PP
   mzc --help
.PP
for a list of command-line options.

.SH MORE INFORMATION
For further information, run
.PP
   plt-help
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.plt-scheme.org/software/mzc/

.SH AUTHOR
.B mzc
was implemented by PLT, http://www.plt-scheme.org/.
.SH SEE ALSO
.BR plt-help(1),
.BR mzscheme(1),
.BR drscheme(1)
