.\" dummy line
.TH MZSCHEME 1 "January 2008"
.UC 4
.SH NAME
mzscheme \- The PLT Scheme implementation
.SH SYNOPSIS
.B mzscheme
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
MzScheme
is the PLT
Scheme implementation.

.PP
Run
.PP
   mzscheme --help
.PP
for a list of command-line options and other start-up information.

.PP
Supplying no arguments to
.B mzscheme
is the same as supplying the
.B -i
option for interactive evaluation.

.PP
Supplying a single non-switch argument to
.B mzscheme
is the same as putting
.B -u
before the argument to run it as a module-based script.

.SH MORE INFORMATION
For further information, run
.PP
   plt-help
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.plt-scheme.org/software/mzscheme/

.SH AUTHOR
MzScheme
was implemented by Matthew Flatt (mflatt@plt-scheme.org).
It was originally based on libscheme, written by Brent Benson.
.SH SEE ALSO
.BR plt-help(1),
.BR drscheme(1),
.BR mred(1),
.BR setup-plt(1),
.BR mzc(1)
