.\" dummy line
.TH PLT-Help 1 "January 2008"
.UC 4
.SH NAME
plt-help \- The PLT Scheme documentation center
.SH SYNOPSIS
.B plt-help
[\c
.I -x\c
] [\c
.I --exact\c
] [\c
.IR term \ ...]
.SH DESCRIPTION
PLT Help 
searches for term in the PLT Scheme documentation.
It opens a locally generated HTML document in a web
browser with results of a search.
.PP
For further information on PLT Help, run it. Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.drscheme.org/
.SH AUTHOR
PLT Help is implemented by PLT, http://www.plt-scheme.org/.
.SH SEE ALSO
.BR drscheme(1),
.BR mzscheme(1),
.BR mred(1)
