.\" dummy line
.TH SETUP-PLT 1 "January 2008"
.UC 4
.SH NAME
setup-plt \- The PLT Scheme setup tool
.SH SYNOPSIS
.B setup-plt
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
Setup PLT
performs various installation and setup tasks for a PLT Scheme
installation.

.PP
Run
.PP
   setup-plt --help
.PP
for a list of command-line options.

.SH MORE INFORMATION
For further information, run
.PP
   plt-help
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.plt-scheme.org/

.SH AUTHOR
Setup PLT
was implemented by PLT, http://www.plt-scheme.org/.
.SH SEE ALSO
.BR plt-help(1),
.BR mzscheme(1),
.BR drscheme(1)
