.\" dummy line
.TH SETUP-PLT 1 "May 2010"
.UC 4
.SH NAME
setup-plt \- compatibility Racket setup tool
.SH SYNOPSIS
.B setup-plt
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
.B setup-plt
provides an old interface to some Racket tools that are now
normally provided via
.BR raco .

.PP
Run
.PP
   setup-plt --help
.PP
for a list of command-line options.

.SH MORE INFORMATION
For further information, run
.PP
   raco help
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://racket-lang.org/

.SH SEE ALSO
.BR raco(1),
.BR racket(1)
