#!/bin/sh

run() {
  exe="gracket"
  if [ "x$1" = "x-t" ]; then exe="racket"; fi
  "$exe" "$1"
  echo "done:--- $1 ---"
  echo ""
}

run bad-draw.rkt
run -t batch-io.rkt
run clause-once.rkt
run full-scene-visible.rkt
run image-too-large.rkt
run image-equality-performance-htdp.rkt
run image-equality-performance.rkt
run mouse-evt.rkt
run on-tick-defined.rkt
run perform-robby.rkt
run profile-robby.rkt
run release.rkt
run stop.rkt
run test-image.rkt
run ufo-rename.rkt
run server-rename.rkt
run world0-stops.rkt
run record.rkt
run record-stop-when.rkt
run stop-when-crash.rkt
