#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote graphics/value-turtles))
(check-docs (quote graphics/value-turtles-test))
(check-docs (quote graphics/value-turtles-examples))
(check-docs (quote graphics/turtles))
(check-docs (quote graphics/turtle-test))
(check-docs (quote graphics/turtle-examples))
(check-docs (quote graphics))
(check-docs (quote graphics/graphics))
(check-docs (quote graphics/graphics-unit))
(check-docs (quote graphics/graphics-sig))
(check-docs (quote graphics/graphics-posn-less-unit))
