#lang racket/base
(require tests/utils/docs-complete)
(check-docs (quote planet/version))
(check-docs (quote planet/util))
(check-docs (quote planet/syntax))
(check-docs (quote planet/scribble))
(check-docs (quote planet/resolver))
(check-docs (quote planet/raco))
(check-docs (quote planet/planet))
(check-docs (quote planet/planet-archives))
(check-docs (quote planet/parsereq))
(check-docs (quote planet/config))
(check-docs (quote planet/cachepath))
