#lang racket/base
(require rackunit/docs-complete)
(check-docs (quote setup/xref))
(check-docs (quote setup/winvers))
(check-docs (quote setup/winvers-change))
(check-docs (quote setup/variant))
(check-docs (quote setup/unpack))
(check-docs (quote setup/unixstyle-install))
(check-docs (quote setup/setup-unit))
(check-docs (quote setup/setup-go))
(check-docs (quote setup/setup-cmdline))
(check-docs (quote setup/scribble))
(check-docs (quote setup/plt-single-installer))
(check-docs (quote setup/plt-installer))
(check-docs (quote setup/plt-installer-unit))
(check-docs (quote setup/plt-installer-sig))
(check-docs (quote setup/path-relativize))
(check-docs (quote setup/parallel-do))
(check-docs (quote setup/parallel-build))
(check-docs (quote setup/pack))
(check-docs (quote setup/option-unit))
(check-docs (quote setup/option-sig))
(check-docs (quote setup))
(check-docs (quote setup))
(check-docs (quote setup))
(check-docs (quote setup/dirs))
(check-docs (quote setup/configtab))
(check-docs (quote setup/collects))
