#lang info

(define collection 'multi)

(define deps '("algol60"
               "at-exp-lib"
               "compatibility"
               "contract-profile"
               "data-lib"
               "datalog"
               "db"
               "deinprogramm"
               "draw"
               "draw-doc"
               "draw-lib"
               "drracket"
               "eopl"
               "errortrace"
               "frtime"
               "future-visualizer"
               "future-visualizer-typed"
               "games"
               "gui"
               "htdp"
               "html"
               "icons"
               "images"
               "lazy"
               "macro-debugger"
               "macro-debugger-text-lib"
               "make"
               "math"
               "mysterx"
               "mzcom"
               "mzscheme"
               "parser-tools"
               "pconvert-lib"
               "pict"
               "picturing-programs"
               "plai"
               "plot"
               "preprocessor"
               "profile"
               "r5rs"
               "r6rs"
               "racket-doc"
               "distributed-places-doc"
               "racket-index"
               "racket-lib"
               "racklog"
               "rackunit-lib"
               "readline"
               "realm"
               "redex"
               "sandbox-lib"
               "schemeunit"
               "scribble"
               "sgl"
               "shell-completion"
               "slatex"
               "slideshow"
               "snip"
               "srfi"
               "string-constants-lib"
               "swindle"
               "syntax-color"
               "trace"
               "typed-racket"
               "typed-racket-more"
               "unstable"
               "unstable-contract-lib"
               "unstable-latent-contract-lib"
               "unstable-list-lib"
               "unstable-options-lib"
               "unstable-parameter-group-lib"
               "unstable-flonum-doc"
               "unstable-redex"
               "web-server"
               "wxme"
               "xrepl"
               "ds-store"))

(define pkg-desc "A package that combines all of the packages in the main Racket distribution")

(define pkg-authors '(eli jay matthias mflatt robby))
