.\" dummy line
.TH MZSCHEME 1 "May 2010"
.UC 4
.SH NAME
mzscheme \- compatibility executable for Racket
.SH SYNOPSIS
.B mzscheme
[
.I option ...
] [
.I argument ...
]
.SH DESCRIPTION
MzScheme is the old name for the core Racket implementation.

.PP
For most cases, running
.B mzscheme
is the same as running
.BR racket ,
except that the default interaction language is slightly
different for backward compatibility.

.SH MORE INFORMATION
For further information, run
.PP
   raco docs
.PP
to open installed documentation in your web browser.

.PP
Alternately, consult the on-line
documentation and other information available at
.PP
.ce 1
http://racket-lang.org/

.SH SEE ALSO
.BR racket(1)
